### ISSUE TITLE
Too many MAB fields mapped to otherTitleInformation

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#108]
Example: http://lobid.org/nwbib/CT003012479

E.g. fields 361, 370a, 805b probably should be mapped to other properties.

**Comment by acka47** [comment]
Regexps from [current morph](https://github.com/lobid/lodmill/blob/10654588eb53225c8e274380dd27eba843b38a44/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml):
- `33[13][-ab][-1].a` ([l. 510](https://github.com/lobid/lodmill/blob/10654588eb53225c8e274380dd27eba843b38a44/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L510)
- `335[-abcd][-12].a|370[a][-12].a` ([l. 523](https://github.com/lobid/lodmill/blob/10654588eb53225c8e274380dd27eba843b38a44/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L523))
- `35[012345][-ab][-1].a` ([l. 525](https://github.com/lobid/lodmill/blob/10654588eb53225c8e274380dd27eba843b38a44/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L525))
- `36[0123456789][-abcd][-12].a` ([l. 526](https://github.com/lobid/lodmill/blob/10654588eb53225c8e274380dd27eba843b38a44/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L526))
- `8[012][0123456789][-ab][-12].a|C[136][0135][-ab][-12].a` ([l. 529](https://github.com/lobid/lodmill/blob/10654588eb53225c8e274380dd27eba843b38a44/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L529))

**Comment by acka47** [comment]
MAB field `361       BEIGEFUEGTE WERKE` shouldn't be added to `otherTitleInformation`. Will have to look where else to put it, though.

**Comment by acka47** [comment]
And we shouldn't show the contents of `370       WEITERE SACHTITEL` in NWBib which means that we need a separate property for this.

**Comment by acka47** [comment]
Here is another example edoweb folks got feedback on: http://lobid.org/resource/HT017379873/about. The problem here is that 370a (`370       WEITERE SACHTITEL`) is mapped to `otherTitleInformation`. I suggest just removing it from the morph.

**Comment by acka47** [comment]
We shoulkd probably also kick out the entire 36*s off `otherTitleInformation`:

```
360       UNTERREIHEN

          Indikator:
          blank = nicht definiert


361       BEIGEFUEGTE WERKE

          Indikator:
          blank = nicht definiert


365       ZUSAETZE ZUR GESAMTEN VORLAGE

          Indikator:
          blank = nicht definiert


369       VERFASSERANGABE ZUR GESAMTEN VORLAGE

          Indikator:
          blank = nicht definiert
```

**Comment by acka47** [comment]
MAB doc on 35*s:
```
352       4. PARALLELSACHTITEL IN ANSETZUNGSFORM
353       4. PARALLELSACHTITEL IN VORLAGEFORM ODER MISCHFORM
354       ZU ERGAENZENDE URHEBER ZUM 4. PARALLELSACHTITEL
355       ZUSAETZE ZUM 4. PARALLELSACHTITEL


359       VERFASSERANGABE

          Indikator:
          blank = nicht definiert
```
As we don't add info from the 34*s on "Parallelsachtitel" to `otherTitleInformation` we neither should add 35*s.

What is a "Parallelsachtitel" anyway? [RAK-WB](http://files.d-nb.de/pdf/rak_wb_netz.pdf), §28, 4. reads:
> Fassungen des Haupttitels in anderen Sprachen und/oder Schriften werden ... als
Paralleltitel bezeichnet.

**Comment by acka47** [comment]
I would also leave out the 8**s. MAB doc:

```
8--   Segment Nichtstandardmaessige Nebeneintragungen (NE)

800       PERSON DER 1. NE

          Indikator:
          blank = nicht definiert


801       VERWEISUNGSFORM ZUR PERSON DER 1. NE

          Indikator:
          blank = nicht definiert


802       KOERPERSCHAFT DER 1. NE

          Indikator:
          blank = nicht definiert


803       VERWEISUNGSFORM ZUR KOERPERSCHAFT DER 1. NE

          Indikator:
          blank = nicht definiert


804       EINHEITSSACHTITEL DER 1. NE

          Indikator:
          blank = nicht definiert


805       SACHTITEL DER 1. NE

          Indikator:
          a = Ansetzungsform
          b = Mischform


806       PERSON DER 2. NE
807       VERWEISUNGSFORM ZUR PERSON DER 2. NE
808       KOERPERSCHAFT DER 2. NE
809       VERWEISUNGSFORM ZUR KOERPERSCHAFT DER 2. NE
810       EINHEITSSACHTITEL DER 2. NE
811       SACHTITEL DER 2. NE

...

824       PERSON DER 5. NE
825       VERWEISUNGSFORM ZUR PERSON DER 5. NE
826       KOERPERSCHAFT DER 5. NE
827       VERWEISUNGSFORM ZUR KOERPERSCHAFT DER 5. NE
828       EINHEITSSACHTITEL DER 5. NE
829       SACHTITEL DER 5. NE
```

**Comment by acka47** [comment]
Following the comments above, here is a to do list for @dr0i. Please remove the following MAB fields from inclusion in `otherTitleInformation`.

- [ ] 361
- [ ] 370
- [ ] 36*s
- [ ] 35*s
- [ ] 8*s

**Comment by dr0i** [comment]
See 40b258aec5bba4715ef509b9b95486e35f737a73.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
