### ISSUE TITLE
One organisation is now two

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#114]
See e.g. http://lobid.org/organisation/DE-9/about or http://lobid.org/organisation/DE-1a/about or `curl -L -H "Accept: text/turtle"  http://lobid.org/organisation/DE-3` which's response looks like (snippet):
```
<http://lobid.org/organisation/DE-3>
      a       <http://xmlns.com/foaf/0.1/Organization> ;
...

<http://lobid.org/organisation/DE-3>
      a       <http://xmlns.com/foaf/0.1/Organization> ;
...
```

**Comment by dr0i** [comment]
There were two elasticsearchers aliases with the same name. This is an issue regarding automatic alias creation, see also #643.
I fixed the issue by manually deleting one alias. However, the issue must also be fixed in the code, so I leave this issue open.

**Comment by acka47** [comment]
@dr0i Has this something to do with lobid/lodmill#609? Can we maybe close this one now?

**Comment by dr0i** [comment]
No, it's not lobid/lodmill#609. But the issue can be avoided when setting the parameters of the indexer right.( Now. There is stuff to do , the programm is too complicated. But we leave it is at is for now.)
