### ISSUE TITLE
Add corporateBody parameter to /resource API endpoint

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#121]
To implement a "Körperschaftssuche" in NWBib (see https://github.com/hbz/nwbib/issues/54) we will implement a separate API parameter `corporateBody`. It should query the following fields:
- `contributingCorporateBodyLabel`
- And to enable search by GND ID: `dct:creator` and `dct:contributor` (This will also allow search by GND ID for persons via this parameter which is ok for now.)

**Comment by fsteeg** [comment]
Deployed to staging, using `corporation` as parameter name as agreed offline. See:

http://test.lobid.org/resource?corporation=Werkbund+NW
http://test.lobid.org/resource?corporation=http://d-nb.info/gnd/2172019-8
http://test.lobid.org/resource?corporation=2172019-8

**Comment by acka47** [comment]
+1
