### ISSUE TITLE
Add subject headings without GND links to RDF

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#122]
See e.g. http://lobid.org/resource?id=BT000040377&format=source (to be added to testset). It contains the following data:

```
<datafield tag="902" ind1="-" ind2="1">
    <subfield code="a">Rheine</subfield>
    <subfield code="a">Vogelschutz</subfield>
</datafield>
<datafield tag="907" ind1="-" ind2="1">
    <subfield code="a">Vogelschutz</subfield>
    <subfield code="a">Rheine</subfield>
</datafield>
```

You can't find "Vogelschutz" or "Rheine" in http://lobid.org/resource/BT000040377, though. Neither in `dc:subject` nor in `lv:subjectChain`.

Other examples:
- http://lobid.org/resource?id=BT000041074&format=source
- http://lobid.org/resource?id=BT000040274&format=source
- http://lobid.org/resource?id=BT000050299&format=source

It looks like this should be added to `lv:subjectChain`. Will explore this further tomorrow.

**Comment by acka47** [comment]
As this data is shown in the Aleph OPAC with label "1. Schlagwortkette", "2. Schlagwortkette" etc. (see e.g. [here](http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DBT000040377) or [here(http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DBT000041074)) we should add this to `lv:subjectChain` in lobid.

**Comment by dr0i** [comment]
This issue is already resolved by #39 , see https://github.com/lobid/lodmill/pull/647/files#diff-1b113d0a603f2694c6ff079a3fab3ebfR954.

Test it: http://test.lobid.org/resource?id=BT000040377 .

**Comment by acka47** [comment]
Nice. But I think our customers will want the information displayed in NWBib as "Schlagwortkette" so that I think we'll have to move it to `lv:subjectChain`.

**Comment by dr0i** [comment]
How to concatenate the subjects? They are in the same subfield `a` - should they be concatenated with just a space between these entries, or using a comma or ..?

**Comment by acka47** [comment]
To be consistent, you should do it the same way as current subject headings are generated: using space-pipe-space (` | `) between each part. See e.g. http://lobid.org/resource/HT018473848/about.

**Comment by acka47** [comment]
Deployed to production. Closing.
