### ISSUE TITLE
Get rid of api.lobid.org and staging.api.lobid.org

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#123]
As far as I can see are redundant to `lobid.org` resp. `test.lobid.org`. Configuring the Apache server this redundancy made things more complicated. Also, these redundant URLs add confusion for lobid users.

@dr0i and I propose to deprecate  `api.lobid.org` and `staging.api.lobid.org` starting with a 301 to `lobid.org` resp. `test.lobid.org`. (Of course we will replace these URLs in the lobid, lodmill and nwbib code where they occur infrequently.)

@fsteeg : Any objections?

**Comment by fsteeg** [comment]
Sounds good. I'd suggest to leave the redirect (at least) until we publish a 2.0 API.

**Comment by dr0i** [comment]
Done. Configured `api` to be elevated one domain level higher using redirection (http status code 301).
So deprecated URIs will work for now all right, e.g. `http://api.lobid.org/resource?id=HT002189125`.
TBD: Will clean all code and examples using the `api` subdomain.

**Comment by dr0i** [comment]
Pinging also @jschnasse @literarymachine @ahagenbruch for information (sorry folks, should have ping you *before* configuring that redirect (because it _might_ break applications)).

**Comment by ahagenbruch** [comment]
Thanks for the heads-up. Everything still working smoothly here...

**Comment by acka47** [comment]
Works. Closing.
