### ISSUE TITLE
Statistics and privacy

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#125]
The stats 
- [x] shouldn't be readable by everyone and a 
- [ ] a privacy policy should be added to the footer reading as follows:

> For the purpose of usage statistics, lobid.org automatically stores a log file of the data which your browser sends when visiting the page, specifically:
> - IP-Address
> - Browsertype and -version
> - Operating System
> - Referrer URL (the page, from which this page was linked, including the search term, in case of a search engine)
> - Time and date of the request

**Comment by dr0i** [comment]
The pages aren't accessible from outside the hbz network:

$ wget 'http://stats.lobid.org'
--2015-03-12 15:44:25--  http://stats.lobid.org/
Auflösen des Hostnamen »stats.lobid.org (stats.lobid.org)«... 193.30.112.187
Verbindungsaufbau zu stats.lobid.org (stats.lobid.org)|193.30.112.187|:80... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 403 Forbidden
2015-03-12 15:44:26 FEHLER 403: Forbidden.

**Comment by dr0i** [comment]
ticket refers to hbz/nwbib#91.

**Comment by ChristophEwertowski** [comment]
See https://github.com/hbz/lobid-resources/issues/799.

**Comment by acka47** [comment]
As this is covered by https://github.com/hbz/lobid-resources/issues/799 and the whole DSGVO work, I am closing this issue.
