### ISSUE TITLE
Serving XML with one root element 

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#126]
E.g. `curl -L --header "Accept: application/rdf+xml" http://api.lobid.org/resource?id=HT002189125` results in a document having two root elements. A file with many Xml root nodes is not well-formed Xml. The two nodes should be contained under one root element.
This was reported Werner Greßhoff .

**Comment by acka47** [comment]
Looks similar or even redundant to https://github.com/lobid/lodmill/issues/463. @dr0i What do you think: Can we close one of these?

**Comment by dr0i** [comment]
Yes, closing.
