### ISSUE TITLE
Umlaut issue in title HT014720390

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#130]
http://lobid.org/resource/HT014720390

**Comment by acka47** [comment]
This isn't restricted to this one title, see e.g. http://lobid.org/resource?name=f%C3%BCr.

**Comment by acka47** [comment]
Solved. Closing. For the sake of complete documentation on here I will add three emails by @jschnasse's (in German) in the comments below.

**Comment by acka47** [comment]
On 19.03.2015 15:15, Jan Schnasse wrote:> 
Hallo Ihr,
> 
> letztlich lag das Umlauteproblem also nur an ein paar Umgebungsvariablen
> auf Phillips [= @philboeselager] Rechner, die mit der Zeile "SendEnv LC_*" in
> /etc/ssh/ssh_config in die Serverumgebung injiziert wurden. Bin ich
> froh, dass wir das nun raus bekommen haben! Sollte man echt verbieten so
> einen Unfug!
> 
> Warum die Applikation ursprünglich abgestürzt war, wissen wir aber immer
> noch nicht!
> 
> Viele Grüße und lang lebe lobid!
> Jan
