### ISSUE TITLE
Wrong title information

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#134]
Reported by @jschnasse via email.

http://lobid.org/resource/HT017004654 only has title information data from MAB field 333 in the RDF but nothing from 331 which should be prefered. 

MAB field 310 (`HAUPTSACHTITEL IN ANSETZUNGSFORM`) is missing in the [source data](http://lobid.org/resource?id=HT017004654&format=source), we only have 331 (`HAUPTSACHTITEL IN VORLAGEFORM ODER MISCHFORM`) and 333 (`ZU ERGAENZENDE URHEBER ZUM HAUPTSACHTITEL`):

```xml
<datafield tag="331" ind1="-" ind2="1">
    <subfield code="a">Einbürgerungen in Koblenz</subfield>
</datafield>
<datafield tag="333" ind1="-" ind2="1">
    <subfield code="a">Stadt Koblenz, Hauptamt, Abt. Statistik</subfield>
</datafield>
```

Currently this RDF is generated from source (snippet):
```
<http://lobid.org/resource/HT017004654> <http://purl.org/dc/terms/title> "Stadt Koblenz, Hauptamt, Abt. Statistik" .
```

I can't see why 331 isn't taken into account. Relevant lines in current morph are [505-528](https://github.com/lobid/lodmill/blob/f1f3b4af82ca17935756a5d6d4bbbdc0dac3382b/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L505-L528):

```xml
	
<!-- ####################### -->
<!-- ########## title -->
<!-- ####################### -->
<data source="304[-a]1.a" name="http://purl.org/dc/terms/alternative"/>
<data source="310[-ab][-12].a" name="@title"/>
<data source="@title" name="http://purl.org/dc/terms/title">
    <replace pattern="&gt;" with=""/>
    <replace pattern="&lt;" with=""/>
</data>
<!-- has other title information. If no title exists yet, use this as title. -->
<combine name="@otherTitle" value="${titleRemainder}" sameEntity="true">
    <data source="@title"/>
    <data source="33[13][-ab][-1].a" name="titleRemainder">
        <regexp match="(.*)" format="${1}"/>
    </data>
</combine>
<combine name="@title" value="${title}">
    <if>
        <none>
            <data source="@title"/>
        </none>
    </if>
    <data source="33[13][-ab][-1].a" name="title"/>
</combine>```

**Comment by acka47** [comment]
Probably the first (331) is overwritten by the second (333) when both occur. What do you think, @dr0i?

**Comment by acka47** [comment]
More examples from the edoweb colleagues: HT016175600, HT015225938, HT014169524, HT018456404, HT017188373, HT017700492, HT017004654, HT017004696

**Comment by dr0i** [comment]
No resource you provided is already part of the test data. But try http://test.lobid.org/resource/HT003160768 , it reflects the same problem.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production.
