### ISSUE TITLE
Simplify json results: provide always the same data type for fields

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#136]
Reported by Werner Greßhoff:
Some elements are sometimes delivered as single values, sometimes as arrays. Thus, working on that data, each time such a field is parsed it is necessary to check if it's a single value or an array. Much easier would be to _always have one consistent data type_ ( @dr0i: This would be an array, then). People behind entityfacts are doing it in this customer friendly manner.

**Comment by fsteeg** [comment]
This could be easily implemented using the `compactArrays=false` option while compacting our JSON-LD, but this has very broad effects, as all values will then be wrapped in arrays, even for fields that never have multiple values (like `issued`, or `hbzId`). This would break API users that process these fields as simple values. I would therefore prefer to switch to that in API 2.0 (https://github.com/hbz/lobid/issues/1).

What do you think, @dr0i @acka47?

**Comment by acka47** [comment]
> This would break API users that process these fields as simple values. I would therefore prefer to switch to that in API 2.0

+1

**Comment by dr0i** [comment]
Don't we actually use only arrays?

**Comment by fsteeg** [comment]
In 1.x we do not, see: http://lobid.org/resource?id=HT000970912&format=full

**Comment by acka47** [comment]
As we won't fix this in 1.x, we might as well close the issue.

**Comment by dr0i** [comment]
Ack. Closing.
