### ISSUE TITLE
Add predecessors and successors (formerly: Include MAB fields 530 to 533 in RDF)

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#137]
As asked for by NWBib customers, see https://wiki1.hbz-nrw.de/x/FoDgAw -> Funktionsvergleich "Einzeltrefferanzeige", 2.1.
From the [MAB documentation](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mabTitelBibliographischeDaten2001.txt?__blob=publicationFile):

```
530       TITEL VON BEZUGSWERKEN

          Indikator:
          blank = verbale Beschreibung
          x     = reziproke Beziehung
          y     = nicht reziproke Beziehung
          z     = nicht differenzierte Beziehung


531       HINWEISE AUF FRUEHERE AUSGABEN UND BAENDE

          Indikator:
          blank = verbale Beschreibung
          x     = reziproke Beziehung
          y     = nicht reziproke Beziehung
          z     = nicht differenzierte Beziehung


532       HINWEISE AUF FRUEHERE UND SPAETERE SOWIE ZEITWEISE
          GUELTIGE TITEL

          Indikator:
          blank = verbale Beschreibung
          x     = reziproke Beziehung
          y     = nicht reziproke Beziehung
          z     = nicht differenzierte Beziehung


533       HINWEISE AUF SPAETERE AUSGABEN UND BAENDE

          Indikator:
          blank = verbale Beschreibung
          x     = reziproke Beziehung
          y     = nicht reziproke Beziehung
          z     = nicht differenzierte Beziehung
```

Links have to be included into NWBib after implementation.

**Comment by dr0i** [comment]
Ok, but what properties shall we use?

**Comment by dr0i** [comment]
Also there is possible the same problem mentioned in https://github.com/hbz/lobid-resources/issues/200#issuecomment-277987790.

**Comment by acka47** [comment]
NWBib customer didn't ask for it again. Removing the PI 2.0 tag as we can also do this later.

**Comment by ChristophEwertowski** [comment]
Looked for properties which could be used to express the contents of the MAB fields:
530 (Titel von Bezugswerken): Don't know if we should implement this. The relationship to related resources could be expressed but the title shouldn't be added to the relation. http://id.loc.gov/ontologies/bibframe/relatedTo could work.
531 (Hinweise auf frühere Ausgaben und Bände): http://id.loc.gov/ontologies/bibframe/precededBy (owl:ObjectProperty) or http://id.loc.gov/ontologies/bibframe/replacementOf (owl:ObjectProperty)
532 (Hinweise auf frühere und spätere sowie zeitweise gültige Titel): The nearest thing would be something like http://id.loc.gov/ontologies/bibframe/variantType (literal)
533 (Hinweise auf spätere Ausgaben und Bände): http://id.loc.gov/ontologies/bibframe/succeededBy (owl:ObjectProperty)

To do:
* [ ] Looking what's in the fields
* [ ] Drawing a json structure

**Comment by ChristophEwertowski** [comment]
http://lobid.org/hbz01/HT017317344 (530, 531) and http://lobid.org/hbz01/HT002191548 (532, 533) are examples for resources which have the wanted fields. All fields have three subfields:
* p: what is referenced to (531, 533)? Erscheinungsweise (530, 532). Not standardisied
* a: title
* 9: contains the HT numbers
```
relationships: [
    {id: http://lobid.org/resources/[XYZ];
    type: example.org/precededBy},   
    {id: http://lobid.org/resources/[XYZ];
    type: example.org/succeededBy},
    {id: http://lobid.org/resources/[XYZ];
    type: example.org/undefinedRelationship}
]
```
The fields 530 and 532 I would map to the last object.
The titles of the MAB fields don't have to be included into the RDF/JSONLD. For the two examples only in one case the subfield a didn't match the title (the second 530 field in the first example) and instead a "Zusatz zum Sachtitel" was inserted.

**Comment by ChristophEwertowski** [comment]
About the title in the subfield a: If we want to show the titles as links and not a clickable search like "Enthält" "XYZ Beiträge" we have to include them. Under point one it's stated that the linking should work like in the old NWBib: What was that like?
Another question for implementation is: Exists for every preceding resource at least one succeeding resource and vice versa or would we have links in one direction only?
@acka47 : Need your feedback.

**Comment by acka47** [comment]
Generally, the only fields that actually make the relation clear are `531` (predecessor) and `533` (successor). Thus I suggest to follow the ZDB (see e.g. `curl -L -H "Accept: text/turtle" http://ld.zdb-services.de/resource/2673588-X`) and use http://rdaregistry.info/Elements/u/P60261 for the former and http://rdaregistry.info/Elements/u/P60278 for the latter adding the ID (subfield `9`) and label (subfield `a`) of the resource to an object. This would mean ignoring `530` and `532` for now. For the examples the result would look like this:

```json
{
  "@context": {
    "predecessor": {
      "type": "@id",
      "@id": "http://rdaregistry.info/Elements/u/P60261"
    },
    "successor": {
      "type": "@id",
      "@id": "http://rdaregistry.info/Elements/u/P60278"
    }
  },
  "id": "http://lobid.org/hbz01/HT017317344",
  "predecessor": {
    "id": "http://lobid.org/resources/HT014507359",
    "label": "TM Düsseldorf fashion guide"
  }  
}
```

```json
{
  "@context": {
    "predecessor": {
      "type": "@id",
      "@id": "http://rdaregistry.info/Elements/u/P60261"
    },
    "successor": {
      "type": "@id",
      "@id": "http://rdaregistry.info/Elements/u/P60278"
    }
  },
  "id": "http://lobid.org/hbz01/HT002191548",
  "successor": {
    "id": "http://lobid.org/resources/HT013374914",
    "label": "Essen: Statistischer Halbjahresbericht der Stadt Essen"
  }  
}
```

**Comment by ChristophEwertowski** [comment]
Added predecessor and successor. See [example json](http://test.lobid.org/resources/HT002619538?format=json). The brackets were also removed, see [example (test)](http://test.lobid.org/resources/HT000009600?format=json) and [example (production, MAB field 533)](http://lobid.org/hbz01/HT000009600).
In the test set are many predecessors and successors which have an ind2, e.g. weren't catalogued with an original. Shall we take them into account nonetheless?

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.

**Comment by acka47** [comment]
Reopening, as predecessors without ID are missing, for example http://lobid.org/resources/HT001236436

**Comment by ChristophEwertowski** [comment]
Also missing for RDA entries, e.g. [HT019498390](https://lobid.org/resources/HT019498390). Requested by edoweb customers so inform jschnasse after this ticket is done. Also update table at [hbz Wolke](https://wolke.hbz-nrw.de/index.php/apps/onlyoffice/9522).
