### ISSUE TITLE
GND subject name doesn't favour exact matches

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#138]
Querying http://lobid.org/subject?name=verkehr the first hits are _not_ docs with exact matches but word compunds. The cause is the usage of `ngram_analyzer` in the  index profile to enable auto suggestion. However, a `subject name` query should result in only `exact` matches or, maybe even nicer, serving also word compunds but with _favouring_ the exact match.

**Comment by dr0i** [comment]
Now, while with the changes in the queries are somewhat better (e.g. http://lobid.org/subject?name=verkehr ) , they are not perfect (e.g. http://lobid.org/subject?name=stadt).
Seems the only safe way do do it is to have multiple fields as suggested in https://stackoverflow.com/questions/23686577/favor-exact-matches-over-ngram-matches-in-elasticsearch-when-mapping .

**Comment by dr0i** [comment]
Question is: should be merge this slightly, if ever,  improvement?

**Comment by acka47** [comment]
Multiple fields/indices are the way to go I think. I'd suggest two different query options over the same field. We will have to add a parameter, then.
The auto-suggest use case shouldn't be that central especially as we have seen that it isn't used, anyway.

**Comment by acka47** [comment]
Fixed in lobid-gnd, see http://lobid.org/gnd/search?q=verkehr. Closing.
