### ISSUE TITLE
Improve relevance ranking for title search

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#140]
Matches in alternative title seem to be prefered over main title, see e.g. http://lobid.org/resource?name=Kunst: More than the first 50 entries have `alternativeTitle` "Kunst" but no occurance of "Kunst" in the `title` field (if one exists at all). 

We should boost the `title` over `alternativeTitle` over `otherTitleInformation` (these being the three fields covered by a `?name` query, see https://github.com/hbz/lobid/blob/master/app/models/queries/LobidResources.java#L67-L81.)

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/resource?name=Kunst&format=full

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See http://lobid.org/resource?name=Kunst&format=full
