### ISSUE TITLE
Item URIs can't be dereferenced

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#141]
See e.g. http://lobid.org/item/HT014345141:DE-361:OL830%20N489 or http://lobid.org/item/HT000346014:DE-465:ICC180

**Comment by dr0i** [comment]
Deployed to staging and to production (although travis failed , but that's because of a dependency download problem and we can't wait when this is fixed. )

**Comment by dr0i** [comment]
@ahagenbruch was affected by this bug, I think.

**Comment by dr0i** [comment]
Now, the build is sucessful even on travis. Merged and closing this ticket.
