### ISSUE TITLE
Missing types

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#143]
Some types  cannot be retrieved when using the api `type`parameter, e.g.:
http://lobid.org/resource?q=*&type=http://purl.org/lobid/lv#Schoolbook
This seems to be true for all the lobid vocabulary defined types.

**Comment by fsteeg** [comment]
Your sample does not encode the `#` as `%23`, with that it works fine for me:
http://lobid.org/resource?q=*&type=http://purl.org/lobid/lv%23Schoolbook

**Comment by dr0i** [comment]
That's it! Thx :)
