### ISSUE TITLE
PreferredNameForTheWork occurs at entities where it shouldn't and aren't in sync with PreferredName

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#144]
Subticket to #139.

Example http://test.lobid.org/resource?id=HT018312899&format=full:

```
{"@graph": [
    {
      "@id": "http://d-nb.info/gnd/1023391147",
      "preferredName": "Maes, Sientje",
      "preferredNameForThePerson": "Maes, Sientje"
    },
    {
      "@id": "http://d-nb.info/gnd/4049716-1",
      "preferredName": "Rezeption",
      "preferredNameForTheSubjectHeading": "Rezeption",
      "preferredNameForTheWork": "<<Der>> Cid"
    },
    {
      "@id": "http://d-nb.info/gnd/4124796-6",
      "preferredName": "Dramaturgie",
      "preferredNameForTheSubjectHeading": "Dramaturgie",
      "preferredNameForTheWork": "<<Der>> Cid"
    },
    {
      "@id": "http://d-nb.info/gnd/7683386-0",
      "preferredName": "Grabbe, Christian Dietrich: Der Cid",
      "preferredNameForTheWork": "<<Der>> Cid"
    }
  ]}
```

Two problems:
- `"preferredNameForTheWork": "<<Der>> Cid"` occurs at GND entities where it shouldn't.
- for http://d-nb.info/gnd/7683386-0, `preferredName` and `preferredNameForTheWork` are not identical as they should be.

**Comment by dr0i** [comment]
Still a problem with work title - shouldn't have `preferredNameForThePerson`:
 
    {"@id": "http://d-nb.info/gnd/7683386-0",
    "preferredName": "Grabbe, Christian Dietrich: Der Cid",
    "preferredNameForThePerson": "Grabbe, Christian Dietrich: Der Cid",
    "preferredNameForTheWork": "Grabbe, Christian Dietrich: Der Cid"},

**Comment by dr0i** [comment]
This issue seems to be resolved. @acka47 please have a look, too.

**Comment by acka47** [comment]
+1. Closing.

**Comment by dr0i** [comment]
The problem reported in https://github.com/hbz/lobid/issues/144#issuecomment-105980315 is still/again a problem. Reopening ticket.

**Comment by dr0i** [comment]
Uh, there is a ticket for this issue (hbz/lobid#267) so this one can stay closed.
