### ISSUE TITLE
Problems with GND entities with complex names

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#145]
Sub-issue of #139 .

Example http://test.lobid.org/resource/HT014215912/about, snippet:

```
{
    "@id" : "http://d-nb.info/gnd/118560034",
    "preferredName" : [ "Heiliges Römisches Reich, Kaiser", "Karl" ]
  }
```
[Source](http://lobid.org/resource?id=HT014215912&format=source):

```
<datafield tag="902" ind1="-" ind2="1">
    <subfield code="p">Karl</subfield>
    <subfield code="n">I.</subfield>
    <subfield code="c">Heiliges Römisches Reich, Kaiser</subfield>
    <subfield code="d">747-814</subfield>
    <subfield code="9">(DE-588)118560034</subfield>
</datafield>
```

[In the Aleph catalogue](http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DBT000007970), these are simply concatenated with seperating commas:
`Karl, I., Heiliges Römisches Reich, Kaiser, 747-814 [(DE-588)118560034]`. We could do it the same but should leave out the trailing GND ID.

**Comment by acka47** [comment]
See also http://lobid.org/resource/HT015455455, snippet
```
{
    "@id" : "http://d-nb.info/gnd/4443675-0",
    "preferredName" : "Marke",
    "preferredNameForTheSubjectHeading" : "Daimler"
  }, {
    "@id" : "http://d-nb.info/gnd/4576855-9",
    "preferredName" : "Marke",
    "preferredNameForTheSubjectHeading" : "Steyr"
  }
```
[Source](http://lobid.org/resource?id=HT015455455&format=source):
```xml
<datafield tag="912" ind1="-" ind2="1">
    <subfield code="s">Daimler</subfield>
    <subfield code="h">Marke</subfield>
    <subfield code="9">(DE-588)4443675-0</subfield>
</datafield>
<datafield tag="917" ind1="-" ind2="1">
    <subfield code="s">Steyr</subfield>
    <subfield code="h">Marke</subfield>
    <subfield code="9">(DE-588)4576855-9</subfield>
</datafield>
```

**Comment by acka47** [comment]
Another one. Compare http://lobid.org/resource/TT001136847/about (godd) with http://test.lobid.org/resource/TT001136847/about (notm good, because array of preferred names.

**Comment by dr0i** [comment]
Deployed to staging, please test.

**Comment by acka47** [comment]
Looks better, but there are more things to do regarding all three examples I delivered above.

**Example 1**: http://test.lobid.org/resource/HT014215912/about, snippet
```javascript
{
  "@graph": [
    {
      "@id": "http://d-nb.info/gnd/118560034",
      "preferredName": "Karl , I. , Heiliges Römisches Reich, Kaiser , 747-814"
    },
    {
    "subjectChain": [
        "Karl | Heiliges Römisches Reich, Kaiser | Herrscherbild | Geschichte",
        "Karl | Heiliges Römisches Reich, Kaiser | Herrscherbild | Geschichte (213)" ]
      }
  ] 
}
``` 
- `"preferredNameForThePerson": "Karl , I. , Heiliges Römisches Reich, Kaiser , 747-814"` is missing
- The subject chain should read: `"subjectChain" : [ "Karl, Heiliges Römisches Reich, Kaiser | Herrscherbild | Geschichte (213)" ]` pulling together "Karl" and "Heiliges Römisches Reich, Kaiser" and leaving out the redundant chain.

**Example 2**: http://test.lobid.org/resource/HT015455455, snippet:
```javascript
{
  "@graph": [
    {
      "@id": "http://d-nb.info/gnd/4443675-0",
      "preferredName": "Daimler , Marke",
      "preferredNameForTheSubjectHeading": "Daimler"
    },
    {
      "@id": "http://d-nb.info/gnd/4576855-9",
      "preferredName": "Steyr , Marke",
      "preferredNameForTheSubjectHeading": "Steyr"
    },
    {"subjectChain": [
        "Austro-Daimler-Puchwerke | Automobilsport | Steyr-Daimler-Puch AG | Geschichte (2134,3214)",
        "Steyr | Marke | Kraftfahrzeug | Geschichte 1920-1945 | Verzeichnis",
        "Daimler | Kraftfahrzeug | Geschichte 1918-1940 | Verzeichnis (2134)",
        "Austro-Daimler-Puchwerke | Porsche, Ferdinand | Steyr-Daimler-Puch AG | Geschichte",
        "Austro-Daimler-Puchwerke | Automobilsport | Steyr-Daimler-Puch AG | Geschichte",
        "Daimler | Marke | Kraftfahrzeug | Geschichte 1918-1940 | Verzeichnis",
        "Austro-Daimler-Puchwerke | Porsche, Ferdinand | Steyr-Daimler-Puch AG | Geschichte (2134,3214)",
        "Steyr | Kraftfahrzeug | Geschichte 1920-1945 | Verzeichnis (2134)" ]
      }
  ]
}
```
- `preferredName` and `preferredNameForTheSubjectHeading` must be identical ("Daimler, Marke" and "Steyr, Marke").
- Instead of eight, there should be 4 subject chains:
```
"subjectChain": [
        "Austro-Daimler-Puchwerke | Automobilsport | Steyr-Daimler-Puch AG | Geschichte (2134,3214)",
        "Steyr, Marke | Kraftfahrzeug | Geschichte 1920-1945 | Verzeichnis (2134)",
        "Daimler, Marke | Kraftfahrzeug | Geschichte 1918-1940 | Verzeichnis (2134)",
        "Austro-Daimler-Puchwerke | Porsche, Ferdinand | Steyr-Daimler-Puch AG | Geschichte (2134,3214)"
```
:exclamation: Note that "Steyr" and "Marke are seperated by a pipe though they should be seperated ba a comma and that the "Marke" is currently missing with "Daimler".

**Example 3**: http://test.lobid.org/resource/TT001136847/about, snippet:
```
{
   "@graph": [
    {
      "@id": "http://d-nb.info/gnd/121600335",
      "preferredName": "Kleiser , Familie, Nordrhein-Westfalen"
    },
    {
      "subjectChain": "Kleiser | Familie, Nordrhein-Westfalen | Geschichte"
    }
  ]
}
```
- `preferredNameForTheFamily` is missing
- `subjectChain` should look like this: ` "Kleiser, Familie, Nordrhein-Westfalen | Geschichte"`

**Comment by dr0i** [comment]
I beg for not mixing new issues into exiting ones (e.g. http://lobid.org/resource/HT014215912 also has two subject chains and also hasn't comma separated entries ("Karl, Heiliges Römisches Reich, Kaiser | Herrscherbild |...").
These issues have been there at least since 17 April (see https://github.com/lobid/lodmill/blob/master/lodmill-rd/src/test/resources/hbz01.nt ).
Also, this ticket consists in fact of many tickets. It's better to make one issue for an task. As it is, the complexity is big and this slows down resolving considerably .

I think it is really important to separate issues, not at last to be able to priorize them as high or as "can be resolved someday". Otherwise, we are far away from "rapid","agile","responsive".

**Comment by dr0i** [comment]
Extracted four ticktes out of this one (#145, #146,#147,#148).

**Comment by dr0i** [comment]
@acka47 please confirm if this issues is resolved at the staging system.

**Comment by acka47** [comment]
Resolved on staging and production. Closing.
