### ISSUE TITLE
subjectChain: pulling element entries together

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#148]
http://test.lobid.org/resource/HT014215912/about, snippet
```javascript
{
  "@graph": [
    {
      "@id": "http://d-nb.info/gnd/118560034",
      "preferredName": "Karl , I. , Heiliges Römisches Reich, Kaiser , 747-814"
    },
    {
    "subjectChain": [
        "Karl | Heiliges Römisches Reich, Kaiser | Herrscherbild | Geschichte",
        "Karl | Heiliges Römisches Reich, Kaiser | Herrscherbild | Geschichte (213)" ]
      }
  ] 
}
``` 

 The subject chain should read: `"subjectChain" : [ "Karl, Heiliges Römisches Reich, Kaiser | Herrscherbild | Geschichte (213)" ]` pulling together "Karl" and "Heiliges Römisches Reich, Kaiser"

**Comment by acka47** [comment]
Another example is http://lobid.org/resource/HT018312899:

Currently it reads:
`"subjectChain" : "Grabbe, Christian Dietrich | <<Der>> Cid | Dramaturgie | Rezeption (231,321)"`

Desired outcome:
`"subjectChain" : "Grabbe, Christian Dietrich: Der Cid | Dramaturgie | Rezeption (231,321)"`

(see also https://github.com/hbz/nwbib/issues/104)

**Comment by acka47** [comment]
We don't need to do this as the problem won't exist anymore after implementing API 2.0. Thus, closing.
