### ISSUE TITLE
Some gnd contributors missing

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#150]
In the dnb mab mapping docu only indicator {balnk,b,c,e,f} are mentioned. In the actual data we also have {a}, so these were missing.
See e.g. http://lobid.org/resource/TT001230001 and http://lobid.org/resource/HT015414894 .

**Comment by dr0i** [comment]
@acka47 mentioned: 

    Here is an example where GND labels for one author (http://d-nb.info/gnd/1050282418,
     "Heckmann,  Helmut") were left out: http://test.lobid.org/resource/HT018506077/about 

    Another one: http://test.lobid.org/resource/HT018504052/about

And

    I have the feeling that in records where there are two or more authors the label is
    only added for one  author. Another example: http://test.lobid.org/resource/BT000158168/about

    With three contributors it seems to work, though, see e.g.
     http://test.lobid.org/resource/HT010086112/about.

**Comment by dr0i** [comment]
Deployed to staging and production.

**Comment by acka47** [comment]
Looks good. Closing.
