### ISSUE TITLE
Redundant preferredNames as array 

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#153]
Examples in this result list: http://lobid.org/nwbib/search?person=Konrad+Adenauer&from=20&sort=

E.g. http://lobid.org/resource/HT015891797/about & http://lobid.org/resource/HT014319164/about

Note :exclamation: This problem occurs when a person is both contributor and subject.

**Comment by acka47** [comment]
Another example: http://lobid.org/nwbib/HT018567032

**Comment by dr0i** [comment]
Test-set deployed to staging.

**Comment by acka47** [comment]
Looks good. Please leave out one white space before the comma. [Example](http://test.lobid.org/resource/HT015891797/about) snippet:

`"preferredName" : "Adenauer, Konrad , 1876-1967"`

**Comment by acka47** [comment]
In the [other example](http://test.lobid.org/resource/HT014319164/about), not only there also is the white space before the comma but also the name array with the `preferedNameForThePerson` property:
`"preferredNameForThePerson" : [ "Reinarz, Titus", "Reinarz, Titus , 1948-" ]`

**Comment by dr0i** [comment]
Re: `preferedNameForThePerson`
I just treated `preferedName` as this is the property which is shown , both in lobid RDFa and NWBib.

**Comment by acka47** [comment]
> I just treated `preferedName` as this is the property which is shown , both in lobid RDFa and NWBib.

You did? It is quite strange that in http://test.lobid.org/resource/HT015891797/about both `preferedName` and `preferedNameForThePerson` are ok.

**Comment by dr0i** [comment]
Not strange - in HT015891797 `preferedNameForThePerson` was not an array in the first place (look at http://lobid.org/resource/HT015891797/about ).
Anyway, I'll have a look at it now

**Comment by dr0i** [comment]
TODO: get rid of  `preferredNamesForThePerson`property in subjects, see http://test.lobid.org/resource/HT018312899/about ("Grabbe, Christian Dietrich: Der Cid").

**Comment by dr0i** [comment]
Test-set deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Merged into master . Needs a complete reindexing to be deployed to production, though.

**Comment by dr0i** [comment]
Deployed to production (mind that the first two examples in this issue are still cached with the old values. Wait one hour.)
