### ISSUE TITLE
Problem with persons without GND iD

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#154]
See e.g http://lobid.org/resource/HT018617137 and presentation in NWBib at http://lobid.org/nwbib/HT018617137.

JSON:
```javascript
{
  "@graph": [{
      "contributorLabel": "Helm, Eva Maria",
      "statementOfResponsibility": "[Text: Eva Maria Helm]",
    }]
}
```

[Source](http://lobid.org/resource?id=HT018617137&format=source):

```xml
<datafield tag="100" ind1="-" ind2="1">
    <subfield code="a">Helm, Eva Maria</subfield>
<datafield tag="359" ind1="-" ind2="1">
    <subfield code="a">[Text: Eva Maria Helm]</subfield>
</datafield>
```

In NWBib, we need the content from 100 in a `Autor/in` field. I don' think we can implement this with the current data. What would be the best way to go?

**Comment by acka47** [comment]
As @jschnasse and me agreed on in https://github.com/hbz/lobid/issues/233#issuecomment-139227458 and the comment thereafter, we will add names of authors without GND ID with dc elemens properties `dc:creator` and `dc:contributor`.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
Looks good re. this example for field 100 blank and `dc:creator`. Doesn't work for the example from the duplicate (maybe it wasn't a duplicate after all?)  issue #233 with field 108 b that should be mapped to `dc:contributor`:

Snippet from source of http://lobid.org/resource/HT018700720/about:

```xml
<datafield ind2="1" ind1="b" tag="108">
  <subfield code="p">Ottovay, Kathrin</subfield>
</datafield>
```

Expected outcome (snippet):

```javascript
 {
    "@id" : "http://lobid.org/resource/HT018700720",
    "contributor" : [ "http://d-nb.info/gnd/129961604", "http://d-nb.info/gnd/136371671", "http://d-nb.info/gnd/2006655-7", "http://d-nb.info/gnd/115325859" ],
   "contributorName": "Ottovay, Kathrin"
```

We also have to add the line `"contributorName": "http://purl.org/dc/elements/1.1/contributor"` to the JSON-LD context at http://lobid.org/context/lobid-resources.json.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
