### ISSUE TITLE
"Collections" only transformed to RDF in part

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#155]
Example (haven't found another one yet): http://lobid.org/resource/HT003774860/about

JSON-LD (complete):
```javascript
{
  "primaryTopic": "http://lobid.org/resource/HT003774860",
  "@graph": [{
      "@id": "http://lobid.org/resource/HT003774860",
      "hasPart": "http://lobid.org/resource/HT004823688",
      "@type": "http://purl.org/ontology/bibo/Collection"
    }],
  "@id": "http://lobid.org/resource/HT003774860/about",
  "@context": "http://api.lobid.org/context/lobid-resources.json"
}
```

This should be typed as `bibo:Series` as element 0 in field 052 is "r". [Source](http://lobid.org/resource?id=HT003774860&format=source) (snippet):

```xml
<controlfield tag="050">a|||||||||||||</controlfield>
<controlfield tag="052">r||||||||||||||</controlfield>
```

Maybe this has something to do with missing values in 050 and 052. I could imagine that this is catalogued incorrectly. Will investigate.

**Comment by acka47** [comment]
I found another one: http://lobid.org/nwbib/HT014918230.

JSON-LD (complete):
```javascript
{
  "primaryTopic": "http://lobid.org/resource/HT014918230",
  "@graph": [{
      "@id": "http://lobid.org/resource/HT014918230",
      "hasPart": "http://lobid.org/resource/HT014918244",
      "@type": "http://purl.org/ontology/bibo/Collection"
    }],
  "@id": "http://lobid.org/resource/HT014918230/about",
  "@context": "http://api.lobid.org/context/lobid-resources.json"
}
```

Source (snippet):
```xml
<controlfield tag="050">a|a|||||||||||</controlfield>
<controlfield tag="051">n|||z|||</controlfield>
```
- The data in 050 just means "not specified".
- The data in 051 means "mehrbaendiges begrenztes Werk - nicht Teil eines Gesamtwerks" (for "n" in element 0), "sonstige Veroeffentlichungsart/-inhalt" (for "z" in element 3)
- No data in 052.

**Comment by jschnasse** [comment]
I do not understand the background, but like to mention that I just found another problematic resource http://lobid.org/resource/HT017379873/about. @acka47 ask me to comment here.

**Comment by jschnasse** [comment]
Just to make that clear, the resource is not only typed wrong there is also data missing. Compare http://okeanos-www.hbz-nrw.de/F/?func=find-c&ccl_term=IDN%3DHT017379873

**Comment by acka47** [comment]
Taking a look at http://lobid.org/resource/HT017379873. JSON looks quite similar to the other ones:

```javascript
{
  "primaryTopic" : "http://lobid.org/resource/HT017379873",
  "@graph" : [ {
    "@id" : "http://lobid.org/resource/HT017379873",
    "hasPart" : "http://lobid.org/resource/HT017615629",
    "@type" : "http://purl.org/ontology/bibo/Collection"
  } ],
  "@id" : "http://lobid.org/resource/HT017379873/about",
  "@context" : "http://api.lobid.org/context/lobid-resources.json"
}
```

Source:
```xml
<controlfield tag="050">a|a|||||||||||</controlfield>
<controlfield tag="052">pst||||zz||||||</controlfield>
```

- Field 050: "not specified"
- Field 052 is catalogued incorrectly :exclamation: 
   - There only should be one letter in element 0 instead of three (`pst` from which only the `p` is documented in the [MAB doc](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mab2FormatSatzkennungSegment000Nov2001.txt?__blob=pu blicationFile))
   - `zz` in element 4 of field 052 isn't documented at all

**Comment by acka47** [comment]
Here is a resource from the test set that isn't correct: http://lobid.org/resource/HT001373475

**Comment by acka47** [comment]
Here is a resource in the test set where it doesn't work: http://lobid.org/resource/HT002619538

**Comment by dr0i** [comment]
Since #139 the 1 billion triples are no more collected and sorted (using hadoop) and then transformed into their Json-LD record. Now, if at some point of the transformation a record is identified a Json-LD is generated, resulting in some Json-LD records having the same ID (e.g. when generating the reziprok data of the cataloged `isPartOf` into `<isPartOfUri> <hasPart> <hasPartUri>`), resulting in having two (or more) records with the same ID (but consisting of different data).  The idea is to *merge* these Json records *within elasticsearch*. There is an [doc_as_upsert](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#_literal_doc_as_upsert_literal) in the API but it doesn't work the way I thought it would, obviously.  Rather than merging the data is overwritten.

**Comment by dr0i** [comment]
The workaround is to not create the reziprok data thus having no conflicting records.

**Comment by dr0i** [comment]
Deployed to staging and production. Please have a look, also @jschnasse .

**Comment by acka47** [comment]
+1.

**Comment by dr0i** [comment]
@jschnasse  vocally  +1ed. Thus closing.
