### ISSUE TITLE
Missing preferredNames for some GND entities

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#156]
Example resources: http://lobid.org/resource/HT017171312/about, http://lobid.org/resource/HT017022683/about, http://lobid.org/resource/BT000012724/about, http://lobid.org/resource/HT016853119/about, http://lobid.org/resource/HT004488383/about

At all examples I could find, the problem occura with non-person GND entries (corporate bodies, events) that have a hyphenated GND ID.

**Comment by dr0i** [comment]
@acka47 Have a look , seems to be resolved with #139 .

**Comment by acka47** [comment]
Is indeed resolved. Closing
