### ISSUE TITLE
Remove redundancy: dct:creator is always also dct:contributor

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#158]
Example: http://lobid.org/resource/HT013208865/about

Snippet:

```javascript
{
"@id" : "http://lobid.org/resource/HT013208865",
 "contributor" : "http://d-nb.info/gnd/110109198",
 "creator" : "http://d-nb.info/gnd/110109198"
}
```

**Comment by jschnasse** [comment]
Any progress on this? +1 from me for getting this solved asap.

**Comment by dr0i** [comment]
Deployed to staging, please have a look at e.g. http://test.lobid.org/resource/HT013208865/about .

**Comment by dr0i** [comment]
@fsteeg will this have an impact on nwbib?

**Comment by acka47** [comment]
+1 from me

**Comment by jschnasse** [comment]
+1

**Comment by fsteeg** [comment]
Shouldn't be an issue in NWBib, and looks good: http://test.lobid.org/nwbib/HT013208865

**Comment by dr0i** [comment]
Deployed to production, closing.

**Comment by dr0i** [comment]
There are some unresolved issues, see hbz/nwbib#133. Reopening.

**Comment by acka47** [comment]
In  https://github.com/lobid/lodmill/pull/714#issue-104474778 @dr0i wites:

> treat field 800 on its own
 In the docs it's said about the 8* field:
"Segment Nichtstandardmaessige Nebeneintragungen (NE)"
(engl. roughly "Segment of non-standard side entries").
So we sadly can't treat these fields like the 1* fields.
As nobody knows for sure (aka "non-standard") what the entries mean
it can be said:
-- if subfield "b" exists it must be a contributor because it has a special
 role (specified via this non-controlled field "b").
-- otherwise we ignore id because it cannot be said for sure what it meant
 (creator?)
-- in any case the name of the prson is added to "contributorLabel"

I see a problem with having some names in `contributorLabel` (which is only used for search) without having the person in the data for presentation. This may lead to people finding resources with a person search where the person isn't mentioned in the actual shown record. I don't know how many resources this affects. Would be interesting. An easy solution would be to leave out person from 800 without subfiled `b` altogether.

**Comment by dr0i** [comment]
The [Last commit](https://github.com/lobid/lodmill/commit/da53474ab10155b304748202e240f81743ef123e) takes care to not emit a `contributorLabel` when 800b is missing. I couldn't find a real world example so I constructed one, see the commit.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
