### ISSUE TITLE
Adjust transformation rules to RDA changes

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#161]
From **1 October 2015** people will be cataloging in hbz union catalog according to the RDA rules as documented [here](https://wiki1.hbz-nrw.de/x/LwBoB). We will have to adjust the transformation, i.e. the [hbz01-to-lobid morph file](https://github.com/lobid/lodmill/blob/master/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml) accordingly.

After a first cursory look at the documents, I suggest the following approach:

**Identifying RDA records**
RDA is only implemented to newly catalogued resources which get an RDA marker `r` in field 030, indicator=blank,position 4 of the Aleph sequentials (aseq), see the [documentation](https://wiki1.hbz-nrw.de/x/TIAcB). Thus, we will have to add the RDA transformation rules only for these records.

**Checking fields that will be omitted**
Several fields won't be used anymore with RDA cataloging. You can see the list [here](https://wiki1.hbz-nrw.de/pages/viewpage.action?pageId=68976716#07-50-010-Indexierungskonzeptf%C3%BCrneue%2Cge%C3%A4nderteFelderaufgrundRDA-Felder%2Cdief%C3%BCrnachRDAkatalogisierteAufnahmennichtmehrverwendetwerden%2CStand%3A06.05.2015). We will check whether and how we currently transform these to RDF.

**Find out how to transform the new data to lobid'scurrent RDF data model**
 After having identified the data fields where RDA means change we will have to find find out how we integrate the new RDA data into the the current lobid RDF.

**Discuss how to handle breaks in the cataloging practice**
While we be able to make a seemless transformation for some of RDA cataloging so that lobid customers won't even notice that things have changed, this may not be possible for all of the changes. E.g., regarding IMD (Inhaltstyp, Medientyp, Datenträgertype)/CMC (content type, media type, carrier type) we will get better and more coherent information (see [here](https://www.hbz-nrw.de/dokumentencenter/produkte/verbunddatenbank/aktuell/vortraege/i18nfolder.2015-03-31.0604209831/TOP_3_4_RDA_CMC.20150319.pdf) for details). 

On cases where cataloging practice significantly breaks, we will have to look, whether we will both try to map the data to the old/currrent data model _and_ map the data according to RDA.

**Comment by acka47** [comment]
Here is a list of  RDA record in lobid courtesy of @donboern: [rda-ids.txt](https://github.com/hbz/lobid/files/18519/rda-ids.txt)

**Comment by acka47** [comment]
Most of the reosurces listed in [rda-ids.txt](https://github.com/hbz/lobid/files/18519/rda-ids.txt) seem to be periodicals. Here is a print book: http://lobid.org/resource/HT018779822

**Comment by acka47** [comment]
What seems important to me for the start is field 419 with the pbulisher, publication place/date information. 

Snippet from http://lobid.org/resource/HT018779822:

```xml
<datafield ind2="1" ind1="-" tag="419">
            <subfield code="a">New York</subfield>
            <subfield code="b">Routledge</subfield>
            <subfield code="c">2014</subfield>
</datafield>
```

Snippet from http://lobid.org/resource/HT018772912:
```xml
          <datafield ind2="1" ind1="-" tag="419">
            <subfield code="a">Sundern</subfield>
            <subfield code="b">Baulmann Leuchten GmbH</subfield>
            <subfield code="c">2011-</subfield>
            <subfield code="A">3</subfield>
          </datafield>
```

**Comment by dr0i** [comment]
>  Thus, we will have to add the RDA transformation rules only for these records.
Does this mean that fields are ambiguous (i.e. e.g. `419-1c` is the publication date if it's RDA catalogued but something different when it's old MAB2? (In this case I can [see](https://github.com/lobid/lodmill/wiki/RDF-transformation-statistics-of-aleph-mab-xml-fields-of-the-fulldump) that that's not the case)).
_If_ there is no interference it's much simpler to configure the transformation rules, that's why I ask.

**Comment by acka47** [comment]
@droi Could you please get the Aleph XML source of all files in rda-ids.txt](https://github.com/hbz/lobid/files/18519/rda-ids.txt) and put them in one file so that I can search for specific fields?

**Comment by dr0i** [comment]
`for i in $(cat rda-ids.txt); do xmllint --format  "$i?format=source" >>  rda-ids.alephMabXmlPretty.xml; done`
You find that at http://lobid.org/download/rda-ids.alephMabXmlPretty.xml .

**Comment by acka47** [comment]
Speaking to publisso stakeholders, they want to work with roles of persons/corporations from RDA. We will have to consider these in the transformation. Note to self: Take a look at this and open a separate issue.

**Comment by dr0i** [comment]
Updated rda-ids.alephMabXmlPretty.xml . Took as base DE-605-aleph-baseline-marcxchange-2016011515.tar.gz which reveals 16k resources as RDA. Hope this suffices.

**Comment by acka47** [comment]
@dr0i Could you please update rda-ids.alephMabXmlPretty.xml once more?

**Comment by dr0i** [comment]
http://lobid.org/download/rda-ids.alephMabXmlPretty.xml.bz2

**Comment by acka47** [comment]
Thanks. Unwieldy as the file gets, I won't ask again for creating it. Now thinking about how to work with a 1,5GB xml file...

**Comment by dr0i** [comment]
Depending on what you want, you can always use the friendly stream tools like `less`, `grep`, `sed` etc.

**Comment by acka47** [comment]
There seems to be a problem with the rda-ids.alephMabXmlPretty.xml. When I do for example `cat rda-ids.alephMabXmlPretty.xml | xmllint --format - | grep --color  -A 4 "<datafield tag=\"064\" ind1=\".\" ind2=\".\">"` I get:

```
-:103: parser error : XML declaration allowed only at the start of the document
<?xml version="1.0" encoding="UTF-8"?>
     ^
-:104: parser error : Extra content at the end of the document
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.o
```

**Comment by ChristophEwertowski** [comment]
As a finger execise I looked at the [morph-hbz01-to-lobid.xml](https://github.com/lobid/lodmill/blob/master/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml) to check fields which are now omitted, how they are transformed and to document it here.

Number MAB2 | Field name | if & how transformed
---------- | -------------- | ------------------------
300 | Sammlungsvermerk | -
304 | Einheitssachtitel
310 | Hauptsachtitel in Ansetzungsform
333 | zu ergänzende Urheber zum Hauptsachtitel
334 | Allgemeine Materialbenennung
340, 344, 348, 352 | Parallelsachtitel in Ansetzungsform | - 
342, 346, 350, 354 | zu ergänzende Urheber zum Parallelsachtitel | -
361 | Beigefügte Werke | -
410, 411, 412, 415, 416, 417, 418 | Alter Erscheinungsvermerk | -
454, 464, 474, 484, 494 | Gesamttitel in Ansetzungsform – wird auf Verbundebene entschieden! | -
502 | Einheitssachtitel eines beigefügten oder kommentierten Werkes | - 
504 | Angabe von Paralleltiteln | 
517 | Angaben zum Inhalt  | -
519 | Alter Hochschulschriftenvermerk 
532 | Hinweise auf frühere und spätere sowie zeitweise gültige Titel | -
610 – 645 | Segment Sekundärformen
652 | Spezifische Materialbenennung und Dateityp 
653 | Physische Beschreibung der Computerdatei auf Datenträger | -
8XX | Segment Nichtstandardmäßige Nebeneintragungen 
9XX | Bei RSWK-Schlagwörtern erstes Unterfeld $f
Work in progress.

**Comment by acka47** [comment]
Closing this super-issue as the two remaining sub-issues are sufficient for future orientation (and don't need to be implemented for the launch).
