### ISSUE TITLE
Get dumps using a time frame like in OAI-PMH

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#162]
It should be possible to get only data that changed since a given date. At the moment, if someone wants to get data set, she has to get the whole set , day by day all over again. This is not performant and comes with a ridicoulus overhead on both sides, server and consumer.

The idea is to create an extra triple which would be about the about-URI of the resource stating _when_ the metadata was created. Then we can take this field into account when querying the data.

@acka47 what property can we use for this?

**Comment by acka47** [comment]
As I understand this, the information we want to add is in MAB fields `002` and `003`. From the [MAB documentation](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mab2FormatSatzkennungSegment000Nov2001.txt?__blob=publicationFile):

```
002       DATUM DER ERSTERFASSUNG / FREMDDATENUEBERNAHME

          Indikator:
          a = Datum der Ersterfassung
          b = Datum der Fremddatenuebernahme


003       DATUM DER LETZTEN KORREKTUR

          Indikator:
          Blank = nicht definiert
```

In an [example file](http://lobid.org/resource?id=HT002948556&format=source) it looks like this:

```xml
<datafield tag="002" ind1="a" ind2="1">
   <subfield code="a">19931219</subfield>
</datafield>
<datafield tag="003" ind1="-" ind2="1">
   <subfield code="a">20080520</subfield>
</datafield>
```

# To Do

The JSON-LD should include this after adding the needed information:

```javascript
  "@id" : "http://lobid.org/resource/HT002948556/about",
  "primaryTopic" : "http://lobid.org/resource/HT002948556",
  "dateCreated" : "1993-12-19",
  "dateModified" : "2008-05-20"
}
```

The JSON-LD context should be extended like this:

```javascript
"dateCreated" : "http://purl.org/dc/terms/created",
"dateModified" : "http://purl.org/dc/terms/modified"
```

**Comment by dr0i** [comment]
Deployed to staging using small test set.
Try e.g. `curl -L --header "Accept: application/ld+json" "http://test.lobid.org/resource?set=nwbib&scroll=20050401"`.

**Comment by dr0i** [comment]
Deployed to staging and production. Closing.
