### ISSUE TITLE
Author search reveals unexpected results

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#163]
Reported by Werner Gresshoff.
E.g. http://lobid.org/resource?author=134530306 reveals false hits.

**Comment by dr0i** [comment]
Deployed to staging.
http://lobid.org/resource?author=134530306 wil not show anything because there is nothing there, I think. There _is_ one resource where the person is mentioned , but only as literal: http://lobid.org/resource?author=Stephan,%20Steffi see http://d-nb.info/gnd/134530306.
The query mentioned in hbz/nwbib#102 works but results in only _1_ hit , not _2_ (which seems to indicate that the scripts creating the beacon is not correct):  http://lobid.org/nwbib/search?person=100120318 

http://lobid.org/nwbib/search?person=100120318

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
