### ISSUE TITLE
All ZDB resources wrongly typed as bibo:Periodicals

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#164]
Stumbled over this while investigating #155. When I read the [morph](https://github.com/lobid/lodmill/blob/master/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L499-501) correctly, all resources with a ZDB ID are typed as `bibo:Periodical`. This isn't right as there are also series in ZDB -– which are mostly _not_ periodicals.

Examples: 
- http://lobid.org/resource/HT012350250/about
- http://lobid.org/resource/HT012303883/about
- http://lobid.org/resource/HT014526294/about
- http://lobid.org/resource/HT011192847/about

**Comment by acka47** [comment]
I doesn't seem useful for me to add the Periodical type – especially if it is incorrect. As we don't use `bibo:Periodical` for facetting in NWBib, I suggest removing it completely. The same goes for `bibo:Collection` in the context of ZDB resources.

**Comment by acka47** [comment]
I am working on this and will remove both types `bibo:Periodical` and `bibo:Collection`. 

@literarymachine Felix, @jschnasse told me that he is generally inf avor of cleaning up the typing oin lobid and that you it whouldn't break edoweb. Nonetheless, I am mentioning you so that you know what is going on.

After removing the types `Periodical` and `Collection` you will only have the different types `bibo:Series` and `bibo:Journal`. (Some of these will be also typed as `lv:Miscellaneous`. We will deal with this in another issue, see https://github.com/lobid/lodmill/issues/676.)

**Comment by dr0i** [comment]
Deployed to test. And production.
