### ISSUE TITLE
Thesis - Abschlussarbeit - Dissertation - MasterThesis

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#166]
This is a question regarding types in lobid. 

Example:
http://lobid.org/resource/HT017480009/about 

This resource has been marked as beeing of type

http://purl.org/vocab/frbr/core#Manifestation
http://purl.org/dc/terms/BibliographicResource
http://purl.org/ontology/bibo/Thesis
http://purl.org/ontology/bibo/Book 

Questions:
1. Is there a way to decide that this is a doctoral thesis and not a bachelor or master?
2. How is the relationship - if there is any - between bibo:Book and bibo:Thesis in lobid?

**Comment by acka47** [comment]
> 1. Is there a way to decide that this is a doctoral thesis and not a bachelor or master

I don't think so. We get this from MAB 051 (code u) and 052 (code `sc`), see [lines 417 to 423 in the morph](https://github.com/lobid/lodmill/blob/master/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L417-L423). From the [MAB documentation](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mab2FormatSatzkennungSegment000Nov2001.txt?__blob=publicationFile):

```
051     VEROEFFENTLICHUNGSSPEZIFISCHE ANGABEN ZU BEGRENZTEN
        WERKEN
                u = Universitaetsschrift


052       VEROEFFENTLICHUNGSSPEZIFISCHE ANGABEN ZU FORTLAUFENDEN
          SAMMELWERKEN

               sc = Schul- / Universitaetsschrift
```
The good thing is: I am quite sure that only doctorl thesises get catalogued so all of them should be of this type. Looking at ten examples, they all have information on this in field 519, e.g. http://lobid.org/resource?id=HT018239864&format=source:

```xml
<datafield tag="519" ind1="-" ind2="1">
<subfield code="p">Zugl.</subfield>
<subfield code="a">Göttingen, Univ., Diss., 2013</subfield>
</datafield>
```

Or do you know of any bachelor and/or master thesis in the catalog, @jschnasse?

> 2. How is the relationship - if there is any - between bibo:Book and bibo:Thesis in lobid?

Both types are added separately and without any relation to the other.

**Comment by jschnasse** [comment]
What about habilitation treatise? Do they have a specific type in lobid?

**Comment by acka47** [comment]
I found a "Diplomarbeit" in the catalog, see http://lobid.org/resource?id=HT009060096&format=source. It isn't typed as Thesis, though.

**Comment by acka47** [comment]
I found another "Diplomarbeit" (http://lobid.org/resource/HT009067278/about, [source](http://lobid.org/resource?id=HT009067278&format=source)) which is actually typed as `bibo:Thesis`.

**Comment by acka47** [comment]
Here is an unspecified one: http://lobid.org/resource/HT009069745/about & http://lobid.org/resource?id=HT009069745&format=source

**Comment by acka47** [comment]
Her is a very old "Universitätsschrift" which is not typed as such:http://lobid.org/resource/HT009060414/about.

**Comment by acka47** [comment]
And finally I also found a "**Habilitationsschrif**t" typed as `bibo:Thesis`: http://lobid.org/resource/HT009066992/about, source: http://lobid.org/resource?id=HT009066992&format=source

**Comment by acka47** [comment]
> The good thing is: I am quite sure that only doctoral thesises get catalogued so all of them should be of this type.

This statement is now disproved by the examples in the comments above.

**Comment by acka47** [comment]
@jschnasse I hope you now have some more clarity regarding your initial two questions. Can we close this ticket, then?

**Comment by acka47** [comment]
I just talked to @jschnasse, he now has absolute clarity. We decided not to try adding more detaiuled typing but at least to add the information from field 519 to the RDF. I will investigate the way to go forward in another ticket (#177). Closing this one.
