### ISSUE TITLE
Missing URN  in http://lobid.org/resource/HT017480009/about 

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#167]
Why does the URN not show up in lobid?

http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DHT017480009

We need that identifier for our FRL repo (formerly Ellinet).

**Comment by dr0i** [comment]
What URN do you need?
I can see `http://nbn-resolving.de/urn:nbn:de:hbz:38m-0000006293` for http://lobid.org/resource/HT017480009 .

**Comment by jschnasse** [comment]
What about http://purl.org/lobid/lv#urn ?

**Comment by acka47** [comment]
According to the [morph file, lines 688-694](https://github.com/lobid/lodmill/blob/master/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L688-L694), we take the URN from field 552b. In the referenced resource, the URN is stored in a field named `URN`, though. From the [source](http://lobid.org/resource?id=HT017480009&format=source):
```xml
datafield tag="URN" ind1="-" ind2="1">
<subfield code="a">urn:nbn:de:hbz:38m-0000006293</subfield>
<subfield code="p">DTL2ALEPH:4826540</subfield>
</datafield>
```

**Comment by dr0i** [comment]
Uh - this is not MAB conform. Why is this even possible?

**Comment by jschnasse** [comment]
It is ExL stuff: Comes from Digitool

Example that provides lobid:urn
http://lobid.org/resource/HT016173828/about

**Comment by jschnasse** [comment]
Maybe it is more hbz stuff and should prevent overrides, so they reserve their own field.

**Comment by acka47** [comment]
> Example that provides lobid:urn
http://lobid.org/resource/HT016173828/about

For this resource the URN is stored – correctly – in 552b, from the [source](http://lobid.org/resource?id=HT016173828&format=source):

```xml
<datafield tag="552" ind1="b" ind2="1">
<subfield code="a">urn:nbn:de:hbz:929:02-edoweb:34301760</subfield>
</datafield>
```

I don't know why this `URN` field exists...

**Comment by acka47** [comment]
@jschnasse Can you tell us whether Ellinet generally uses the `URN` field instead of 552?

**Comment by dr0i** [comment]
I asked the hbz Verbund and they said 1. this field exists for a very long time and 2. it is expanded to `552b` for most exports (Z39.50 etc.). Why it is missing in the AlephMabXml export is not cleared yet.

**Comment by dr0i** [comment]
Git the answer: Correct is `AlephXml` not `AlephMabXml`, and for the former one it is correct to have `URN`. I found in the description of the export (https://wiki1.hbz-nrw.de/pages/viewpage.action?pageId=13238276 (German)) a table referenced ("tab_fix_mab") which shows up the ominous `URN` field.
So, the solution is to take the `URN` filed into acount when transforming the data to LOD.

**Comment by dr0i** [comment]
Deployed to production. @jschnasse plz have a look.

**Comment by acka47** [comment]
+1 from me

**Comment by jschnasse** [comment]
+1

**Comment by dr0i** [comment]
Closing.

**Comment by dr0i** [comment]
Sorry folks, the pull request was not merged. Don't know what was going here.

**Comment by dr0i** [comment]
Deployed to production after merging into master. Closing.
