### ISSUE TITLE
Use lv properties instead of dc elements for lists of alternate labels

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#169]
Requested by @jschnasse . Listing several labels of one contributor/creator or subject under `dc:contributor`/~~`dc:creator`/~~`dc:subject` seems wrong as it leaves the impressions of having more contributors/creators than there actually are. We should rather use properties from our local lobid vocab namespace. As this is only intended to be an interims solution, we could just use properties without defining them in the vocab as we already do with `contributingCorporateBodyLabel`.

**Comment by acka47** [comment]
To do:
- [ ] Adjust morph
- [ Adjust context file
- [ ] OPTIONAL Add properties to lobid vocab

**Comment by acka47** [comment]
The morph has to be updated like this:
- [ ] Replace all occurences of `http://purl.org/dc/elements/1.1/contributor` by `http://purl.org/lobid/lv#nameOfContributingPerson`
- [ ] Replace `http://purl.org/dc/elements/1.1/subject` by `http://purl.org/lobid/lv#subjectLabel`

**Comment by acka47** [comment]
After running the morph, the JSON-LD context has to be updated like this:

- [ ] Replace `"contributorLabel": "http://purl.org/dc/elements/1.1/contributor"` b< "contributorLabel": "http://purl.org/lobid/lv#contributorLabel"
- [ ] Replace `"subjectLabel": "http://purl.org/dc/elements/1.1/subject"` by `"subjectLabel": "http://purl.org/lobid/lv#subjectLabel"`

**Comment by acka47** [comment]
@dr0i, what do you think: Should I update the morph myself according to https://github.com/hbz/lobid/issues/169#issuecomment-113487704?

**Comment by dr0i** [comment]
Just give it a try. Put in in an branch of its own, as normal. I will review it.

**Comment by dr0i** [comment]
Deployed to testing.

**Comment by dr0i** [comment]
Deployed to production, closing.

**Comment by jschnasse** [comment]
thx! Looks nice so far.

**Comment by dr0i** [comment]
We forgot to update the API as well, thus leading to hbz/nwbib#117.

**Comment by dr0i** [comment]
Reclosing due to resolving hbz/nwbib#117.
