### ISSUE TITLE
Handhabung von gelöschten Saätzen

### ISSUE THREAD

**Issue by donboern** [hbz/lobid#17]
Ich bin auf einen Satz gestoßen, der in den Ausgangsdaten aber unlängst gelöscht wurde, weil er wohl eine Dublette war. Es erscheint mir sinnvoll, dass die einmal ausgegebene URI noch vorhanden ist. Einen Kommentar oder sonstigen Hinweis in den Daten, dass dieser Satz eigentlich gelöscht ist, fände ich aber ebenfalls sinnvoll.

Satz bei lobid:
http://lobid.org/resource/HT017160923/about

Löschmeldung des Verbundes zu HT017160923:

``` xml
<OAI-PMH xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
<ListRecords>
<record>
<header status="deleted">
<identifier>aleph-publish:019068055</identifier>
</header>
<metadata>
<record>
<leader>00910nM2.01200024------h</leader>
<controlfield tag="LDR">00910nM2.01200024------h</controlfield>
<controlfield tag="FMT">MH</controlfield>
<controlfield tag="SYS">019068055</controlfield>
<datafield tag="DEL" ind1="-" ind2="1">
<subfield code="a">Y</subfield>
</datafield>
</record>
</metadata>
</record>
</ListRecords>
</OAI-PMH>
```

Weiterer Satz zu diesem Titel:
http://lobid.org/resource/HT014887379/about

**Comment by acka47** [comment]
The example above has been deleted in lobid by now. Here is another example of a record currntly deleted in hbz catalogue but still in lobid: http://lobid.org/nwbib/BT000165331

**Comment by dr0i** [comment]
This record will be deleted in lobid with the weekly regeneration of the index. Since this regeneration fails since last week (missing all enrichments done via lodmil-ld ), we switched to an old index (2015-03-28) and incrementally update this one. Thus, now deletions since 2015-03-28.

**Comment by dr0i** [comment]
For quite some time a fulldump is successfully  indexed weekly. Closing.
