### ISSUE TITLE
Some hasPart relations missing

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#171]
Example:
http://lobid.org/resource/HT018585378 says `"isPartOf" : "http://lobid.org/resource/HT018583629"` but http://lobid.org/resource/HT018583629 doesn't have a `hasPart` link back.

**Comment by acka47** [comment]
Another example is http://lobid.org/resource/HT018193229:

It is linked with `isPartOf` from http://lobid.org/resource/HT018206132 but doesnt contain a `hasPart` link back.

**Comment by acka47** [comment]
As in all these examples somehow acollection is involved that is not really transformed to RDF at the moment this might have something to do with #155 and – if we are lucky – might be resolved together with #155.

**Comment by acka47** [comment]
Thinkinjg about this more, this might not be an actual issue. I guess we don't have all the `hasPart` links in the data in the first place. We will have to check this.

**Comment by ChristophEwertowski** [comment]
We don't have `hasPart` links anymore. Therefore closing this issue.
