### ISSUE TITLE
Move hbz01tordf transformation code to repo hbz/lobid-resources

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#172]
With deploying to production #139 we moved away hadoop and should now move the hbz01 transformation code to hbz/lobid-resources.

We will wait with this until @fsteeg is back, though – except he gives his approval on this ticket before.

**Comment by dr0i** [comment]
The moving has started, see https://github.com/hbz/lobid-resources/issues/1 . The new repo will be used by the upcoming lobid API 2.0 and shortly by [NWBib](https://github.com/hbz/nwbib), so it is to be expected that the old [lobid/lodmill repo](https://github.com/lobid/lodmill) will be still alive and active more some time in parallel to the new repo.
Closing this issue.
