### ISSUE TITLE
Getting loads of data (aka dump)

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#176]
It should be possible to load lots of data, e.g. for hbz/nwbib#106. Getting this dump it is not save to use `deep pagination` (setting `from`and `size` and repeat the iterated  lookups) because there are background merge processes in elasticsearch, resulting in doublets and missing data (this can be reproduced when using https://github.com/hbz/lobid/blob/master/test/tests/SampleUsage.java ). Also, [`deep pagination` is very inefficient](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html). 

Solution:
to get the data reliable and fast the `scroll`and `scan` API must be used.

**Comment by jbaiter** [comment]
This would be incredible, I've been playing around with `from` and `size` a bit, with a very bad conscience about the server load I must've been producing, good to know that I was most likely missing out on a lot of data, too!
Exposing `scroll`/`scan` would be great :-)

**Comment by akuckartz** [comment]
How about [Triple Pattern Fragments](http://www.hydra-cg.com/spec/latest/triple-pattern-fragments/)?

**Comment by acka47** [comment]
@akuckartz Thanks for the comment. We are aware of the Linked Data Fragments approach. Anyway, we built the lobid API so that people can access the data without knowing about RDF Triples and SPARQL. We will think about adding triple pattern fragments functionality in the future. I opened an issue for this, see #181.
Would you use the functionality if provided?

**Comment by dr0i** [comment]
Deployed to production.
For usage explanation have a look at the [api overview page](http://lobid.org/api) -> Bulk Downloads.
The result is now reproducible ever the same, and it's fast. Would be even much faster zipping the data but leave that for now as it is.
Comments or questions are of course welcome.
Closing the issue.

**Comment by dr0i** [comment]
A quick note: the last commit fixes a bug shortly introduced after closing this issue.
