### ISSUE TITLE
Add information from field 519 to RDF

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#178]
See https://github.com/hbz/lobid/issues/166#issuecomment-114087749.

**Comment by acka47** [comment]
I found the right RDA property for this: [rdau:P60489](http://rdaregistry.info/Elements/u/P60489). From the description:

> Relates a resource to information about a resource presented as part of the formal requirements for an academic degree.

See also the respective [paragraph in the RDA toolkit](http://access.rdatoolkit.org/document.php?id=rdachp7&target=rda7-677#rda7-677) (authentification needed).

**Comment by acka47** [comment]
If – besides subfield a which should be there for all records with field 519 – also subfield p exists both should be concatenated. Example http://lobid.org/resource?id=HT018239864&format=source should result in:

`<http://lobid.org/resource/HT018239864> <http://rdaregistry.info/Elements/u/P60489> ">Zugl. Göttingen, Univ., Diss., 2013" .`

**Comment by dr0i** [comment]
@acka47 see the diffs, e.g. https://github.com/lobid/lodmill/commit/9ce9052c069d6cc77965dfc60c066bc7321225fc#diff-f6a6eb684e027c0ab8bd2b12b15b19c6R3727

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
We will have to adjust the context for this. Will use the key "thesisInformation" for this.

**Comment by dr0i** [comment]
Deployed context to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
