### ISSUE TITLE
Some GND labels not correctly built from Aleph XML

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#179]
E.g. , the label of GND entity http://d-nb.info/gnd/36467-8 isn't correctly transformed to RDF, see http://lobid.org/resource?author=36467-8. lt should read "Rheinland-Pfalz. Statistisches Landesamt" or similar and not only "Rheinland Pfalz".

[Example](http://lobid.org/resource?id=HT018216462&format=source) source data (snippet):

```xml
<datafield tag="205" ind1="-" ind2="1">
   <subfield code="k">Statistisches Landesamt</subfield>
   <subfield code="h">Rheinland-Pfalz</subfield>
</datafield>
```

In RDF, subfields `h` and `k`should be concatenated, resulting in:

```javascript
{
    "@id" : "http://d-nb.info/gnd/36467-8",
    "preferredName" : "Rheinland Pfalz. Statistisches Landesamt",
    "preferredNameForTheCorporateBody" : "Rheinland Pfalz. Statistisches Landesamt"
}
```

**Comment by acka47** [comment]
@jschnasse Let us know if this has to be prioritized.

**Comment by acka47** [comment]
Similar to #735 but for corporations.

**Comment by acka47** [comment]
Another example:

Source:

```xml
<datafield ind2="1" ind1="-" tag="200">
            <subfield code="k">Deutschland</subfield>
            <subfield code="b">Bundesministerium für Gesundheit</subfield>
            <subfield code="9">(DE-588)2117859-8</subfield>
</datafield>
<datafield ind2="1" ind1="a" tag="204">
            <subfield code="k">Deutschland</subfield>
            <subfield code="b">Umweltbundesamt</subfield>
            <subfield code="9">(DE-588)2116834-9</subfield>
</datafield>
```

Current JSON:

```javascript
{
    "@id" : "http://d-nb.info/gnd/2117859-8",
    "preferredName" : "Deutschland",
    "preferredNameForThePerson" : "Deutschland"
 }, {
    "@id" : "http://d-nb.info/gnd/2116834-9",
    "preferredName" : "Deutschland",
    "preferredNameForThePerson" : "Deutschland"
  }
```

Expected JSON:

```javascript
{
    "@id" : "http://d-nb.info/gnd/2117859-8",
    "preferredName" : "Deutschland. Bundesministerium für Gesundheit",
    "preferredNameForThePerson" : "Deutschland. Bundesministerium für Gesundheit"
 }, {
    "@id" : "http://d-nb.info/gnd/2116834-9",
    "preferredName" : "Deutschland. Umweltbundesamt",
    "preferredNameForThePerson" : "Deutschland. Umweltbundesamt"
  }
```

**Comment by dr0i** [comment]
Data will be deployed tomorrow for testing.
Because I don't work tomorrow:
If you find staging good, go on and merge the open pull request. Data will then be ready on monday and I can go to deploy them to production then.
(if you feel bold or @fsteeg can help you, you may also want to switch staging index to production tomorrow. Hm. Ok this only takes 2 minutes, I will probably have a look tomorrow myself and will switch myself :) )

**Comment by acka47** [comment]
Looks great from my side: +1 @jschnasse What do you think?

**Comment by jschnasse** [comment]
http://test.lobid.org/resource?author=36467-8 looks still wrong?

**Comment by dr0i** [comment]
The test instance is automatically switched to the newest index which is build weekly at the weekend, not having the commit merged thus not having the new data in it.
I switched the index alias back to index which reflects the commit.
So, please review anew.

**Comment by jschnasse** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
