### ISSUE TITLE
Mapping for field 078 needed

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#180]
allow me to quote the description from my recent emails:

> für unser Ellinet-Nachfolge-Repositorium benötigen wir ein Mapping
für Feld 078. In diesem Feld wurde von der zbmed zusätzlich zum
Ellinet-Selektionskennzeichen die assoziierte Institution in Form einer
GND-ID erfasst (unterscheidet sich wohl semantisch von 200).

> Beispiel:
<subfield code="a">38 M: ellinet ; GND: (DE-588)2137494-6</subfield>

> Anstatt "38 M: ellinet" kann auch "98 : ellinet" vorkommen. Der
nachvollgende Eintrag "GND:.*" muss nicht vorkommen.

> Uns interessiert z.Z. nur die GND-Daten aus dem Feld 078.
Als prädikat käme z.B. in Frage: dbpedia-owl:institutionoder
aiiso:Institution

**Comment by acka47** [comment]
Example http://lobid.org/resource/HT015697059/about?format=source, snippet:

```xml
<datafield tag="078" ind1="r" ind2="1">
   <subfield code="a">38 M: ellinet; GND: (DE-588)2180083-2</subfield>
</datafield>
```

Example http://lobid.org/resource/HT016075829/about?format=source, snippet:

```xml
<datafield tag="078" ind1="i" ind2="1">
   <subfield code="a">iall</subfield>
</datafield>
<datafield tag="078" ind1="r" ind2="1">
   <subfield code="a">38 M: ellinet</subfield>
</datafield>
```
:grey_exclamation: Note , that field 078 is repeated here. We will have to take into account indicator `r`.

Example http://lobid.org/resource/HT016702347/about?format=source, snippet:

```xml
<datafield tag="078" ind1="i" ind2="1">
   <subfield code="a">iall</subfield>
</datafield>
<datafield tag="078" ind1="r" ind2="1">
   <subfield code="a">98: ellinet</subfield>
</datafield>

```

**Comment by acka47** [comment]
The question is which property we use to indicate the "associated institution". I guess the value is always one from [`98`](http://lobid.org/organisation/DE-98) or [`38M`](http://lobid.org/organisation/DE-38M). [`dbpedia:institution`](http://dbpedia.org/ontology/institution) seems general enough for our case. So I also suggest using it in this case.

**Comment by acka47** [comment]
We should also think about implementing this via collections – similar to [NWBib](http://lobid.org/resource/NWBib) and [edoweb](http://lobid.org/resource/Edoweb) – and `isPartOf` relations.

I talked to @jschnasse about this requirement. It is probably better to clarify the use case this adjustment should serve and then decide on how to implement it.

**Comment by acka47** [comment]
It's not that easy to find other examples with a GND ID in `078`. Here are two more.

http://lobid.org/resource/HT017738056/about?format=source, snippet:

```xml
<datafield tag="078" ind1="i" ind2="1">
   <subfield code="a">iall</subfield>
</datafield>
<datafield tag="078" ind1="r" ind2="1">
   <subfield code="a">38 M: ellinet; GND: (DE-588)16007439-3</subfield>
</datafield>
```

http://lobid.org/resource/HT017901785/about?format=source, snippet:
```xml
<datafield tag="078" ind1="i" ind2="1">
   <subfield code="a">iall</subfield>
</datafield>
<datafield tag="078" ind1="r" ind2="1">
   <subfield code="a">38 M: ellinet; GND: (DE-588)2159834-4</subfield>
</datafield>
```

BTW, I just tried ten resources six of which had a GND ID in 078: [HT018389798](http://lobid.org/resource/HT018389798/about?format=source), [HT018389903](http://lobid.org/resource/HT018389903/about?format=source), [HT018362994](http://lobid.org/resource/HT018362994/about?format=source), [HT018362919](http://lobid.org/resource/HT018362919/about?format=source), [HT018361570](http://lobid.org/resource/HT018361570/about?format=source), [HT018361926](http://lobid.org/resource/HT018361926/about?format=source).

**Comment by acka47** [comment]
Assigning @jschnasse to clarify the user story for this one.

**Comment by jschnasse** [comment]
forget it. i will implement it by myself using the mabxml.
