### ISSUE TITLE
Support HTTPS in lobid

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#182]
Requested on 2015-06-26 by T. Scheffler who is working on the [MIR repository software](http://www.mycore.de/mir/content/index.xml). They use lobid GND API for lookup of GND persons.

If we need some advice we can ask @jschnasse who has some experience with HTTPs for hbz services.

**Comment by acka47** [comment]
We will go forward like this:

- [ ] get the SSL certificate
- [ ] implement https in https://github.com/hbz/lobid-organisations
- [ ] Implement https for GND API endpoint (http://lobid.org/subject and http://lobid.org/person)
- [ ] Implement https for NWBib
- [ ] Discuss how to and make a plan to switch to https in lobid-resources.

**Comment by akuckartz** [comment]
:+1:

**Comment by acka47** [comment]
Here is a site to analyze the configuration of an SSL-Server: https://www.ssllabs.com/ssltest/analyze.html As soon as we have a first implementation we can use this for testing.

**Comment by dr0i** [comment]
Deployed to http://test.lobid.org and https://beta.lobid.org/.

**Comment by acka47** [comment]
It works – but doesn't get the best grades, see https://www.ssllabs.com/ssltest/analyze.html?d=http%3A%2F%2Ftest.lobid.org%2F

**Comment by acka47** [comment]
Chromium says:

![test-lobid-ssl](https://cloud.githubusercontent.com/assets/160292/10013775/af271d14-6114-11e5-9e29-aac372680216.png)

I would rather have it looking like oerworldmap:

![oerworldmap-ssl](https://cloud.githubusercontent.com/assets/160292/10013785/c00dd230-6114-11e5-8114-ec26da75ac22.png)

This is ok for now and can be deployed as it suffices for the initial request by T. Scheffler. We will discuss on Thursday when we will work on improving it.

**Comment by dr0i** [comment]
We could make `https` as default, not allowing `http` at all. This would it make easier to handle the vhost apache configs. But I would argue against that, especially because of the big downloads we provide, because caching is with `https` no more possible.
For the discussion a little bit of [context](https://security.stackexchange.com/questions/18853/why-arent-application-downloads-routinely-done-over-https).

**Comment by dr0i** [comment]
Deployed to production. @acka47 please ping `MIR repo`.

**Comment by acka47** [comment]
> please ping `MIR repo`.

Did so. Closing.

**Comment by dr0i** [comment]
As reported by @jschnasse, the api-URL (api.lobid.org) is not ssl enabled. @fsteeg : do we need the `api` subdomain at all? If we could get rid of it , we should do so, and then update the documentation at https://lobid.org/api.

**Comment by fsteeg** [comment]
I don't think we need the `api` subdomain, and it already redirects to `lobid.org`, see: http://api.lobid.org

So I think all we need to do is to update the documentation. Deployed to staging: http://test.lobid.org/api

**Comment by dr0i** [comment]
Great :)
