### ISSUE TITLE
Type filter doesn't work for /subject endpoint

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#185]
See e.g. the example from the API documentation: http://lobid.org/subject?name=Heinsberg&type=http://d-nb.info/standards/elementset/gnd%23BuildingOrMemorial

**Comment by acka47** [comment]
Also, as the /person endpoint depends on type filtering it doesn't work at all. See the examples from the API doc:
- http://lobid.org/person?id=118580604
- http://lobid.org/person?name=Johann+Sebastian+Bach
- http://lobid.org/person?q=%22Bruder+von%22

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.

**Comment by dr0i** [comment]
Note:
After resolving  #520 (updating an outdated index profile) it appeared that the index profile for the gnd was not correct in part.
