### ISSUE TITLE
Update play to -2.4.2- 2.3.10

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#186]
Due to memory leak issues it seems best to update play to the moset recent version.
This ticket is fundamental for #176.

**Comment by fsteeg** [comment]
Unless you're sure about the memory issue being caused and fixed by Play itself, I'd be careful about updating. New Play versions change API and other subtle things. The second digit in Play version numbers actually indicates major changes, unlike most other version numbers.

**Comment by dr0i** [comment]
Fiddled myself trying to update to 2.4 but failed utterly.

**Comment by dr0i** [comment]
This ticket may solve #188.
Note the last commit, updating activator to 1.3.5: this update seems to reduce memory leaking very much! So, the update to play 2.4.x may not be that important at all.

**Comment by fsteeg** [comment]
I'd suggest we update to 2.3.10, the latest maintenance release for 2.3 instead.

**Comment by dr0i** [comment]
+1
