### ISSUE TITLE
subjectLabel isn't searched with ?subject query

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#189]
See e.g. http://lobid.org/resource?subject=wiedert%C3%A4ufer&set=nwbib which should deliver ~158 hits. 

One resource that has "Wiedertäufer" as `subjectLabel` but isn't in result list is http://lobid.org/resource/HT018392783.

**Comment by dr0i** [comment]
Deployed to staging. Delivers 161 hits.

**Comment by acka47** [comment]
Looks good. +1

**Comment by dr0i** [comment]
Deployed to production, closing.
