### ISSUE TITLE
Collection and team not rendered in html

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#193]
The response content type is wrongly `text/plain` even when provided as `rdfa`. Thus a browser don't render the html.

See http://lobid.org/team/ap , http://lobid.org/resource/RPB/about etc.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1. Closing, as this is already deployed to production.

**Comment by dr0i** [comment]
Unfortunately this breaks e.g. when using the `scroll`parameter , see #176.

**Comment by dr0i** [comment]
Fix deployed to production, closing.
