### ISSUE TITLE
Set up Skosmos instance

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#209]
See https://github.com/NatLibFi/Skosmos/wiki/Installation. I want to use this for publishing a human-readable and browsable version of the SKOS concept schemes we created (NWBib, RPB as well as https://github.com/hbz/oerworldmap/issues/220).

Skosmos also provides an [API](https://github.com/NatLibFi/Skosmos/wiki/REST-API) that probably can be used for auto-suggest/completion in edit/search forms.

**Comment by dr0i** [comment]
For further installation, it seems that a `composer.json` must be created in the first place to define your project, see https://getcomposer.org/doc/04-schema.md : 

    $ php composer.phar install --no-dev
    Composer could not find a composer.json file in /opt
    To initialize a project, please create a composer.json file as described in
    the https://getcomposer.org/ "Getting Started" section
    
 @acka47  can you provide this?

**Comment by acka47** [comment]
There is a `composer.json` file in the Skosmos GitHub repository, see https://github.com/NatLibFi/Skosmos/blob/master/composer.json. Please use this one.

**Comment by akuckartz** [comment]
:+1:

**Comment by dr0i** [comment]
Deployed to http://aither.hbz-nrw.de/skosmos/en/ .

**Comment by acka47** [comment]
We need the SKOS vocabularies in a triplestroe with SPARQL endpoint. Where can I load them?

**Comment by dr0i** [comment]
4store is running. DB is named 'skosmos'. Have a log in the process list:

    $ ps -ef | grep 4s

To import data, see http://4store.org/trac/wiki/ImportData.

**Comment by dr0i** [comment]
Since there seems to be trouble using this 4store version and skosmos, we try fuseki. Fuseki is startet in a `screen` session:

    lod@aither:/opt/apache-jena-fuseki-2.3.0$ fuseki-server --update --loc=DB /ds

**Comment by acka47** [comment]
Closing this one. Made some more tickets regarding the specific concept schemes, see https://github.com/hbz/isced/issues.
