### ISSUE TITLE
Adjust @context URL

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#211]
The @context URL for lobid.resources must be changed from http://api.lobid.org/context/lobid-resources.json to http://lobid.org/context/lobid-resources.json. The current redirect gives an error in the JSON-LD playground, see e.g. http://tinyurl.com/pgwwaka.

**Comment by fsteeg** [comment]
Deployed to staging, see:
http://test.lobid.org/resource?id=HT002189125&format=full
http://tinyurl.com/pqshzfg

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Reassigning for production deployment when staging has full data (for the switch).

**Comment by dr0i** [comment]
Deployed to production, closing.
