### ISSUE TITLE
Wrap an record tag around an rdf xml resource

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#223]
Reported by Werner Greßhoff:

Getting multiple records every rdf xml resource should be wrapped in a tag for easier parsing.

> ich hatte vor einiger Zeit angeregt das
> gesamte Ergebnis mit einem Root-Tag zu umklammern, damit ein
> gültiges XML-Dokument entsteht. Das ist auch passiert, leider
> ist dabei auch etwas verloren gegangen: das RDF-Tag ist jetzt
> auch nur noch einmal vorhanden und nicht mehr, wie vorher, um
> jeden Metadatensatz! Einzelne Dokumente sind damit nur noch über
> das about-Attribut zu erkennen.

**Comment by dr0i** [comment]
Maybe this contradicts #463? What do you think @fsteeg ?

**Comment by fsteeg** [comment]
Deployed to staging.

Standard request (no `scroll`), wraps into `<docs>`:

`curl -L --header "Accept: application/rdf+xml" "http://test.lobid.org/resource?q=ehrenfeld" > rdf.xml` `xmllint rdf.xml`
`rapper -i rdfxml rdf.xml`

`scroll` request, additionally wrapped into `<root>`:

`curl -L --header "Accept: application/rdf+xml" "http://test.lobid.org/resource?q=ehrenfeld&scroll=20100701" > rdf.xml` 
`xmllint rdf.xml`
`rapper -i rdfxml rdf.xml`

Note that with `scroll`, subsets of the documents are wrapped into `<docs>`.

**Comment by dr0i** [comment]
Deployed to production. Let's wait what Werner says to this solution.

**Comment by dr0i** [comment]
We got an OK, thus closing.

**Comment by jschnasse** [comment]
@dr0i asked me to put my observations to here. In rdf4j lib I get an error when consuming rdf+xml data from lobid (e.g. http://lobid.org/resource/HT017612594/about)
Cause of Error:
org.openrdf.rio.RDFParseException: <rdf:RDF> not allowed as property element [line 15, column 76]

Example in curl:
curl -H"accept: application/rdf+xml" http://lobid.org/resource/HT017612594/about

Example in rapper:
rapper -i rdfxml http://lobid.org/resource/HT017612594/about

Rapper also gives a warning but proceeds:
rapper: Parsing URI http://lobid.org/resource/HT017612594/about with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Warning - URI http://lobid.org/resource/HT017612594/about:1 - Using node element 'docs' without a namespace is forbidden.
