### ISSUE TITLE
Support multi value queries

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid#226]
For https://github.com/hbz/nwbib/issues/97 and https://github.com/hbz/nwbib/issues/129 we need to support multi-value queries (logical AND) for:

- [x] `nwbibsubject`
- [x] `nwbibspatial`
- [x] `subject`
- [x] `medium`

We already support multi-value queries (logical OR) for:

- [x] `type`
- [x] `owner`

**Comment by fsteeg** [comment]
Deployed to staging, see:

- http://test.lobid.org/resource?subject=4066438-7,4077548-3&format=full
- http://test.lobid.org/resource?nwbibspatial=K%C3%B6ln,M%C3%B6nchengladbach&format=full
- http://test.lobid.org/resource?nwbibsubject=http://purl.org/lobid/nwbib%23s706230,http://purl.org/lobid/nwbib%23s704042&format=full
- http://test.lobid.org/resource?medium=http://rdvocab.info/termList/RDACarrierType/1018,http://rdvocab.info/termList/RDACarrierType/1010&format=full

**Comment by acka47** [comment]
Subject search also works with subject URIs, e.g. http://test.lobid.org/resource?subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F4066438-7,http%3A%2F%2Fd-nb.info%2Fgnd%2F4077548-3&format=full

**Comment by acka47** [comment]
...as well as http://test.lobid.org/resource?subject=http://d-nb.info/gnd/4066438-7,http://d-nb.info/gnd/4077548-3&format=full

**Comment by acka47** [comment]
I assume the spatial search also works with URIs. Can't test it as there are probably not so much resources with double NWBib spatial notations and probably none of them in the test set.

**Comment by acka47** [comment]
I don't see the use of combining two medium types with AND. With the exception of "electronic resource" and "oline resource" there should be only one medium. IMO, an OR combination would make more sense in this case.

**Comment by acka47** [comment]
Will leave this open, as discussed offline. We are still not sure whether an AND combination for multi-value queries is the way to go. The optimal way would be to support AND and OR API-wise. This might best be implemented with API 2.0, though...

For now, @fsteeg will get to know the frontend possibilities and we will discuss this again at a later point.

**Comment by fsteeg** [comment]
After some more discussion we agreed to use OR, mainly for being consistent across all facets (holdings only make sense with OR) and our current UX (facets do not narrow down themselves).

**Comment by fsteeg** [comment]
Changed boolean logic to OR, deployed to staging, see:

- http://test.lobid.org/resource?subject=4066438-7,4077548-3&format=full
- http://test.lobid.org/resource?nwbibspatial=K%C3%B6ln,M%C3%B6nchengladbach&format=full
- http://test.lobid.org/resource?nwbibsubject=http://purl.org/lobid/nwbib%23s706230,http://purl.org/lobid/nwbib%23s704042&format=full
- http://test.lobid.org/resource?medium=http://rdvocab.info/termList/RDACarrierType/1018,http://rdvocab.info/termList/RDACarrierType/1010&format=full

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

- http://lobid.org/resource?subject=4066438-7,4077548-3&format=full
- http://lobid.org/resource?nwbibspatial=K%C3%B6ln,M%C3%B6nchengladbach&format=full
- http://lobid.org/resource?nwbibsubject=http://purl.org/lobid/nwbib%23s706230,http://purl.org/lobid/nwbib%23s704042&format=full
- http://lobid.org/resource?medium=http://rdvocab.info/termList/RDACarrierType/1018,http://rdvocab.info/termList/RDACarrierType/1010&format=full
