### ISSUE TITLE
Allow compression within apache

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#234]
Serving raw data compressed speeds up delivering considerably.
This is especially true when doing bulk downloads (see hbz/lobid#176).
Apache can be configured using DEFLATE and thus will serve the data compressed if the client is able to accept this encoding.
The costs reside on the clients (for decompressing) and on the apache server side (for compressing). But CPU power is not the bottleneck, so these costs are much cheaper than to not compress.

**Comment by dr0i** [comment]
Enabled in staging. 
@acka47 @fsteeg @jschnasse do you experience any issues using your browsers (which accept gzip encoding by default) and your other tools querying test.lobid.org? If not I would want to enable this behaviour for whole lobid.org.

**Comment by jschnasse** [comment]
Seems to work for edoweb. No browser errors experienced.

**Comment by dr0i** [comment]
Deployed to prodution, closing.
