### ISSUE TITLE
Add anchors to API page

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#236]
I'd like to have direct links to paragraphs in http://lobid.org/api. Please add the following anchors:

- http://lobid.org/api#pagination+limits+bulk-downloads
- http://lobid.org/api#content-negotiation
- http://lobid.org/api#auto-suggest-examples

**Comment by fsteeg** [comment]
Deployed to staging:

http://test.lobid.org/api#pagination+limits+bulk-downloads
http://test.lobid.org/api#content-negotiation
http://test.lobid.org/api#auto-suggest-examples

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/api#pagination+limits+bulk-downloads
http://lobid.org/api#content-negotiation
http://lobid.org/api#auto-suggest-examples
