### ISSUE TITLE
519 Hochschulschriftenvermerk

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#238]
IMO, MAB 519 can be mapped to dc:publisher at least if 051 is  equal my||||.... What do you think?

**Comment by jschnasse** [comment]
Example given: http://lobid.org/resource/HT018753058/about

**Comment by acka47** [comment]
I don think we can do this as the actual publisher isn't indicated in 519 but the publication place and the publication date. As we can't reliably parse the information out of the one field, I would leave it this way.

Is this a request by ZB MED customers?

**Comment by jschnasse** [comment]
Sorry, I overlooked that the data is already included under http://rdaregistry.info/Elements/u/P60489. This seems to be sufficient.
