### ISSUE TITLE
Enhance Mapping on bibo:Proceedings

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#243]
Suggested rules:

if MAB51 begins  with mk --> map to http://purl.org/ontology/bibo/Proceedings

if MAB51 begins with ak --> map to http://purl.org/spar/fabio/ConferencePaper

**Comment by acka47** [comment]
@ChristophEwertowski Please have a look at some point whether this is still needed.

**Comment by ChristophEwertowski** [comment]
The proceedings suggestion is already included. A grep on the baseline didn't result in resources with "051>ak". So I'll close this issue.
