### ISSUE TITLE
Wrong triple on http://lobid.org/resource/HT016048134

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#249]
I found this data attached to the resource
```
<http://d-nb.info/gnd/16030343-6> <http://d-nb.info/standards/elementset/gnd#preferredNameForThePerson> "Bayern"^^<http://www.w3.org/2001/XMLSchema#string> .
<http://d-nb.info/gnd/16030343-6> <http://d-nb.info/standards/elementset/gnd#preferredNameForTheCorporateBody> "Bayern"^^<http://www.w3.org/2001/XMLSchema#string> .
<http://d-nb.info/gnd/16030343-6> <http://d-nb.info/standards/elementset/gnd#preferredName> "Bayern"^^<http://www.w3.org/2001/XMLSchema#string> .
```

If you look at http://d-nb.info/gnd/16030343-6, this seems to be wrong.

**Comment by acka47** [comment]
We need to fix this (as well as https://github.com/lobid/lodmill/issues/735) asap. The problem here is the label (not the incorrect use of `preferredNameForThePerson`).

From the source (snippet):

```xml
<datafield ind2="1" ind1="b" tag="200">
            <subfield code="k">Bayern</subfield>
            <subfield code="b">
              Bayerisches Landesamt für Gesundheit und Lebensmittelsicherheit
            </subfield>
            <subfield code="9">(DE-588)16030343-6</subfield>
</datafield>
```

Obviously, subfield `b` isn't taken into account in the transformation.

**Comment by acka47** [comment]
Another example is http://lobid.org/resource/HT016048134. We should concatenate subfields `k` and `b` with a period and space in between. E.g. "Bayern. Bayerisches Landesamt für Gesundheit und Lebensmittelsicherheit" in http://lobid.org/resource/HT016048134 and "Nordrhein-Westfalen. Ministerium für Inneres und Kommunales" in http://lobid.org/resource/HT016048134.

**Comment by dr0i** [comment]
Ah, yeah I was to ask `Should fields be concatenated like in https://github.com/hbz/lobid/issues/179 ? Or has it nothing to do with it?` 
Also, interesting documentation is https://wiki1.hbz-nrw.de/display/VDBE/GND-2+-+Neue+Unterfeldstruktur+in+BIB . `k` denotes the name of the corporation, `b` is the name of the subordinated corporation.

**Comment by acka47** [comment]
+1

**Comment by jschnasse** [comment]
i hope everything works now. Please inform me as soon as index is ready.

**Comment by dr0i** [comment]
>  Thus, we would have not only concatenate k, h but k. b, h . Yes?

No. `h` seems to be mostly acted as an location addendum to `k`, thus it was wrapped liked in `<b>`, not comma separated. Thus, with the new commit we  have the following precedence and structure:

`k <h>. b` , `k. b`, `k <h>`, `k`.

Hope this makes sense.

**Comment by acka47** [comment]
Looks good to me.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed tp production, closing.
