### ISSUE TITLE
Special characters aren't encoded correctly in source tab

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#251]
See any lobid resource – e.g. http://lobid.org/resource/CT003006137/about – and click on the "source" tab.

**Comment by fsteeg** [comment]
Fixed in http://beta.lobid.org/hbz01 which is used in lobid production.

See: http://lobid.org/resource/CT003006137/about

Opened https://github.com/hbz/mabxml-elasticsearch/issues/14 for a separate hbz01 staging instance.

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See http://lobid.org/resource/CT003006137/about
