### ISSUE TITLE
short.field result format broken 

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid#252]
See http://lobid.org/resource?id=HT002189125&format=short.fulltextOnline (sample link from doc page).

**Comment by fsteeg** [comment]
Deployed to staging:

See http://test.lobid.org/resource?q=*&format=short.fulltextOnline (linked from http://test.lobid.org/api)

**Comment by acka47** [comment]
Why are there only six results shown?

**Comment by fsteeg** [comment]
Default paging is 10 hits, not all have the specified field.

**Comment by dr0i** [comment]
But there is a wildcard query, must result in lot of hits. Why are then not shown the first 10 of them?

**Comment by fsteeg** [comment]
That's the behavior we've always had: the result set (here: 10 hits) is filtered for the requested field. Yes, not very intuitive, and perhaps something we should change, but a different issue than this bug, which results in an exception in production.

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See http://lobid.org/resource?q=*&format=short.fulltextOnline
