### ISSUE TITLE
Embed JSON-LD in HTML with <script> tag and remove RDFa

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#256]
Currently, the JSON-LD is also part of the HTML in lobid.org. I suggest, simultaneously publishing it within the `<script type="application/ld+json">` tag and removing the buggy RDFa. What do you think?

**Comment by fsteeg** [comment]
+1

**Comment by akuckartz** [comment]
Non-buggy JSON-LD is better than buggy RDFa.

**Comment by acka47** [comment]
We should best embed schema.org JSON-LD, see also https://github.com/hbz/nwbib/issues/99.

**Comment by acka47** [comment]
Won't fix in API 1.0. The upcoming version (http://lobid.org/resources) will get some embedded schema.org JSON-LD (from the start or later, see https://github.com/hbz/lobid-resources-web/issues/25#issuecomment-274093946). It already supports content negotiation for `application/json+ld` and `application/json` from the start. Closing.
