### ISSUE TITLE
Update data dump information

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#257]
Currently it reads on the [lobid about page](http://lobid.org/about):

> The /resource and /item endpoints provide access to data from the hbz union catalogue that is published under CC0. The data is updated on a daily basis. See the data hub for downloading a base dump and updates: [Raw data export in rdfmab](http://datahub.io/dataset/hbz_unioncatalog), [lobid RDF](http://datahub.io/dataset/lobid-resources).

As far as I know, we don't provide rdfmab anymore, or do we @dr0i ? We should adjust this accordingly. Also, it might make sense to link to http://lobid.org/api#pagination+limits+bulk-downloads for downloading bulk data.

**Comment by dr0i** [comment]
+1

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
