### ISSUE TITLE
Trailing slashes in URLs result in "Action not found"

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#259]
Reported by @nichtich via mail on 2015-10-28.

Examples:

- http://lobid.org/nwbib/ 
- http://lobid.org/api/ 
- http://lobid.org/about/

**Comment by fsteeg** [comment]
Deployed to staging, see:

- http://test.lobid.org/nwbib/
- http://test.lobid.org/api/
- http://test.lobid.org/about/

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing.

See:

- http://lobid.org/nwbib/
- http://lobid.org/api/
- http://lobid.org/about/
