### ISSUE TITLE
Bibo:doi is not searched when doing an idQuery

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#262]
`bibo:doi` is not searched doing an ID query.

**Comment by dr0i** [comment]
Deployed to staging, test e.g. http://api.test.lobid.org/resource?id=10.1007/978-1-4020-8389-1.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.

**Comment by dr0i** [comment]
Upd -sorry, not deployed yet. Just switched the index.

**Comment by dr0i** [comment]
Deployed to production, closing.
