### ISSUE TITLE
The person (http://d-nb.info/gnd/110200136) not found in index

### ISSUE THREAD

**Issue by PaulBorchert** [hbz/lobid#263]
The Person Schödlbauer, Ulrich (http://d-nb.info/gnd/110200136) isn't listed in the autocompletion resultlist.(search for Schödlbauer, Ulrich). Only as a subject he's listed.

http://lobid.org/person?callback=jQuery1102008634846928990614_1446470408287&name=Sch%C3%B6dlbauer%2C+Ulrich&format=ids&_=1446470408288

**Comment by dr0i** [comment]
Hm. It's even not found doing a person search using the ID (http://lobid.org/person?id=110200136) but it's there doing a subject ID search (http://lobid.org/subject?id=110200136).

**Comment by dr0i** [comment]
The person is not of type `http://d-nb.info/standards/elementset/gnd#Person` but only of the more specific type `http://d-nb.info/standards/elementset/gnd#DifferentiatedPerson`. Seems to be an inferecing problem, again (is this generaslly broken? Will investigate).

**Comment by dr0i** [comment]
Seems not to be a general issue, e.g. http://lobid.org/person?id=118580604 works fine. @acka47 or have I missed something obviously? At the moment I don't understand why inferencing seems to work sometimes, and sometimes not. You hav a clue?

**Comment by acka47** [comment]
I took a look at this and also think there is the same underlying issue with the inferencing as for #84. Generally, resources with `gndo:DifferentiatedPerson` also have the type `gndo:Person`, see e.g. http://lobid.org/person?id=118696432. 

Note, that _no inferencing at all_ is done for http://lobid.org/subject?id=110200136. Also, the generic type `gndo:AuthorityResource` is missing as well as the generic `preferredName` property.
_But_ this not the case for the examples in #84 where all of them are missing the`preferredName` but two of three have enriched types from the inferencing.

It's hard to detect a pattern in these errors. We will have to take a deeper look at the inferencing or just try out another library or so for inferencing.

**Comment by yagee-de** [comment]
http://d-nb.info/gnd/113818122 is also currently not found

**Comment by dr0i** [comment]
Tanks for the report.
The bug is known. A workaround is to to use the subject endpoint of the API, like:
http://lobid.org/subject?id=113818122

**Comment by fsteeg** [comment]
Fixed in our new GND service, closing. See:

http://lobid.org/gnd/search?q=Sch%C3%B6dlbauer%2C+Ulrich
http://lobid.org/gnd/search?q=K%C3%B6nig-Ries%2C+Birgitta
