### ISSUE TITLE
PreferredNameForThePerson occurs where not expected

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#267]
For example http://test.lobid.org/resource?id=HT018312899&format=full problem with work title - shouldn't have preferredNameForThePerson:

```javascript
{
"@id": "http://d-nb.info/gnd/7683386-0",
"preferredName": "Grabbe, Christian Dietrich: Der Cid",
"preferredNameForThePerson": "Grabbe, Christian Dietrich: Der Cid",
"preferredNameForTheWork": "Grabbe, Christian Dietrich: Der Cid"}
}
```

See also https://github.com/hbz/lobid/issues/144#issuecomment-105980315

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
