### ISSUE TITLE
Missing 200b in HT018803762

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#269]
The [catalog resource for HT018803762](http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DHT018803762) contains
```200b |e Symposium zum Thema Erhaltung und nachhaltige Nutzung genetischer Ressourcen von Zierpflanzen - weitere Schritte zum Ausbau der Deutschen Genbank Zierpflanzen |d 2009 |c Bonn |9 HG00148342```

This seems to be not available at the corresponding lobid resource
http://lobid.org/resource/HT018803762/about

**Comment by acka47** [comment]
It looks like this is a corporate body without GND ID. Obviously, we don't include them into lobid until now.

Possible solutions:

1. ZB MED cataloguers at this event to GND
2. We add a rule to the morph that we will have corporate bodies without GND in the data as we do for persons (see #154).

**Comment by acka47** [comment]
Further discussion moved for now to internal JIRA system: https://jira.hbz-nrw.de/browse/FRL-100

**Comment by acka47** [comment]
As far as I can see, the content of subfield `e` isn't part of the RDF.

Source:

```xml
<datafield ind2="1" ind1="b" tag="200">
            <subfield code="e">
              Symposium zum Thema Erhaltung und nachhaltige Nutzung genetischer Ressourcen von Zierpflanzen - weitere Schritte zum Ausbau der Deutschen Genbank Zierpflanzen
            </subfield>
            <subfield code="d">2009</subfield>
            <subfield code="c">Bonn</subfield>
            <subfield code="9">(DE-588)1079071148</subfield>
</datafield>
``` 

JSON:

```javascript
{
    "@id" : "http://d-nb.info/gnd/1079071148",
    "preferredName" : "2009, Bonn"
  }
```

@jschnasse I wonder why FRL stakeholders didn't complain about this...

**Comment by acka47** [comment]
This was fixed by adding a GND ID to the corporate body, see also https://jira.hbz-nrw.de/browse/FRL-100. Closing. For adding names of corporate bodies without GND ID to the RDF we have #302 .
