### ISSUE TITLE
Missing field MAB 405

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#286]
http://lobid.org/resource/HT016689928/about?format=source

**Comment by acka47** [comment]
From the [MAB documentation](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mabTitelBibliographischeDaten2001.txt?__blob=publicationFile):

```
 405       ERSCHEINUNGSVERLAUF

         Indikator:
          blank = nicht definiert
```

**Comment by acka47** [comment]
This issue might made superfluous by hbz/lobid-resources#59 that is about MAB 406 and controlled values for "Erscheinungsverlauf".

**Comment by ChristophEwertowski** [comment]
405 (Erscheinungsverlauf) contains non-controlled values. Also 523 (Angaben über Erscheinungsweise und Erscheinungsdauer), which is currently used. In case of unregulary published works it could be really useful to know when which volumes/issues were published ([example, compare fields 405/425a (Erscheinungsjahr in Ansetzungsform)](http://lobid.org/resource/HT012143009/about?format=source)). Maybe combine 405 with the new *Notiz* [(issue)](https://github.com/hbz/lobid-resources/issues/167)?

**Comment by acka47** [comment]
What about also writing 405 into http://rdaregistry.info/Elements/u/P60538, like we do for 523?

**Comment by ChristophEwertowski** [comment]
Erscheinungsverlauf ≠ Erscheinungsweise. 
Erscheinungsweise = frequent or unregulary.
Erscheinungsverlauf = When did the volumes/issues appear? Are there breaks in publication, new countings (neue Folge), was a volume number skipped, did a volume appear before expected, is the Berichtsjahr different from the publication year? Examples:
* 2000 - 2004
* 2000 -
* 1.2000 - 5.2004
* 1.2000 ; 3.2001 ; 2.2002 (volume 3 appear earlier than vol. 2)
* 1.2000 - 5.2004 ; 7.2005 (volume 6 wasn't cataloged or didn't appear)
* 1.2000 - 5.2004,5 (published until volume 5, issue 5)
* 1905(1909) (Berichtsjahr 1905, published 1909)
See also [ZDB](http://www.zeitschriftendatenbank.de/erschliessung/arbeitsunterlagen/zeta/4025/), short paragraph "Inhalt und Aufbau".
So, you can see that it is unique content which we can't combine with a frequency. Mostly you can conclude a frequency but that's not always the case.

**Comment by acka47** [comment]
So we basically have to change the property used for 523 "ngaben über Erscheinungsweise und Erscheinungsdauer" as the current one (http://rdaregistry.info/Elements/u/P60538) is defined as:

> Relates a resource to an interval at which an issue or part of a serial or an update to an integrating resource is issued.

Furthermore, we have to think about whether we should somehow ad 405 to the same property or add another one.

**Comment by ChristophEwertowski** [comment]
As we now take bibframe/note for MAB 523 we could also put MAB 405 in it.

**Comment by acka47** [comment]
It was now also requested by S.S. to add the "Erscheinungsverlauf" note to lobid RDF (in MARC, this is field 362). Shen provides the following examples: http://ld.zdb-services.de/resource/2256606-5, http://ld.zdb-services.de/resource/2751608-8, http://ld.zdb-services.de/resource/2020230-1

So I picked up the work on this. Looking for a property, I did not find anything in Bibframe but the RDA property [rdau:P60135](http://rdaregistry.info/Elements/u/P60135) ("has note on numbering of sequence") looks promising. Alas, the description is not so easy to grasp so I am not sure whether it really is the right pick:

> Relates a resource to a note providing information on the range of designators that is used to indicate a sequence of the individual parts or iterations of a resource.

@cklee, have you already dealt with this question and can you tell me whether we can move forward with rdau:P60135 or should rather create a new property?

**Comment by cKlee** [comment]
In [ECPO](http://cklee.github.io/ecpo/ecpo.html#dccoverage) I chosen `dc:coverage` for the transport of the whole source description of a chronology. In your case you want to add a note to a `PublicationEvent`, right? The unconstrained property ["has note on numbering of sequence"](http://www.rdaregistry.info/Elements/u/#P60135) seems a little to narrow for this purpose. You can likewise use http://www.rdaregistry.info/Elements/u/#P60470 or http://www.rdaregistry.info/Elements/u/#P60131 for this purpose.

Actually MARC 362 is not a note nor a comment but the 'raw' data on which MARC 363 is based. MARC 362 serves as data for human, not for machine consumption. Maybe this makes the decision for the property more easy?

**Comment by acka47** [comment]
Thanks for the helpful hints, @cKlee. I will think about how to proceed.

**Comment by acka47** [comment]
Following up on this, my preference is to just add this information to the `bf:note` field where we already have MARC 515/MAB 523. Will ask S.S. about it.

**Comment by acka47** [comment]
I propose to insert 405 _before_ 523 in the note field. Regarding the examples provided by LBZ this would mean:

### [HT014891169](https://lobid.org/resources/HT014891169)

#### Before 

```json
{
   "publication":[
      {
         "type":[
            "PublicationEvent"
         ],
         "frequency":[
            {
               "id":"http://marc21rdf.info/terms/continuingfre#g",
               "label":"alle zwei Jahre"
            }
         ],
         "note":"Ersch. zweijährl.",
         "endDate":"2006",
         "location":"Koblenz",
         "publishedBy":"Landesamt für Vermessung und Geobasisinformation",
         "startDate":"2004"
      }
   ]
}
```

#### After

```json
{
   "publication":[
      {
         "type":[
            "PublicationEvent"
         ],
         "frequency":[
            {
               "id":"http://marc21rdf.info/terms/continuingfre#g",
               "label":"alle zwei Jahre"
            }
         ],
         "note":"Ausg. 2004 - 2006; damit Ersch. eingest.; Ersch. zweijährl.",
         "endDate":"2006",
         "location":"Koblenz",
         "publishedBy":"Landesamt für Vermessung und Geobasisinformation",
         "startDate":"2004"
      }
   ]
}
```

### [HT018138773](https://lobid.org/resources/HT018138773)

#### Before

```json
{
   "publication":[
      {
         "type":[
            "SecondaryPublicationEvent"
         ],
         "description":[
            "München : Münchener Digitalisierungszentrum, 2008-2013",
            "Digital. Ausg."
         ],
         "location":"München",
         "publishedBy":"Münchener Digitalisierungszentrum",
         "startDate":"2008"
      },
      {
         "type":[
            "PublicationEvent"
         ],
         "frequency":[
            {
               "id":"http://marc21rdf.info/terms/continuingfre#a",
               "label":"jährlich"
            }
         ],
         "note":"Repr. mit eigener zusätzlicher Bd.-Zählung",
         "endDate":"1895",
         "location":[
            "Wiesbaden",
            "Frankfurt, M.",
            "Altenburg"
         ],
         "startDate":"1846"
      }
   ]
}
```

#### After

```json
{
   "publication":[
      {
         "type":[
            "SecondaryPublicationEvent"
         ],
         "description":[
            "München : Münchener Digitalisierungszentrum, 2008-2013",
            "Digital. Ausg."
         ],
         "location":"München",
         "publishedBy":"Münchener Digitalisierungszentrum",
         "startDate":"2008"
      },
      {
         "type":[
            "PublicationEvent"
         ],
         "frequency":[
            {
               "id":"http://marc21rdf.info/terms/continuingfre#a",
               "label":"jährlich"
            }
         ],
         "note":"Urheberrechtsfreie Bände digitalisiert oder im Digitalisierungsprozess 1847 - 1895 = Jg. 2-50; Repr. mit eigener zusätzlicher Bd.-Zählung",
         "endDate":"1895",
         "location":[
            "Wiesbaden",
            "Frankfurt, M.",
            "Altenburg"
         ],
         "startDate":"1846"
      }
   ]
}
```

### [HT013006372](https://lobid.org/resources/HT013006372)

#### Before

```json
{
   "publication":[
      {
         "type":[
            "PublicationEvent"
         ],
         "frequency":[
            {
               "id":"http://marc21rdf.info/terms/continuingfre#g",
               "label":"alle zwei Jahre"
            }
         ],
         "endDate":"2008",
         "location":"Mainz",
         "publishedBy":"Rheinland-Pfalz",
         "startDate":"2000"
      }
   ]
}
```

#### After

```json
{
   "publication":[
      {
         "type":[
            "PublicationEvent"
         ],
         "frequency":[
            {
               "id":"http://marc21rdf.info/terms/continuingfre#g",
               "label":"alle zwei Jahre"
            }
         ],
         "note": "2000/01 - 2002/03; 2005/06 - 2007/08",
         "endDate":"2008",
         "location":"Mainz",
         "publishedBy":"Rheinland-Pfalz",
         "startDate":"2000"
      }
   ]
}
```

**Comment by acka47** [comment]
As this issue was triggered by LBZ, I asked them about the `bf:bote` approach. They prefer having the information in a separate field. Will think about possible solutions.

**Comment by acka47** [comment]
Looking around again, I found [rdau:P60491 "has history of resource"](http://rdaregistry.info/Elements/u/P60491) with description text "Relates a resource to a summary of information about the history of a resource." I think this would work well for MAB 405 / MARC 362. What do you think, @cKlee?

**Comment by cKlee** [comment]
We are going to use [rdau:P60128](http://www.rdaregistry.info/Elements/u/#P60128) ("has note on publication statement") in our Service soon. But P60491 looks fine too. Semantics are not clear for both anyway.

**Comment by acka47** [comment]
Thanks, @cKlee. As we already have a `note` field in the `PublicationEvent` object, we will use [rdau:P60491 "has history of resource"](http://rdaregistry.info/Elements/u/P60491) instead of having to notes on publication...

**Comment by acka47** [comment]
@dr0i, I suggest to name the JSON key "publicationHistory" and, thus, to add the following to the JSON-LD context:

```json
{
   "publicationHistory":{
      "@id":"http://rdaregistry.info/Elements/u/P60491"
   }
}
```

**Comment by acka47** [comment]
As this is deployed on staging, I made a functional review. Everything looks as requested except one thing: `publicationHistory`is not (yet?) in the context, neither at http://stage.lobid.org/resources/context.jsonld nor at http://lobid.org/resources/context.jsonld

**Comment by dr0i** [comment]
As discussed offline, the context is only deployed for production by redeploying the web app.
The only source to validate the context is to look in the provided context.json of the PR.

Deployed to production (merging the branch, switching the alias, restarted the web app).
Now the `publicationHistory`  is in the context at lobid.org.
Closing.

**Comment by acka47** [comment]
I just informed LBZ – who requested this addition to the data – about the change.
