### ISSUE TITLE
Plan creation of docs for lobid API

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#288]
Several people have asked for documentation of the lobid APIs, the data structure and the field mapping from source data to the JSON provided by the API. With API 2.0 we will finally have to create docs for all of these. Questions for docs creation:
- Until when do we need what documentation?
- How will we write, publish and update the docs?
- Who is responsible for what?

**Comment by acka47** [comment]
Does anyone have experience with https://readthedocs.org/? This might be a good way of providing docs...

**Comment by fsteeg** [comment]
I don't have experience with  https://readthedocs.org/, but I don't think we need to (or should) use an external service for this. I'd imagine simple markup files (Textile or Markdown) checked into the repo(s). These can be viewed directly in the repo, or converted to HTML to be published elsewhere.

**Comment by acka47** [comment]
You are right. I thought you could host your own readthedocs but in fact you can't...

**Comment by acka47** [comment]
> - How will we write, publish and update the docs?

Some days ago, I discussed with @jschnasse how one should document the transformation from MAB to JSON-LD. We came to the conclusion that an example-centered approach might be best and had the following idea:
1. Implement detail view from NWBib for lobid with some design adjustments (e.g. hbz coloring)
2. Choose 3-5 examples from our test cases to cover most resource types (monograph, journal, article, online resource etc.), isPart/hasPart relations etc.
3. Annotate the test cases with hypothes.is
   - Each key to indicate which RDF property is used
   - Each value to show from which part of the MAB source it comes from and which part of the morph is relevant for its transformatio
4. Publish a page with a description pf our documentation approach by example and a link to the examples.
5. If fields/questions by customers are not covered add more annotated example resources.

**Comment by ChristophEwertowski** [comment]
Documentation of field mapping started: Done for the MAB2 fields which are omitted in RDA. See https://github.com/hbz/lobid/issues/161#issuecomment-272420198.
For the documentation of the MAB2 fields look at [Tabelle MAB deutsch-englisch Stand: 11. April 2006](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mabTabelleDeutschEnglisch2006.pdf?__blob=publicationFile) and [Table section "control fields"](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mab2FormatSatzkennungSegment000Nov2001.txt?__blob=publicationFile).

**Comment by ChristophEwertowski** [comment]
Created two tables where every MAB2 field and it's transformation are listed. See [commit to branch 288](https://github.com/hbz/lobid/blob/e3244abc9afd40f91594ea5b148e9112cdbe58f9/documentationMAB2ToRDF.md) at the lobid repo. The first is the table for MAB2 fields which are omitted in RDA, the second table contains the rest of the fields.
@acka47 We should look over it to see if it's good enough to annotate example files for the documentation.

**Comment by ChristophEwertowski** [comment]
What I'm missing is the answer to the question: Who is responsible for what? 
My suggestion is that I'm responsible for everything field related and @fsteeg for everything query related. Did I miss another documentation field?

Also there is a markup file which I created which lists the MAB2 fields and their transformation. At the moment it's located only at an [old branch](https://github.com/hbz/lobid/blob/e3244abc9afd40f91594ea5b148e9112cdbe58f9/documentationMAB2ToRDF.md). It could be of interest for librarians which fields are transformed to what json object (especially if it grows to an official product). I would set it up at the lobid-resources repository, update it while I'm working at data transformation issues and looking once a week for data transformations of other team members.

**Comment by ChristophEwertowski** [comment]
Updated and added the old field transformation table form January at https://github.com/hbz/lobid-resources/blob/288-updateDocumentation/src/main/resources/documentationMAB2ToRDF.md.

**Comment by acka47** [comment]
I suggest to continue having this file in the wiki under https://github.com/hbz/lobid-resources/wiki/Mapping-of-MAB2-on-RDA.

**Comment by acka47** [comment]
Also, I think as this exclusively addresses German librarians, we should write this in German.

**Comment by acka47** [comment]
BTW, here is a blog post about what to document: http://blog.lobid.org/2017/02/23/api-documentation-1.html
