### ISSUE TITLE
Bring API 2.0 index data to /resources - as linked data

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#289]
Yesterday I noticed that API 2.0 will coin totally new URIs using http://lobid.org/resources instead of http://lobid.org/resource . What I like to suggest is to make the new URIs work for requests with ``GET accept: application/json`` this can be done immediately with a simple apache rewrite something like

`` /resources/$1   http://gaia.hbz-nrw.de:9200/resources/_all/$1/_source``

should do the trick. The advantage would be (hopefully), that sameAs links (e.g. ZDB vs. HT) in the current 2.0 index can be used directly without any postprocessing. Also it would provide the new index  as linked data.

**Comment by dr0i** [comment]
Thx, this is a nice low hanging fruit, yummy :) . Enjoy e.g. http://lobid.org/resources/HT013304490.

But:
- lobid-ZDB links are not working right now, see #292.

- Also, what is with our `items` endpoint - you provided a rewrite that would e.g. work with http://gaia.hbz-nrw.de:9200/resources/HT012926727:DE-38:28A2398 (which is not working, opened the issue #293), but it should better be http://gaia.hbz-nrw.de:9200/items/HT012926727:DE-38:28A2398.

**Comment by dr0i** [comment]
@jschnasse besides the two issues that have arised from this ticket, are you comfortable with the solution?

**Comment by fsteeg** [comment]
The rewrite from http://lobid.org/resources/HT013304490 seems to got to:

http://gaia.hbz-nrw.de:9200/resources/resource/HT013304490

instead of:

http://gaia.hbz-nrw.de:9200/resources/resource/HT013304490/_source

**Comment by dr0i** [comment]
Fixed. Using 

    RewriteRule ^/resources/(.*) http://gaia.hbz-nrw.de:9200/resources/_all/$1/_source [P]

**Comment by jschnasse** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
