### ISSUE TITLE
Reproduce getting hbz01 XML clob from Aleph

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#29]

**Comment by dr0i** [comment]
Copied program to `aither:/home/lod/hbz-aleph-indexer/`and started the script `bin/hbz-aleph-daily-update.sh` which results in getting the updates :) .

**Comment by dr0i** [comment]
Docu about getting the XML-Clobs (both sites restricted to hbz internal access only) :
https://wiki.hbz-nrw.de/display/~schnasse/Suchmaschine+-+Alephexport
https://wiki.hbz-nrw.de/display/SMS/Darstellung+des+Gesamtabzugs+der+hbz-Titeldaten
