### ISSUE TITLE
lobid-ZDB sameAs links are not working

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#292]
The sameAs links residing in lobid resources, see e.g. http://lobid.org/resources/ZDB1257-9 coming from http://lobid.org/resources/HT015082724, are not working. ZDB records are not extracted and not indexed .

Should we forget them alltogether? They don't serve any purpose anymore since the LOD zdb-services exists (e.g. http://ld.zdb-services.de/resource/1257-9), therefore: any ZDB id has its own URI. 
But we would break our cool URI promise if we remove them permanently.

**Comment by acka47** [comment]
Please get rid of them. It only caused a lot of problems for us and I never heard that anybody uses the URIs that are based on the ZDB ID. We minted the URIs in 2011, see this post: https://wiki1.hbz-nrw.de/display/SEM/HTTP+URIs+with+ZDB-IDs All the behaviour we described there does not work anymore and nobody cares. I believe API 2.0 is the right time to get rid of ZDB-ID-based URIs alltogether.

As we at some point will have to announce all the changes that are coming with API 2.0, I started a [wiki page](https://github.com/hbz/lobid-resources/wiki/Changes-in-API-2.0) to collect them. Please also add changes you encounter.

P.S.: Shouldn't this issue be in lobid-resources?

**Comment by dr0i** [comment]
> P.S.: Shouldn't this issue be in lobid-resources?

Yes, would be better. But as there is no way to move issues to other repos in github I will it here.

**Comment by dr0i** [comment]
Deployed to staging, see http://lobid.org/resources-staging/HT001373475.

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
As discussed with ZDB colleagues via email in November 2016, we will redirect ZDB URIs to their corresponding http://ld.zdb-services.de/resource/ URI. ZDB itself will remove links to lobid from their RDF.
