### ISSUE TITLE
Api 2.0: Cannot lookup item URIs

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#293]
Item URIs, e.g. "http://lobid.org/item/HT012926727:DE-38:28A2398" taken from http://gaia.hbz-nrw.de:9200/resources/item/_search?q=HT012926727 , cannot be lookuped, e.g. http://gaia.hbz-nrw.de:9200/resources/item/HT012926727:DE-38:28A2398.

**Comment by dr0i** [comment]
Note: some URIs are working fine, e.g. http://gaia.hbz-nrw.de:9200/resources/item/HT012926727:DE-61-81:jurj354.m946.

**Comment by dr0i** [comment]
Updated the /etc/apache2/vhosts.d/lobid.org.conf@emphytos:
       
     AllowEncodedSlashes On
     RewriteRule ^/items/(.*)/(.*) http://lobid.org/items/$1\%2F$2 [P,N]
     RewriteRule ^/items/(.*)\ (.*) http://lobid.org/items/$1\%20$2 [P,N]
     RewriteRule ^/items/(.*?):(.*) http://quaoar1.hbz-nrw.de:9200/resources/item/$1:$2/_source?parent=$1 [P]

As long as we have an outdated apache server (<2.2.18) it is not possible to use `AllowEncodedSlashes NoDecode`, which would allow to not define the firstmentioned two regex' (which are a workaround). The `NoDecode` directive would URLs not be decoded but would pass-through them to the server.
I asked our IT if they can update apache.

**Comment by dr0i** [comment]
Deployed minimal test set. Try e.g.:
http://lobid.org/items/HT012926727:DE-61-81:jurj354.m946
http://lobid.org/items/HT012926727:DE-38:28A2398
With a slash and a space:
http://lobid.org/items/TT001671747:DE-290:GOA%207%2F62-3,5,1#!
Even with multiple slashes and spaces:
http://lobid.org/items/HT018786244:DE-1156:Sbh%2010%20%2F%20For%201%20%2F%20133#!

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
