### ISSUE TITLE
Strange dct:creator on HT018889713

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#295]
http://lobid.org/resource/HT018889713/about 

data at dct:createl looks wrong to me. If taken directly from gnd it  is something like

Fachtagung der BZgA <2015, Essen>

at lobid it is

2015,Essen

**Comment by acka47** [comment]
Similar to https://github.com/hbz/lobid-resources/issues/37 which is about the same subfield (`e`) missing for corporate bodies as subjects. @dr0i, as you are currently working on this: Can you please also take into account corporate bodies as creators?

**Comment by dr0i** [comment]
@acka47 right! Deployed small test set, see e.g. http://lobid.org/resources-staging/HT018889713

**Comment by acka47** [comment]
Looks good. +1 for data 2.0. The thing is, that @jschnasse needs it in data 1.0...

**Comment by dr0i** [comment]
Deployed to staging, see e.g. http://staging.lobid.org/resource/HT018889713/about

**Comment by fsteeg** [comment]
Looks good in nwbib-staging too: http://test.nwbib.de/HT018889713

**Comment by acka47** [comment]
+1

**Comment by jschnasse** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
