### ISSUE TITLE
RDA - issue: get dc:publisher from MAB 419

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#296]
Bislang wurde an Unterordnungen das Feld 412 weitergegeben, so dass der dc:publisher auch an der Unterordnung belegt war.
Mit RDA wird dieselbe Information scheinbar in 419 abgelegt. Dies benötigen wir auch an den Unterordnungen.
Konkret:
In den Unterordnungen von HT018907246 benötigen wir die Info aus  
419 	|a [Köln] |b ZB MED - Leibniz Information Centre for Life Sciences |c [2016]

**Comment by jschnasse** [comment]
The field seems to be in mab source
http://lobid.org/resource/HT018907266/about?format=source

**Comment by dr0i** [comment]
Eine konkrete Unterordnung ist http://lobid.org/resources/HT018907266 , und da fehlt das auch. `Ind2="2"` ist unkonfiguriert, ich füge das jetzt hinzu und lasse den Index neu bauen. Sollte Morgen gegen max 10:00 fertig sein.

**Comment by dr0i** [comment]
@acka47 wir hatte uns drauf geeinigt nicht einfach Tickets aus ander Leuts `working` Spalte zu schnappen, siehe https://github.com/hbz/hbz.github.com/commit/f0b174eae65f17a72817931699ec079b5c907f4a .Dieberei!
Aber, wenn Du schon dabei bist: warum hast Du es Dir geschnappt, haste noch was?

**Comment by acka47** [comment]
> @acka47 wir hatte uns drauf geeinigt nicht einfach Tickets aus ander Leuts `working` Spalte zu schnappen, siehe https://github.com/hbz/hbz.github.com/commit/f0b174eae65f17a72817931699ec079b5c907f4a .Dieberei!

Sorry, ich dachte nur, dass sei meine Aufgabe, mich um die Ursache zu kümmern. Freu mich aber, dass du dich drum gekümmert hast. Ich mach dann einfach später das review...

**Comment by dr0i** [comment]
Gegen 10:00 Uhr wird's nicht fertig. Auf dem Server ist ein hoher load- die letzten 3% der Indexierung brauchen ca. 30% der Gesamtzeit. Ich schätze eher nach der Mittagspause.

**Comment by dr0i** [comment]
Depleoyed to staging.See e.g. http://staging.lobid.org/resource/HT018907266

**Comment by jschnasse** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production.

**Comment by dr0i** [comment]
Also deployed to staging for data 2.0.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
