### ISSUE TITLE
Add cookbook-style API documentation

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid#3]
Provide detailed, step-by-step instructions on how to use the lobid API for an app:
- Getting data from the API, with HTTP requests
- Processing the `short` and `ids` JSON format for autocomplete
- Processing the `full` JSON format, get data from specific fields

Provide sample code and projects implemented in Java (server) and JavaScript (client).

**Comment by acka47** [comment]
WOn't fix/partly fixed. Closing.
