### ISSUE TITLE
Include names of corporate bodies without GND ID

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#302]
http://lobid.org/resource/TT002234042
http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DTT002234042

http://lobid.org/resource/TT002234205
http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DTT002234205

http://lobid.org/resource/TT002234167
http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DTT002234167

http://lobid.org/resource/TT002234205
http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DTT002234205

**Comment by jschnasse** [comment]
seems all TT* ids are effected

**Comment by acka47** [comment]
These are all names of corporate bodies without GND IDs. Nonetheless, they should at least appear in the `nameOfContributingCorporateBody` field – which they don't do. They are not taken into account in data 2.0 as well, see e.g. http://lobid.org/resources/TT002234042

@jschnasse Would it be ok for you if we only resolved this in data 2.0? Or do you need it from the production API?

**Comment by jschnasse** [comment]
data 2.0 will be sufficient!

**Comment by acka47** [comment]
In the current 2.0 morph we don't take into account 200-1.a at all, see [lines 832-922](https://github.com/hbz/lobid-resources/blob/2823082f4879750418050e58c0679c9263cb43a0/src/main/resources/morph-hbz01-to-lobid.xml#L832-L922).

**Comment by acka47** [comment]
#154  is the corresponding ticket where we worked on adding persons without GND IDs into the RDF.

**Comment by acka47** [comment]
https://github.com/hbz/lobid-rdf-to-json/issues/17 is the corresponding ticket for persons without GND ID in API 2.0.

**Comment by acka47** [comment]
As discussed offline, we will concatenate GND URIs (morph variable `@creatorCorporateBodyId` – if existing) and names of corporate bodies without GND ID (not existing in morph yet) in the same order as in source to the `contributorOrder` string whoch currently already holds person IDs and names.

An example with person URIs and a string [HT018700720](http://lobid.org/resources/HT018700720) (snippet):

```
"contributorOrder": [
   "http://d-nb.info/gnd/136371671 | http://d-nb.info/gnd/129961604 | Ottovay, Kathrin | http://d-nb.info/gnd/115325859 | http://d-nb.info/gnd/2006655-7" ]
```

Regarding persons, the relevant part of the current morph is in lines [1130-1134](https://github.com/hbz/lobid-resources/blob/872a13cdc4d76bb63ec79d2631b94e16c725ad5b/src/main/resources/morph-hbz01-to-lobid.xml#L1130-L1134).

For [TT002234205](http://lobid.org/resources/TT002234205) the missing part from the [source data](http://lobid.org/hbz01/TT002234205) looks like this:

```xml
<datafield tag="200" ind1="-" ind2="1">
  <subfield code="a">
Rheinland-Pfalz / Ministerium für Arbeit, Soziales, Familie und Gesundheit
  </subfield>
</datafield>
```

The result should look like this (snippet):

```json
{
   "id":"http://lobid.org/resources/TT002234205#!",
   "contributorOrder":[
      "Rheinland-Pfalz / Ministerium für Arbeit, Soziales, Familie und Gesundheit"
   ]
}
```

**Comment by fsteeg** [comment]
Deployed to small test set, see:

http://lobid.org/resources-small?q=hbzId:TT002234042
http://lobid.org/resources-small?q=hbzId:TT002234205
http://lobid.org/resources-small?q=hbzId:TT002234167

**Comment by acka47** [comment]
The PR implements currently implements what I wrote in https://github.com/hbz/lobid/issues/302#issuecomment-212873147 and will suffice for presentation purposes. As I wrote in https://github.com/hbz/lobid/issues/302#issuecomment-209889538, the strings are also missing in `contributingCorporateBodyLabel` which is used for querying – at least by NWBib. @jschnasse: Do you also search via the `contributingCorporateBodyLabel`? If yes, we would also have to add the string in there..

**Comment by jschnasse** [comment]
I use only contributorOrder from data 2.0. Testset looks fine for me.

**Comment by acka47** [comment]
+1 I forgot that nobody uses API 2.0 for searching anyway, thus we don't need no further adjustments here. (I don't know how many of these corporate bodies without GND ID exist and whether we should make them searchable. If yes, we would have to do it in production.)

**Comment by fsteeg** [comment]
Will be deployed as part of full index build over the weekend.

**Comment by fsteeg** [comment]
Deployment as part of weekly full indexing failed, see https://github.com/hbz/lobid/issues/304

**Comment by fsteeg** [comment]
Deployed to beta, closing. See:

http://lobid.org/resources/TT002234042
http://lobid.org/resources/TT002234205
http://lobid.org/resources/TT002234167

**Comment by dr0i** [comment]
The contributor was only added to the `contributorOrder` field. There was no `dc:contributor`. With hbz/lobid-resources#125 we get rid of `contributorOrder`. A contributor must be added to the the `contribution`-list.

**Comment by dr0i** [comment]
See http://lobid.org/resources/TT002234042 as an example (`Lierscheid`).

**Comment by dr0i** [comment]
Deployed to staging, see http://test.lobid.org/resources/TT002234042.

**Comment by acka47** [comment]
+1
