### ISSUE TITLE
Create value propositions/pitches for lobid

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#306]
We got feedback from people in the hbz library network that they don't get what lobid is actual about and what they can get from it. As we think, this could better be explained and communicated, we plan to have some kind of marketing workshop in July or latest September.

**Comment by acka47** [comment]
A similar issue for lobid-organisations already exists: https://github.com/hbz/lobid-map/issues/9

**Comment by akuckartz** [comment]
:+1:

**Comment by acka47** [comment]
Just stumbled over this. We are now working on this in the context of metadaten.nrw. Closing here
