### ISSUE TITLE
Set up tile server?

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#309]
As the tile server used for NWBib and lobid-organisations was discontinued without us being aware of it in advance (see hbz/nwbib#325 and hbz/lobid-organisations#234) we should think about measures to avoid something like this in the future. One obvious solution would be to set up a hbz-wide tile server. 

There were some thoughts in this direction within the world map project, see e.g. https://github.com/hbz/oerworldmap/issues/472. However, during a physical team meeting @philboeselager, @j0hj0h and @literarymachine came to the conclusion that we would need terabytes of memory for a tile server covering the whole world with all zoom levels. Thus, the plans were put on ice. 

Here are some links for setting up an OSM tile server: 
- Tile server requirements from https://switch2osm.org/serving-tiles/building-a-tile-server-from-packages/: 
  
  > If you want to import and render the whole world, you will need a considerably beefier server than a typical desktop. E.g. starting from about 24Gb of RAM upwards. It is also strongly recomend to use an SSD for the database or at least a fast RAID array. The full planet import is currently around about 256GB, so to store all of the DB on an SSD, you will likely need a 512GB SSD. An import that is not updated and uses the –drop option on the otherhand likely still fits on a 256GB SSD. You can also selectively put the most important parts of the database on an SSD and the rest on slower disks. Osm2pgsql supports using separate tablespaces for different parts of the database for this purpose.
- Some numbers from the OSM tile server: http://wiki.openstreetmap.org/wiki/Tile_disk_usage

**Comment by dr0i** [comment]
Just a note:
we now 2TB of SSD in every one of the 5 weywot's.

**Comment by dr0i** [comment]
IT proposed to set up a tileserver, at least for DACH region, and even to open it for library institutions.
We should really do this, e.g. beacuse of https://github.com/hbz/lobid-organisations/issues/430 .

**Comment by acka47** [comment]
I just noticed that DBS also recently enabled using a map to visualize DBS data, see https://www.hbz-nrw.de/aktuelles/nachrichten/bibliotheksstatistik-neues-werkzeug-zur-visualisierung-von-dbs-daten. They are currently using the OSM tile server. So there are definitely several products now using tile servers (home page, lobid-organisations, NWBib, DBS, OER World Map) and it would make sense to set up an hbz tile server.

**Comment by fsteeg** [comment]
>  So there are definitely several products now using tile servers (home page, lobid-organisations, NWBib, DBS, OER World Map)

lobid-gnd too, see https://lobid.org/gnd/4005728-8

And currently it seems to be broken for organisations, gnd, and nwbib.

**Comment by dr0i** [comment]
Hooray IT provides a tileserver, at least for europe and up to zoom level 17.
We can use it via lobid proxy.

- [ ] lobid-resources
- [ ] lobid-organisations (wikimedia tileserver working atm)
- [ ] lobid-gnd
- [ ] nwbib  (wikimedia tileserver working atm)

**Comment by dr0i** [comment]
>Hmm, the tiles have a dark style I havenÄt encountered before.
(https://github.com/hbz/lobid-resources/pull/1093#issuecomment-742596783)

Map style is https://opentopomap.org/about where it is said:
>Der Kartenstil orientiert sich an den amtlichen Karten und setzt auf gute Lesbarkeit 

It was choosen by IT. I think it's not really dark, but has good contrast, and since it seems to be orientated by official maps and guarantees good readability (which is a desiderat when it comes to be barrier free) I think we can go with it.

**Comment by dr0i** [comment]
In principal, this issue is solved. There remain questions, if you like:
1. only europe is available. Is this enough?
2. the style may be discussible
3. is the zoom level sufficient (I think it is)
...

**Comment by acka47** [comment]
> 1. only europe is available. Is this enough?

In GND (and even a bit in lobid-organisations) we have some places outside of Europe. See e.g. https://test.lobid.org/gnd/4064682-8. The continents are at lest there so it is not nothing. However, couldn't we add the rest of the world with much less detail but that at least the names of the bigger cities are displayed?

2. the style may be discussible

It's ok for me. We should move forward with this.

3. is the zoom level sufficient (I think it is)

Yes, i's definitely enough.

**Comment by dr0i** [comment]
I asked IT , they will decide how to go on, first comments seem to tend to not add world data :( .

**Comment by dr0i** [comment]
IT now willing to provide World Tiles :) See https://github.com/hbz/lobid/issues/436.

**Comment by dr0i** [comment]
This seems to be resolved, we have mapped the world to tiles.

**Comment by acka47** [comment]
+1
