### ISSUE TITLE
Set up repo for "digitalisiertedrucke"

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#311]
As discussed yesterdy, @fsteeg will soon start working on the digitalisierte drucke API and interface. The first step should be to create a new repo with the existing transformation code from https://github.com/lobid/lodmill/tree/master/lodmill-rd/transformations/zvdd.

**Comment by fsteeg** [comment]
Created a new repo, splitting out `lodmill-rd/transformations` from https://github.com/lobid/lodmill/ (see documentation at https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/):

https://github.com/hbz/digitalisiertedrucke

Next steps: set up a Play project in the repo, move over ZVDD tests from lodmill repo, set up CI.

**Comment by fsteeg** [comment]
Repo set up with Play project, original tests, CI, and custom project settings:

https://github.com/hbz/digitalisiertedrucke

Closing this, will continue with issues in new repo, starting with https://github.com/hbz/digitalisiertedrucke/issues/1.
