### ISSUE TITLE
Add content-media-carrier (CMC) information to RDF

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#317]
Sub-issue of #161.

- content: in MAB field 060, controlled values at https://www.loc.gov/standards/valuelist/rdacontent.html
- media: in MAB field 061, controlled values at https://www.loc.gov/standards/valuelist/rdamedia.html
- carrier: in MAB field 062, controlled values at https://www.loc.gov/standards/valuelist/rdacarrier.html

Example:

```xml
<datafield tag="060" ind1="-" ind2="1">
  <subfield code="b">txt</subfield>
  <subfield code="a">Text</subfield>
</datafield>
<datafield tag="061" ind1="-" ind2="1">
  <subfield code="b">n</subfield>
  <subfield code="a">ohne Hilfsmittel zu benutzen</subfield>
</datafield>
<datafield tag="062" ind1="-" ind2="1">
  <subfield code="b">nb</subfield>
  <subfield code="a">Blatt</subfield>
</datafield>
```

**Comment by dr0i** [comment]
Not exactly sure, but whenever it reads "MAB" I tend to think the natural repo for the issue must be hbz/lobid-resources.

**Comment by acka47** [comment]
Moved to https://github.com/hbz/lobid-resources/issues/115. Closing.
