### ISSUE TITLE
Take into account MAB field 531 in RDF transformation

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#319]
Request by edoweb stakeholders (edited for better readability):

>  ist es möglich, bei Zeitschriften die Kategorie für Titeländerungen anzuzeigen? Ein Beispiel, wo das wichtig sein könnte, ist [HT018885805](http://lobid.org/hbz01/HT018885805). Das wäre in MAB die Kategorie #531z. Geht das?

From the example:

``` xml
<datafield tag="531" ind1="z" ind2="1">
  <subfield code="p">Fortsetzung von</subfield>
  <subfield code="a">Elternarbeit in Rheinland-Pfalz</subfield>
  <subfield code="9">HT018885808</subfield>
</datafield>
```

Generally, field 531 is about "related entries" and predecessor/successor relations are only one kind of relationships, I assume. Thus, it is hard to capture this in RDF without loosing the special character of the relationshhip named in subfield `p` (here: "Fortsetzung von"). We could do something like this (example for API 2.0):

``` json
{
  "id" : "http://lobid.org/resources/HT018885805#!",
  "relationship": {
    "type": "Relationship",
    "relatedTo": "http://lobid.org/resources/HT018885808",
    "label": "Fortsetzung von"
  }
}
```

@jschnasse says he would also need this in API 1.0.

**Comment by acka47** [comment]
I just took a look at a subset to find out what values can be found in 531.z. Taking the following steps (see also https://wiki1.hbz-nrw.de/pages/viewpage.action?pageId=9867212):

- `/files/open_data/closed/hbzvk/snapshot$ for i in $(find  01852 -name "HT01852*.bz2"); do   printf $i ; bzcat $i | grep --color  -A 4 "<datafield tag=\"531\" ind1=\"z\" ind2=\".\"><subfield code=\"p\">"  ; done`
- select parts with regex `<datafield tag=\"531\" ind1=\"z\" ind2=\".\"><subfield code=\"p\">[^<]*`
- separate values and `sort  531values.txt | uniq -c`

Here is the result:

      1 4. Aufl. u.d.T.
      1 Als Vorg. gilt ---&gt;
      5 Darin aufgeg. ---&gt;
      7 Druckausg. u. Vorg. ---&gt;
      2 Früher u.d.T.
      4 Früher u.d. T.
      2 Hervorgeg. aus ---&gt;
      1 Vorg. als Druckausg. ---&gt;
     16 Vorg. ---&gt;
    103 Vorg.: ---&gt;

**Comment by acka47** [comment]
Another sample (or i in $(find 00449 -name "HT00449*.bz2")) gives the following results:

      1 2004 - 2011 Beil., dann darin aufgeg. ---&gt;
      1 2009 darin aufgeg. ---&gt;
      1 44.1995 - 45.1996 Beil., dann darin aufgeg. ---&gt;
      1 6. Aufl. u.d.T.
      1 Ab 1984 darin aufgeg. ---&gt;
      3 Bd. 1 u.d.T.
      1 Beil. u. darin aufgeg. ---&gt;
      1 Beil zu, dann darin aufgeg. ---&gt;
      3 Daraus hervorgeg. u. darin aufgeg. ---&gt;
      6 Darin aufgeg. ---&gt;
      1 Darin, später darin aufgeg. ---&gt;
      1 Praxisreihe u. darin aufgeg. ---&gt;
     82 Vorg. ---&gt;
     34 Vorg.: ---&gt;
      1 Vorg u. 23/24.1988 ---&gt;

Obviously, this field generally contains information about  predecessors, so we should actually use http://rdaregistry.info/Elements/u/P60683 to model this in JSON-LD:

```json
  "@context": {
    "hasPredecessor": {
      "@type": "@id",
      "@id": "http://rdaregistry.info/Elements/u/P60683"
    }
  }
  "id" : "http://lobid.org/resources/HT018885805#!",
  "hasPredecessor": {
    "id": "http://lobid.org/resources/HT018885808",
    "label": "Elternarbeit in Rheinland-Pfalz"
  }
}
```

**Comment by acka47** [comment]
Would the approach outlined in the previous comment work for you, @jschnasse ?

**Comment by acka47** [comment]
We might also add the info from subfield `p` as `rdfs:comment` or similar in the case edoweb stakeholders want to show this information.

```json
{
  "@context": {
    "hasPredecessor": {
      "@type": "@id",
      "@id": "http://rdaregistry.info/Elements/u/P60683"
    },
    "comment": "http://www.w3.org/2000/01/rdf-schema#comment"
  },
  "id" : "http://lobid.org/resources/HT018885805#!",
  "hasPredecessor": {
    "id": "http://lobid.org/resources/HT018885808",
    "label": "Elternarbeit in Rheinland-Pfalz",
    "comment": "Fortsetzung von"
  }
}
```

**Comment by ChristophEwertowski** [comment]
Predecessors and successors are already added. The contents of `531z1.p` or `533z1.p` aren't standardized and mostly don't contain additional information. Therefore I'm closing this issue.
