### ISSUE TITLE
Don't type resources with 051 s| | as Misc

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#320]
Reported by publisso stakeholders. Many publisso resources are typed as "Anderes"/Miscellaneous, see https://repository.publisso.de/resource?query%5B0%5D%5Bfacets%5D%5Brdftype%5D%5B0%5D=Anderes. For example http://lobid.org/hbz01/HT016988885. Many of these have an `s` in `051` at position `0`. From the example:

``` xml
<controlfield tag="051">s|||z|||</controlfield>
```

From the [MAB documentation](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mab2FormatSatzkennungSegment000Nov2001.txt?__blob=publicationFile):

```
051     VEROEFFENTLICHUNGSSPEZIFISCHE ANGABEN ZU BEGRENZTEN
        WERKEN

          Indikator:
          blank = nicht definiert

          Datenelemente:
            0  Erscheinungsform
               a = unselbstaendig erschienenes Werk
               f = Fortsetzung
               m = einbaendiges Werk - nicht Teil eines
                   Gesamtwerks
               n = mehrbaendiges begrenztes Werk - nicht Teil
                   eines Gesamtwerks
               s = einbaendiges Werk  u n d  Teil (mit
                   Stuecktitel) eines Gesamtwerks
               t = mehrbaendiges begrenztes Werk  u n d
                   Teil (mit Stuecktitel) eines Gesamtwerks
```

Proposal: As `s` stands for "einbändiges Werk" (monograph) we should also type it as `bibo:Book` (as we do with other monographs).

**Comment by ChristophEwertowski** [comment]
Resources with MAB 051.s are typed as books now and not miscellaneous ([example (production)](http://lobid.org/resources/HT018895767?format=json) / [example (test)](http://test.lobid.org/resources/HT018895767?format=json)). If there is already a publication type then it's added ([example (production)](http://lobid.org/resources/HT018700720?format=json) / [example (test)](http://test.lobid.org/resources/HT018700720?format=json)).

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closed.

**Comment by ChristophEwertowski** [comment]
An elinet customer reported that `051.s` should be only typed as book if the subtype isn't defined. Her examples were 051.s[kr]. Her example https://ellinet-dev.hbz-nrw.de/resource/frl:6019470 would be only a conference work and not a book (which is correct because from the bibliographic resource we only get that it's an electronic resource). We should expand the definition that a book can't be an electronic resource alone (050.level 8) / has to be a printing (050.a) or hand writing (050..a). @jschnasse : For your information.

**Comment by ChristophEwertowski** [comment]
Misunderstood the customer first while reading her comment, therefore no change is necessary. Wrote her an explanation about our mapping of publication types and sent her an link to our documentation.
