### ISSUE TITLE
Set up lobid blog with github pages and Jekyll

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#321]
Domain should probably be blog.lobid.org (back to the roots). Perhaps using octopress?

**Comment by fsteeg** [comment]
I've set up a Jekyll based blog in the lobid organisation's GitHub page: http://lobid.github.io

Posts are Markdown files that are published when pushed to GitHub, see:
https://github.com/lobid/lobid.github.com/blob/master/_posts/

About the `blog.lobid.org` setup: our idea was to set up a vhost on emphytos for that. Currently `blog.lobid.org` redirect to a Blogger blog. There is no vhost config for that on emphytos. Is that configured within Blogger? It seems we'd have to do something similar for GitHub, see [1]. I've tested a vhost setup at `weblog.lobid.org`, and while that does end up on GitHub, it yields a 404.

[1] https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by acka47** [comment]
> Currently `blog.lobid.org` redirect to a Blogger blog. There is no vhost config for that on emphytos. Is that configured within Blogger?

Yes, and we set a CNAME in the DNS settings.

**Comment by acka47** [comment]
Just talked @fsteeg about also setting up a sub-domain and CNAME for slides.lobid.org to host the repo https://github.com/hbz/slides.

**Comment by acka47** [comment]
I set the CNAMEs both for blog.lobid.org and slides.lobid.org. Let's see what happens.

**Comment by acka47** [comment]
Looks good now both for http://blog.lobid.org/ and http://slides.lobid.org/ .

**Comment by acka47** [comment]
GitHub pages for https://github.com/hbz/slides is now published via the mater branch. (Though it wasn't so easy to switch that as gh-pages and master branch didn't have a common git history...)

**Comment by fsteeg** [comment]
Cool. Then this is done, right?
