### ISSUE TITLE
Missing HT-Resources

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#322]
http://lobid.org/resource/HT019239207
http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DHT019239207
http://lobid.org/resource/HT019239326
http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DHT019239326
http://lobid.org/resource/HT019239190
http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DHT019239190
http://lobid.org/resource/HT019241015
http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DHT019241015

**Comment by acka47** [comment]
All are there in API 2.0, see e.g. http://lobid.org/resources/HT019239207

**Comment by dr0i** [comment]
Don't comprehend yet what has gone wrong. Did a grep on all update Clobs (see http://lobid.org/download/dumps/DE-605/mabxml/) but couldn't find it there. So it should be in the big `baseline` dump. Looking at the logs of that indexing process I see nothing unusual.
The first three resources reside in the old index ,though, see e.g. http://test.lobid.org/resource/HT019239207/about . Justl updated that older index switched back to it.
Waiting for weekends new indexing - maybe then it's cured on itself.
But I don't think so => further investigation.

**Comment by dr0i** [comment]
Checked if the resource can be transformed and indexed - yes, it can! Hm, hm. So - weekend!

**Comment by acka47** [comment]
Three of the four resources are now transformed and index. One is still missing: http://lobid.org/resource/HT019241015/about

**Comment by dr0i** [comment]
> All are there in API 2.0

this is true because this index was an _old_, unswitched one.
In all _newer_ indexes  >2017-02-12 these documents are missing.
As the indexing test above shows there is no principal problem with transforming and indexing the MabXmlClobs I assume that the resources are missing in the basedump. To investigate this I await the the result of:

`tar xfz  /files/open_data/open/DE-605/mabxml/DE-605-aleph-baseline-marcxchange-2017022510.tar.gz --ignore-command-error  --to-command='grep "HT019239207\|HT019239190\|HT019241015\|HT019239326"'`

**Comment by dr0i** [comment]
The command above had nothing showed up. There is a way faster command IF you now the aleph-ID (which I happen to know), try :
`nohup tar -ztvf /files/open_data/open/DE-605/mabxml/DE-605-aleph-baseline-marcxchange-2017030410.tar.gz  | grep 000805561 > grep_000805561_baseline.txt &`
You can get the aleph-ID by looking at the MabXmlClobs:
`http://lobid.org/hbz01/HT002189125`
You can also look at the other hbz-index:
`https://index.hbz-nrw.de/_es2/hbz/_search?q=HT00218912`
Conclusion:
The resource is missing in our MabXmlClobs source dump. But it doesn't seems to be missing at the source dump used by the other index. For this I have to grep at the other source dump (I don't have access to it yet).

**Comment by dr0i** [comment]
Increasing parameter `max` of the dumping-script will resolve the issue. It was set to `21500000` whilst e.g. `HT019239207` has a slightly greater number `"<identifier>aleph-publish:021502302</identifier>"`. Thx @jprante for the hint!

**Comment by dr0i** [comment]
Missing documents back again.
Please have a look @jschnasse.

**Comment by jschnasse** [comment]
thx!
