### ISSUE TITLE
Set up new landing page for lobid.org

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid#323]
Linking to the new resources and organisations services

Moved from https://github.com/hbz/lobid-resources/issues/280

**Comment by fsteeg** [comment]
Deployed to staging, see: http://stage.lobid.org/

**Comment by fsteeg** [comment]
Redeployed with changes discussed offline: http://stage.lobid.org/

**Comment by ChristophEwertowski** [comment]
+1

**Comment by acka47** [comment]
+1
