### ISSUE TITLE
Add "deprecated" note to old API version

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#326]
Especially at http://lobid.org/api.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://stage.lobid.org/api

**Comment by acka47** [comment]
For a start, this message is ok (+1). Current API users might be confused seeing this. We should communicate a concrete date when the API will be discontinued and provide some information on the transition process. This probably is a a topic for our Thursday meeting (thinking about this, we might add a label "discuss" or so to identify topics for the in-person discussions).
