### ISSUE TITLE
Decide and document consistent license

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid#338]
We have different licenses inconsistently attached to our repos and source code (EPL, GPL, Affero). We should decide on a consistent approach and update the documentation and source code headers.

**Comment by fsteeg** [comment]
Decided in offline discussion to use EPL. Will add LICENSE files to the repos.

**Comment by dr0i** [comment]
- [x] Lobid-resources relicensed.

**Comment by fsteeg** [comment]
All LICENSE files set up, headers updated, set license for Zenodo snapshots. Closing.
