### ISSUE TITLE
Add German version of lobid home page

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#340]
https://lobid.org/

**Comment by acka47** [comment]
It looks like the page isnÄt set up yet for multilinguality. I don't know where to put the German version. Assigning @fsteeg . (I would like to have this until my presentation tomorrow...)

**Comment by fsteeg** [comment]
Deployed to staging: http://stage.lobid.org/

**Comment by acka47** [comment]
Looks good but I think we have to still work on the wording. What about something like this:

> lobid ist ein Angebot LOD-basierter Rechercheoberflächen und Programmierschnittstellen (APIs) für Bibliotheken. Es wird betrieben vom Hochschulbibliothekszentrum des Landes NRW (hbz).

**Comment by fsteeg** [comment]
Redeployed to staging: http://stage.lobid.org/

**Comment by acka47** [comment]
+1, although the LOD akronym isn't resolved. But I just couldn't come up with a good solution and "Linked-Open-Data-basiert" is too sperrig.

**Comment by fsteeg** [comment]
Redeployed after discussion by @dr0i and @acka47 in #341: http://stage.lobid.org/

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
+1
