### ISSUE TITLE
https certificate error - easy to solve

### ISSUE THREAD

**Issue by aquast** [hbz/lobid#349]
Dear colleagues,

Your https-implementation is somehow incomplete which results in a security warning from modern browsers. The Problem is quite easy to solve:

replace "http" with https in all [ALL] linked URLs. In my opinion the security issue is related to the call of   http://lobid.org/images/clouds.jpg solely but... it's also a good idea to provide linked services like twitter & co. via https too.

IMHO in your next step your webserver (apache/ningx) should be configured to redirect all http-requests to https which is an upcoming default inthe www

**Comment by fsteeg** [comment]
Deployed to production: https://lobid.org

Thanks for the report @aquast.

**Comment by ChristophEwertowski** [comment]
+1 and closing.
