### ISSUE TITLE
Switch scheduler: from crontab  to Jenkins

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#354]
I like this little [post](https://www.cloudbees.com/blog/drop-cron-use-jenkins-instead-scheduled-jobs) which describes jenkins as “cron on steroids”.
Jenkins can do more than that, but first of all the described scheduling is what is most important for us. Jenkins' *events* could have prevented hbz/lobid-resources#586.

**Comment by acka47** [comment]
Closing
