### ISSUE TITLE
Play cache for json format has different keys

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#356]
Depending on how to lookup the resource (.../resources/ID vs. .../resources/ID.json ) a different cache key is generated although the provided result for resources without an explicit `format` (aka `format=null`) is the same json.

Example:
show(HT018903884,json(.+)?)
show(HT018903884,json)

This has two drawbacks:
1. there are not *one* but *two* ~~cached identically objects~~ different caches for the same object.
2. it may be that the cache of the one resource differs from the other (experienced this with the `dateModified`).

 I think it's better to have just one cached object. What do you think @fsteeg ?

**Comment by acka47** [comment]
Closing
