### ISSUE TITLE
Support content negotiation for /team profiles

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#359]
We already support it for /resources and /organisations see e.g. `curl -i -H "Accept: Application/ld+json" http://lobid.org/organisations/DE-605`. It doens't work for our foaf profiles, though see e.g. `curl -i -H "Accept: Application/ld+json" http://lobid.org/team/ap#!`

**Comment by dr0i** [comment]
Maybe these are even not valid foaf:profile because they use mostly schema.org?

**Comment by dr0i** [comment]
Did this:
>  RewriteCond %{HTTP_ACCEPT} application/ld\+json
RewriteCond %{REQUEST_URI}   !(.*json)
RewriteRule ^/team/(.*)(?!json) /team/$1.json [L,P]
RewriteRule ^/team$ /team.json [L,P]

Have a look @acka47 @fsteeg.

**Comment by acka47** [comment]
Doesn't work for me. `$ curl -i -H "Accept: Application/ld+json" http://lobid.org/team/ap#!` still gives back HTML only.

**Comment by fsteeg** [comment]
With a lowercase `application` it works:

`$ curl -i -H "Accept: application/ld+json" http://lobid.org/team/ap#!`

But:

> "All media type values, subtype values, and parameter names as defined are case-insensitive." (https://tools.ietf.org/html/rfc2045)

**Comment by dr0i** [comment]
Right! Added an '[NC]' to the end of the `rewriteCond` to make it `case insensitive`.
Please check agian.

**Comment by acka47** [comment]
+1
