### ISSUE TITLE
Use new lobid logo

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid#365]
- upper left corner in nav bar
- favicon
- large image on lobid.org

**Comment by fsteeg** [comment]
Deployed to stage:

http://stage.lobid.org/
http://stage.lobid.org/gnd
http://stage.lobid.org/resources
http://stage.lobid.org/organisations

**Comment by ChristophEwertowski** [comment]
+1

**Comment by acka47** [comment]
+1
