### ISSUE TITLE
Switch off HSTS

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#367]
Since at least yesterday we experienced some problems with internal subdomains lacking a ssl certificate. Firefox works sometimes, or not. Chromium gives more information:

>  derzeit nicht aufrufen, da die Website HSTS verwendet. Netzwerkfehler und Angriffe sind in der Regel nur vorübergehend, sodass die Seite wahrscheinlich später wieder funktioniert.

See https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security.
HSTS shall be abandoned on our webserver.

**Comment by acka47** [comment]
You found it! \o/

**Comment by dr0i** [comment]
I think so. The weird thing is - apache don't seems to be configured to use HSTS.
As a workaround @acka47 @fsteeg @ChristophEwertowski if you discover this problem and use firefox:

1. close firefox 
2.  find the "lobid" line in `SiteSecurityServiceState.txt`, remove that line. 
3.  restart firefox

As I understand correctly the HSTS would be set again by our server if we are under "attack" again (yeah, someone tries to fiddle with our webserver at the moment).

**Comment by dr0i** [comment]
Uh. Found the cause of the HSTS - it comes with the `reverseProxy` introduced  with hbz/lobid-resources#798 , see https://stackoverflow.com/questions/39101191/strict-transport-security-influence-on-http-reverse-proxy-that-redirects-to-http/49816426#49816426. Using a simple `RewriteRule` instead fixed it.

**Comment by dr0i** [comment]
Is this ok now for you @acka47 and @fsteeg, too? Check my comment above to unset the `HSTS` flag for firefox first when testing.

**Comment by dr0i** [comment]
Ok now, now this doesn't anonymize us, see curl -vvvL https://lobid.org/tiles/7/3/4.png |grep IP. Grrr.

**Comment by ChristophEwertowski** [comment]
I did remove the lobid-line from the firefox-file but I still get the message "Verbindung ist nicht sicher". But now I can open cerebro again which wasn't possible for some time.

**Comment by dr0i** [comment]
> now this doesn't anonymize us ...

The `ProxyVia On` directive in the `vhost` did the trick.

**Comment by fsteeg** [comment]
> Is this ok now for you @acka47 and @fsteeg, too?

Works fine here (stage and cerebro).

**Comment by dr0i** [comment]
@fsteeg I just now added the  `ProxyVia On directive` because I was afraid to restart the webserver (it was friday 8:00 pm I discovered the "trick").
So, if something strange will happen soon you may want to refer to this issue again.

**Comment by dr0i** [comment]
@ChristophEwertowski yeah. that's the "strange" thing about HSTS ("HTTP Strict Transport Security "): it forces the browser to not allow to ad security exceptions (normally we add those exceptions all the time because evensom  mayor domains are not capable or willing to use proper certification). So, now we can add these exceptions for our (internal, testing) sub-domains again.

**Comment by dr0i** [comment]
Works as expected so far, closing.

**Comment by dr0i** [comment]
Sorry. No. `ProxyVia On` doesn't help to anonymize. Cheeze.

**Comment by dr0i** [comment]
Finally (?!) , again using "reverseProxy" and `Header unset Strict-Transport-Security`, this seems to work. @acka47 @ChristophEwertowski @fsteeg you discover something strange: just cry out loud.
