### ISSUE TITLE
Create "Verfahrensverzeichnisse"

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid#368]
Sub-issue of https://github.com/hbz/lobid/issues/363. See https://wiki.hbz-nrw.de/display/DS/Verfahrensverzeichnisse for a description of what a *Verfahrensverzeichnis* is and https://wiki.hbz-nrw.de/display/DS/Verfahrensverzeichnisse+im+hbz for already existing ones. I will start with it.

**Comment by ChristophEwertowski** [comment]
I created the start of *Verfahrensverzeichnisse* through copying and changing the example of "DigiBib". There are files for lobid-gnd, -organisations and -resources and also for the NWBib behind this [Wolke link](https://wolke.hbz-nrw.de/index.php/apps/files/?dir=/lobid/Verfahrensverzeichnisse&fileid=135179). While working on it I wrote some questions down which I sent our data security officer. On Thursday I will reach for the rest of the team to get some more answers / confirmations.

**Comment by ChristophEwertowski** [comment]
Here a list of needed *Verfahrensverzeichnisse* ordered by significance.

- [ ] lobid-gnd
- [ ] lobid-resources and datahub equivalents of [lobid-resources 1.0](https://old.datahub.io/dataset/lobid-resources) and catalogue in [MAB-XML](https://old.datahub.io/dataset/hbz_unioncatalog)
- [ ] NWBib
- [ ] lobid-organisations and [datahub equivalent](https://old.datahub.io/dataset/lobid-organisations) of lobid-organisations 1.0
- digitalisierteDrucke?

**Comment by acka47** [comment]
Closing
