### ISSUE TITLE
Update hbz datahub exports

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid#369]
Reported by @acka47 in https://github.com/hbz/lobid-resources/issues/809#issuecomment-385386163. I probably have to create a *Verfahrensverzeichnis* for it...

Addition: The missing [link](https://old.datahub.io/dataset/hbz_unioncatalog).

**Comment by ChristophEwertowski** [comment]
There are also datasets for the old [lobid-resources](https://old.datahub.io/dataset/lobid-resources) and old [lobid-organisations](https://old.datahub.io/dataset/lobid-organisations).

**Comment by acka47** [comment]
Closing
