### ISSUE TITLE
Add "MAB source" tab in UI

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#37]
After https://github.com/lobid/lodmill/issues/478 it should be possible to view the source data besides the different RDF via a designated "MAB source" tab.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/resource?id=HT002189125

**Comment by acka47** [comment]
Looks good. However, comparing to http://lobid.org/resource?id=TT000075751&format=source, the XML attributes are sorted differently and syntax highlighting is missing. By now I think that a simple link to the source (as in NWBib)( might have been a better solution. But I will get accustomed to this and we will have to think about adapting the NWBib view for the whole lobid anyway so we shouldn't put to  uch effort into this now. Thus, +1.
