### ISSUE TITLE
Adapt data security statement

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid#370]
We have to link to data security statements for our sites.

**Comment by fsteeg** [comment]
Link from:

- [ ] Lobid 2.x
- [ ] Lobid 1.x
- [ ] NWBib
- [ ] Digitalisiertedrucke

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
The links in resources/organisations/gnd are missing therefore opening this issue again.

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/resources
http://lobid.org/organisations
http://lobid.org/gnd
