### ISSUE TITLE
Exclude old lobid services in robots.txt from crawling 

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#371]
I think we just have to make it:

```
User-agent: *
Disallow: /resource/
Disallow: /subject/
Disallow: /person/
Disallow: /organisation/
```

@fsteeg We should do this soon.

**Comment by fsteeg** [comment]
Deployed to production (stage has a different robots setup), see:

http://lobid.org/robots.txt

Please reopen if something is wrong.

**Comment by ChristophEwertowski** [comment]
+1

**Comment by acka47** [comment]
+1
