### ISSUE TITLE
Write lobid reference article for Infoprax

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#378]
I talked to @hauschke and decided that it would be best to write a "reference article" about lobid. We can easily take parts for the text from our blog.

How will we write this? I think it went quite well on GitHub with the Libreas article some time ago, didn't it?

**Comment by fsteeg** [comment]
Joined the mentioned blog posts into a single file, no content changes, just updated the header levels:

https://github.com/hbz/lobid/blob/infoprax/doc/lobid.md

We can use this as a baseline for edits and diffs.

**Comment by fsteeg** [comment]
Ich habe die Struktur etwas überarbeitet und ein übersetztes TOC mit 2 Ebenen angelegt:

https://github.com/hbz/lobid/blob/infoprax/doc/lobid.md

So in etwa könnte die Gesamtstruktur aussehen. Ich würde dann Mittwoch hier weitermachen.

**Comment by acka47** [comment]
Ich habe heute den ersten Abschnitt ("Überblick") gelesen und einige Änderungen committed (siehe [diff](https://github.com/hbz/lobid/commit/fee60ddfb4fe502646e7d70639bc1096b3e4bd70?short_path=0d73fc2#diff-0d73fc2dba9cc99eead3a724d293a532)). Außerdem habe ich [hier](https://github.com/hbz/lobid/blob/798f69d2bc10c9f41858406fc51cbb95a7fddd6e/doc/lobid.md) einige Kommentare als hypothes.is-Annotationen ergänzt.

Von der Gliederung her ist der Text ja in den ersten beiden Abschnitten sehr technikbezogen. Ich finde das in Ordnung, allerdings sollten wir in einer Einleitung die Gründe für die Gliederung darlegen und vor allem in wenigen Worten deutlich machen, warum lobid überhaupt entwickelt wird, wer die Zielgruppe ist und was dieser mit lobid geboten wird.

**Comment by fsteeg** [comment]
Bin nochmal den ganzen Text durchgegangen und habe Sachen gefixt und hier und da etwas ergänzt und die Überschriften-Struktur angepasst. Das TOC habe ich nochmal neu mit 2 Ebenen generiert, ich finde so sieht man gut die Gesamtstruktur. Ich bin insgesamt zufrieden so.

https://github.com/hbz/lobid/blob/infoprax/doc/lobid.md

Der verbleibende größere Schritt ist dann wohl, das in die Formatvorlage zu bekommen.

https://journals.ub.uni-heidelberg.de/index.php/ip/about/submissions

**Comment by acka47** [comment]
Zu ergänzen:

- [ ] Referenzen für zentrale lobid repos (gnd, organisations, resources)
- [ ] Abschnitt zum Team mit Schätzungen der Ressourcen (Stunden/Woche für lobid allein)

**Comment by acka47** [comment]
Eine Konversion des Markdowns nach docx (``) sieht im Ergebnis bereits ganz gut aus. Folgende Dinge sind aber am Ende noch anzupassen:

- [ ] "Die Code-Abschnitte werden in einer 1x1 Tabelle gesetzt. Bei Bedarf können sie auch mit einem Titel versehen werden, die Nummerierung erfolgt allerdings als Abbildung (“Abb. X”)" (aus der []())
- [ ] JSON-LD-Piktogramm in Abschnitt "Suche und Navigation in der Benutzeroberfläche" einfügen (wird bei der Konversion verschluckt)

**Comment by acka47** [comment]
Nach der Konversion nach doc umfasst der Text 40 Seiten. Das finde ich schon sehr lang. Wir könnte wahrscheinlich leicht zwei Texte draus machen, einen zu lobid allgemein und einen zu lobid-gnd (ab "Fallstudie"). Können wir dann nächste Woche ja mal untereinander und – falls nötig – mit der Infopraxm-Redaktion besprechen.

**Comment by fsteeg** [comment]
> Referenzen für zentrale lobid repos (gnd, organisations, resources) mit Zenodo Snapshot (siehe https://guides.github.com/activities/citable-code/)

Ich habe das in Zenodo soweit eingerichtet. Ich schlage vor, ich erzeuge dann die eigentlichen Releases wenn wir die aktuellen Anpassungen der Datenset-Beschreibungen deployed haben, die ja alle 3 Dienste betreffen.

> Infoprax-Empfehlung für die maximale Länge eines Fachbeitrags sind übrigens 24.000 Zeichen. Wir haben etwa 58.000

Dann passt doch die von dir vorgeschlagene Aufteilung in zwei Artikel sehr gut.

**Comment by hauschke** [comment]
Zwei Artikel sind m.E. in Ordnung, wenn die inhaltliche Aufteilung Sinn ergibt.

**Comment by acka47** [comment]
@hauschke Es ergibt auf jeden Fall Sinn, bin gerade schon am aufteilen.

**Comment by fsteeg** [comment]
Created snapshots for Zenodo:

https://doi.org/10.5281/zenodo.1423188 (gnd)
https://doi.org/10.5281/zenodo.1423192 (organisations)
https://doi.org/10.5281/zenodo.1423194 (resources)

**Comment by fsteeg** [comment]
Habe beide Artikel überarbeitet:

https://github.com/hbz/lobid/blob/infoprax/doc/lobid.md
https://github.com/hbz/lobid/blob/infoprax/doc/lobid-gnd.md

**Comment by acka47** [comment]
Sehr gut. Blöderweise kann ich gerade nicht mehr die Dateien nach doc(x) überführen, ohne dass die Bilder alle zu groß sind. Probiere am Montag weiter.

**Comment by acka47** [comment]
Beide Artikel gingen heute an das hbz-Marketing zur Abnahme/zum Korrekturlesen.
