### ISSUE TITLE
New SSL Certificates needed

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#383]
All two years or so the SSL certificates reached their EOL.
The whole procedure of getting/installing certs is do be done again. Grr.
See #182 for what was done before.

- [x] https://lobid.org
- [x] https://www.lobid.org
- [x] https://beta.lobid.org
- [x] https://blog.lobid.org
- [x] https://test.lobid.org
- [x] ~~https://vocabs.lobid.org~~
These would be cool to have sometime in the future:
- [x] https://labs.lobid.org
- [x] https://slides.lobid.org
- [x] https://matomo.lobid.org
- [x] https://etherpad.lobid.org

These are not of lobid's domain, but as certs are installed at the same time, herewith be included at this overview page:

- [x] https://metafacture.org
- [x] https://www.metafacture.org
 
- [x] https://nwbib.de
- [x] https://www.nwbib.de
- [x] https://test.nwbib.de

- [x] https://skohub.io
- [x] https://www.skohub.io
- [x] https://test.skohub.io

**Comment by dr0i** [comment]
It will be easier if the domain is hosted by hbz and not united-domains. Made a new issue #384.

**Comment by dr0i** [comment]
All set up and tested ok.
Closing.

**Comment by dr0i** [comment]
Remark:
don't forget that there is **SAN**, meaning one certificate can handle multiple domain names. We will use this next time for lobid.org and its respective subdomains.

**Comment by dr0i** [comment]
Two years passed - time for renewal. Contacting IT, asking also for labs.lobid.org. Also SAN. Included  into the FQDN list at https://github.com/hbz/lobid-blog/issues/69 labs.lobid.org.

**Comment by acka47** [comment]
I also added `matomo.lobid.org` and `etherpad.lobid.org` in the original issue.

**Comment by dr0i** [comment]
All configured and commited in internal git repo. Completed the list (at the top of this issue). We still have vocabs.lobid.org in the SAN but it's not configured as vhost. Closing. Cu in 2 years.

**Comment by dr0i** [comment]
Oh, @acka47 you may want to have a look before closing this!

**Comment by acka47** [comment]
> Cu in 2 years.

It looks like the certificates for lobid, metafacture and Skohub only run for one year:

![image](https://user-images.githubusercontent.com/160292/105142268-b4687300-5afa-11eb-93d2-77c56b7c50a0.png)

 For NWBib it looks differently:

![image](https://user-images.githubusercontent.com/160292/105142829-52f4d400-5afb-11eb-94fd-a6831418c95e.png)

Shouldn't it have been updated as well?

**Comment by dr0i** [comment]
Uh, you are right! Now copied the new cert and key into the proper place.
@acka47 please check again.

**Comment by acka47** [comment]
Looks good now. All certificats expire on 2022-02-20. Closing. See you in one year. ;-)
