### ISSUE TITLE
Get rid of ssl keys for vocabs.lobid.org

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#385]
Working on #383 I discovered that we don't use http://vocabs.lobid.org/, right? If so, we don't need to get the SSL keys for that subdomain.

**Comment by acka47** [comment]
+1 Do we have to do anything or can we close the issue?

**Comment by dr0i** [comment]
Hm, no, we just don't have to forget to _not_ apply for a new ssl key for this subdomain.
Closing.
