### ISSUE TITLE
Resource queries based on prefered and alternate labels of subjects

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#39]
Goal:
- http://lobid.org/resource?subject=klimawandel, http://lobid.org/resource?subject=klimaveränderung, http://lobid.org/resource?subject=klimawechsel should all yield results and furthermore the same results.
-  http://lobid.org/resource?subject=ebola-fieber http://lobid.org/resource?subject=Maridifieber (Maybe the label including a hyphen makes different result sets...)
- http://lobid.org/resource?subject=Wirbeltiere, http://lobid.org/resource?subject=Vertebrata

**Comment by acka47** [comment]
Currently, we need to have one property where every preferred and alternate label of all subjects are listed. That is why we – for now – should in fact use `dc:subject` with a list of all the labels as extracted from Aleph XML.

**Comment by dr0i** [comment]
Deployed to staging the small test set (links in this ticket won't work with).

**Comment by dr0i** [comment]
@acka47 you began the ticket with the claim:
> http://lobid.org/resource?subject=klimawandel, http://lobid.org/resource?subject=klimaveränderung, http://lobid.org/resource?subject=klimawechsel should all yield results and furthermore the same results.
But how could they? The information isn't in the data. See e.g. http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DHT018249773 which has `Klimawandel` in it's data but not `Klimaveränderung`.

**Comment by dr0i** [comment]
With the mapping of the subjects prefLabel to `dc:subject` I think we could remove the `"@graph.http://www.w3.org/2004/02/skos/core#prefLabel.@value"` in the subject query, or not?

**Comment by dr0i** [comment]
Deployed to staging, see e.g. http://lobid.org/resource/HT001898812 .
Hard to test. You may want to wait for the complete test data indexing to check the resource-links you already provided, or you may want to have a look at the lonley HT001898812.

**Comment by acka47** [comment]
> With the mapping of the subjects prefLabel to dc:subject I think we could remove the "@graph.http://www.w3.org/2004/02/skos/core#prefLabel.@value" in the subject query, or not?

We should retain it as it is useful for presentation purposes (people will need to know which label to choose for presentation).

**Comment by acka47** [comment]
I added some test resources to the testset that should be found with the "Ebola-Fieber" and the"Wirbeltiere" query e.g. HT002412047 and HT009221259. They cannot be found yet, see
- http://lobid.org/resource?subject=ebola-fieber
- http://lobid.org/resource?subject=Wirbeltiere

(The "Klimawechsel" example is a bad one as the single result actually doesn't have a GND subject with several labels. There only is a subject chain.)

**Comment by acka47** [comment]
The next two steps here are:
- [ ] Also add preferred subject label (Ansetzungsform) to `dc:subject`.
- [ ] Only query `dct:subject`, `dc:subject`, `subjectChain`

**Comment by acka47** [comment]
Here are two test cases that work with the current test set:

-  http://test.lobid.org/resource?subject=ebola-fieber http://test.lobid.org/resource?subject=Maridifieber (Maybe the label including a hyphen makes different result sets...)
- http://test.lobid.org/resource?subject=Wirbeltiere, http://test.lobid.org/resource?subject=Vertebrata

**Comment by acka47** [comment]
It would be great to deploy this together with #122. ;-)

**Comment by dr0i** [comment]
(I don't understand why "Maridifieber" could be ever found in a former test set, as stated in https://github.com/hbz/lobid/issues/39#issuecomment-76946414)
 However, with https://github.com/lobid/lodmill/commit/75ec5e1c448bae4105dd7e329e92b0f200ac8886 the iteratable fields are taken into account which will solve the "Maridi" problem.
You can also have a look in the small test data set (look in the commit. There's no "Maridi", but e.g. 'HT018131501' and 'HT013077595' ).

However, if you @acka47 look into http://lobid.org/resource?id=HT013077595&format=source , maybe you can help me with fiddling together what combinations of subfields are to be concatenated and which not. Also have a look at the (sparsely) [documentation for this internal hbz field - search "952"](https://wiki1.hbz-nrw.de/pages/viewpage.action?pageId=13238276) .

**Comment by acka47** [comment]
That's a lot of points in one comment. I respond in two seperate comments.

> (I don't understand why "Maridifieber" could be ever found in a former test set, as stated in https://github.com/hbz/lobid/issues/39#issuecomment-76946414)

I [added](https://github.com/lobid/lodmill/commit/083cf79d5a8acb20f00581b97e40698f95735ba9) HT009221259 to the test set [whose source](http://lobid.org/resource?id=HT009221259&format=source) contains "Maridifieber" as alternate label of GND entity http://d-nb.info/gnd/4370218-1 in field 952:

```
datafield tag="957" ind1="-" ind2="1"><subfield code="s">Maridifieber</subfield></datafield>
```
>  However, with https://github.com/lobid/lodmill/commit/75ec5e1c448bae4105dd7e329e92b0f200ac8886 the iteratable fields are taken into account which will solve the "Maridi" problem.

Great.

> You can also have a look in the small test data set (look in the commit. There's no "Maridi", but e.g. 'HT018131501' and 'HT013077595' ).

As said above, there's HT009221259 with "Maridifieber".

**Comment by acka47** [comment]
> However, if you @acka47 look into http://lobid.org/resource?id=HT013077595&format=source , maybe you can help me with fiddling together what combinations of subfields are to be concatenated and which not. Also have a look at the (sparsely) [documentation for this internal hbz field - search "952"](https://wiki1.hbz-nrw.de/pages/viewpage.action?pageId=13238276) .

I am ready to have a look but don't really understand what the question is. An example would help.

**Comment by akuckartz** [comment]
Are Triple Pattern Fragments (http://www.hydra-cg.com/spec/latest/triple-pattern-fragments/) an alternative or possible implementation approach?

**Comment by acka47** [comment]
As a general rule. Follow the pattern in the DNB catalog for putting together subject headings, see e.g. http://d-nb.info/gnd/4024116-6 and  http://d-nb.info/gnd/4024116-6. It looks like they do it like this:

- subfield h: parenthesis `()`
- subfield b: period `.`
- subfield x: slash `/`

As this data is only used for search and not for indexing it doesn't matter that much, anyway…

**Comment by dr0i** [comment]
re "Testsets": there are at least 2 so called "testsets":

1. the tests used automatically when building and testing the repo (https://github.com/lobid/lodmill/blob/master/lodmill-rd/src/test/resources/hbz01XmlClobs.tar.bz2), consisting of ~ 30 documents
2. the "smallTest" normally used when deploying and indexing, consisting of `1.` and many more , about ~ 30k documents

It would be great if you could find examples in the data of `1.` because I *must do this anyway* (to have a test set which allows us to evade regressions etc.). I would be thankful if this testset is as small as possible so that tests don't get overbloated.

**Comment by dr0i** [comment]
Took the subfields `[acdefpmogkrstuz]` ( see https://wiki1.hbz-nrw.de/display/VDBE/GND-2+-+Neue+Unterfeldstruktur+in+BIB ) into account and combined them separately with your provision of `[hbx]`.

**Comment by dr0i** [comment]
Deployed to staging. For "Unterfeldstrukturen" see e.g. http://test.lobid.org/resource?id=HT013077595.

**Comment by acka47** [comment]
Looks good. I fund one minor thing, though. The JSON-LD contains this:
```
"subjectLabel" : [ "Pressestelle", "Coesfeld", ...]
```

There seems to be a problem with the conversion of subfield b here. It shoudl rather read 
`"subjectLabel" : [ "Pressestelle", "Coesfeld", ...]`. 

+1 for deploying as it doesn't affect searchability.

**Comment by acka47** [comment]
I just saw that `"Coesfeld. Pressestelle"` is in the data. Obviously, these seem to be added concatenated with a period inbetween and as seperate literals.

**Comment by dr0i** [comment]
There are more than only the three subfields mentioned in https://github.com/hbz/lobid/issues/39#issuecomment-79000458. This is reflected in the [last commit](https://github.com/lobid/lodmill/commit/3c53e8fb898ab1e6156ae124450cbe577df7ac14).

**Comment by acka47** [comment]
> As a general rule. Follow the pattern in the DNB catalog for putting together subject headings, see e.g. http://d-nb.info/gnd/4024116-6 and  http://d-nb.info/gnd/4024116-6. It looks like they do it like this:

> - subfield h: parenthesis `()`
> - subfield b: period `.`
> - subfield x: slash `/`

> As this data is only used for search and not for indexing it doesn't matter that much, anyway…

Sorry, but this shouldn't be a general rule at all but rather confined to spatial subject headings (Geographika). See, e.g. http://lobid.org/resource/HT010726584/about ([source data](http://lobid.org/resource?id=HT010726584&format=source)). We shoudl keep this in mind when working on #139.

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
Closing.
