### ISSUE TITLE
Incorporate feedback from open peer review in lobid-gnd article

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#393]
See [here](https://hyp.is/txaAoBHiEemWZt9g4eZJww/informationspraxis.de/wp-content/uploads/sites/6/2019/01/Christoph_Pohl_Steeg_02012019.pdf)

**Comment by acka47** [comment]
I started working on this in branch https://github.com/hbz/lobid/tree/infoprax. What's still missing? 

Re. OpenRefine tutorial:

> Damit der Sinn (und die oben versprochene Anreicherung) deutlich wird, fehlen hier m.E. noch zwei Schritte:
> 1. Semi-automatische Auswahl der Matches https://paste.pics/53b6942dcd9cecb88b6cfdeaea20ee07
>2. Anreicherung mit Daten aus GND-Einträgen https://paste.pics/f15e410532c90e4214afaaee1caa94be

Re. lobid-gnd usage:

> Um die Nutzungspotentiale für die Leserinnen noch greifbarer zu machen, könntet ihr noch Anwendungsbeispiele im Ausblick oder in einem extra Kapitel benennen. Gibt es eine Liste von lobid-Nutzerinnen (und wofür)? Interessant wären auch erste Statistiken zur Nutzung der lobid-gnd.

**Comment by acka47** [comment]
Re. usage, I am starting with a list of users and use cases (to be extended):

- Kalliope: Anzeigen von Wikipedia-Links ([Beispiel](http://kalliope-verbund.info/de/eac?eac.id=118551132))
- Publisso, Edoweb (?): GNDID-lookup
- CMIF Creator: GNDID-Lookup (siehe [hier](http://slides.lobid.org/gndcon18/#/29))
- NWBib
- Literaturarchiv Marbach (OpenRefine Reconciliation)
- Bauhaus Archiv (OpenRefine Reconciliation)
- Digital Humaities-hackathons und -workshops (siehe https://twitter.com/chrisaliv/status/1091292130029514754 & https://twitter.com/jakobfrohmann/status/1091364967738163200)
- tbc

**Comment by fsteeg** [comment]
[OpenRefine-Matching und -Anreicherung](/hbz/lobid/commit/fbfcfca1d09fca466cd46c1e35e6c3d7eafecf22) ergänzt.

**Comment by acka47** [comment]
Ich hab mal was zur Nutzung ergänzt und ein bisschen den Ausblick und die Referenzen aktualisiert: https://github.com/hbz/lobid/commit/f619e95d03685a53dd02cdaa266ca645a4eeceeb

Sorbib und Geoportost haben m.E. noch keine GND-IDs in ihren Dienste übernommen, ich hatte aber mit beiden längeren E-Mail-Kontakt. Evtl. sollten wir das aber doch lieber rausnehmen.

Für OpenRefine sollten wir noch Nutzungszahlen angeben, wenn wir da etwas klarer sehen,

**Comment by fsteeg** [comment]
Hab ein paar Sachen angepasst und die Zahlen zur Autosuggest-API mal rausgenommen, weil das (auch, und wohl vor allem) unsere eigenen Vorschläge im lobid-gnd Suchfeld enthält.

Siehe https://github.com/hbz/lobid/commit/d139436a9ba184b2516ad7da553f852e09a7ebba

Zum letzten Beispiel ("Unterstützung bei der Ersetzung von nicht mehr aktuellen GND-IDs") fehlt noch wer das macht oder sowas.

**Comment by acka47** [comment]
Ich habe die Dateien an Infoprax gesendet. Es wird allerdings erst im März etwas mit der Veörffentlichung. Closing
