### ISSUE TITLE
Gather usage information

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#394]
Questions we need to answer for lobid-gnd and preferably the other two lobid services:

- Who uses lobid?
- For that is lobid used? Which features are used?
   - Web UI
   - API
   - Bulk downloads
   - OpenRefine Reconciliation Endpoint

We should first take a deeper lool at the logs, I will provide the indicators for API vs. bulk vs. openrefine later. Furthermore, we should consider setting up a very short poll.

**Comment by acka47** [comment]
@dr0i, as I am not able to get this information from Matomo, can you please extract it from the logs directly? For all stats, please use the six months **from 2018-08-01 to 2019-01-31**.

# lobid-resources
- RSS:  GET requests containing `format=rss"or `"Accept: application/rss+xml"`
- Bulk downloads: GET requests containing `format=jsonl`, `format=bulk`, `"Accept: application/x-jsonlines"`, or `"Accept-Encoding: gzip"`
- auto suggest: GET requests containing `format=json:` (The colon is important!)

# lobid-gnd
- Bulk downloads: GET requests containing `format=jsonl`, `"Accept: application/x-jsonlines"`, or `"Accept-Encoding: gzip"`
- auto suggest: GET requests containing `format=json:`
- OpenRefine reconciliation: GET requests with path `/gnd/reconcile`

# lobid-organisations
- csv Downloads: GET mit Header `"Accept: text/csv"`, `format=csv`
-  Bulk downloads: GET requests containing `format=bulk`, `"Accept: application/x-jsonlines"`, or `"Accept-Encoding: gzip"`
- auto suggest: GET requests containing `format=json:`
- other rdf formats: GET requests containing `.rdf`, `.ttl`, `.nt`
- OpenRefine reconciliation: GET requests with path `/organisations/reconcile`

**Comment by acka47** [comment]
@fsteeg, please take a quick look whether i have forgotten anything.

**Comment by acka47** [comment]
THanks, @fsteeg. I updated https://github.com/hbz/lobid/issues/394#issuecomment-460613271 accordingly. Assigning @dr0i .

**Comment by dr0i** [comment]
Note that we don't log header in general.

**Comment by dr0i** [comment]
@acka47 I added the numbers into your comment. See a note from me: the patterns you gave are just grepped by (so they may be complemented by whatever), and mind that we also don't log POSTs.

**Comment by acka47** [comment]
To get a feeling for the geographic distribution, here are the cities in the date range from 2018-08-01 to 2019-01-31 we had at least 100 visits from:

Frankfurt/Main
Berlin
Wien
Kiel
Leipzig
Dortmund
Hannover
Hamburg
Tübingen
Braunschweig
Graz
Basel
Marburg
Dresden
Stuttgart
Mainz
Starnberg
Ashburn
Winterthur
Pinneberg

**Comment by acka47** [comment]
According to Matomo, nearly 200 `.preview` URLs were requested in /gnd from 2018-08-01 to 2019-01-31.

**Comment by acka47** [comment]
Closing this one. However, we should think about also logging POSTs to the /reconcile endpoint.
