### ISSUE TITLE
Restore English team page

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid#395]
I think we lost the English team page when we removed the lobid 1.x web app (https://github.com/hbz/lobid/commit/72f105c2007b63eca1101e2c293fade45a4056d8). The JSON file with the English labels is still there. Maybe we should move the template that generated the page from the JSON file into another app?

**Comment by dr0i** [comment]
We could render the language variant pages using https://lobid.org/team.json.
As discussed with @acka47 we could use the `gatsby` static side generator. As it uses `graphql` we could reuse `gatsby` to generate pages querying our slides, blogs etc.

I managed to install `gatsby`. , grep in `vhosts` to see where to reach it via the Browser. The installation location is the common under`lobid@emphytos`.

**Comment by dr0i** [comment]
Build with gatsby, see http://stage.lobid.org/.

**Comment by fsteeg** [comment]
Main page looks good, but on the team page (http://stage.lobid.org/team_en/) the German/English switch and some CSS are missing (see `ì` menu compared to http://stage.lobid.org). It would also be nice if they followed the same naming convention (e.g. team-de, like index-de, not team_de).

**Comment by dr0i** [comment]
Gatsby now uses the react-bootstrap and no more jquery but react-native components in the navbar. I got it look nearly the same as the old navbar, but it's not exactly the same. See http://stage.lobid.org/ and don't forget to clean your browser's cache.

**Comment by dr0i** [comment]
Regarding naming/structuring of language specific sites: please have a look at [the different proposals](
https://stackoverflow.com/questions/21985164/best-practice-for-urls-of-multi-language-websites) and tell me your favourite. We may discuss this also offline.

**Comment by dr0i** [comment]
Decided offline to go with the language suffix for pages and to get rid of the "html" suffix.
@acka47 @fsteeg please review http://stage.lobid.org/
note to self: when deploying don't forget to route index in apache conf to the index pages without the html suffix.

**Comment by fsteeg** [comment]
> @acka47 @fsteeg please review http://stage.lobid.org/

Great, looks good! +1

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closed.
