### ISSUE TITLE
Add more prominent link to blog

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#406]
Our blog is not featured very prominently on lobid.org. We should think about changing this, e.g. by adding "Blog" to the top nav bar on the right-hand side (next to language switch).

**Comment by acka47** [comment]
We decided to implement this together with #405 by adding a "Publications" tab next to the language switch with sub-entries "Blog" and "Presentations". In the future we can then also add something like "Journal Articles".

**Comment by dr0i** [comment]
Done. Please review @acka47.

**Comment by acka47** [comment]
Thanks. I would prefer it at the left-hand side of the language switch with "Publications" / "Publikationen" written in full. So that it kind of is on one level with the three services linked on the left-hand side of the nav panel.

**Comment by dr0i** [comment]
Check again.

**Comment by acka47** [comment]
I meant this position:

![Bildschirmfoto vom 2019-11-05 10-29-08](https://user-images.githubusercontent.com/160292/68195481-384a4400-ffb7-11e9-84ab-63f0cee98caa.png)

**Comment by dr0i** [comment]
Ah, now I "see" :) Check again.

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
Closing
