### ISSUE TITLE
Create index for resources with links to undifferentiated persons

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#411]
B.B. asks today per email:

> Habt Ihr die Möglichkeit für folgende Datenselektion:
> PN-Sätze (nicht individualisierte Personen) inkl. Information über betreffende HBZ01-Titel-IDN + OWNer

To do:
1. Create a list of all undifferentiated persons in GND: http://lobid.org/gnd/search?filter=%2B%28type%3AUndifferentiatedPerson%29 along with `preferredName` and `variantName`
2. Automatically query lobid-resources based on this list and
3. Save ID of every hit, including the holding institutions, the respective GND entry and its label and altLabel

(This would be easier if we had the concrete type in `contribution.agent.type` but we only have `Person`  for all differentiated as well as undifferentiated persons.)

**Comment by acka47** [comment]
Similar to https://github.com/hbz/lobid-gnd/issues/222. Will reuse the script there.

**Comment by acka47** [comment]
I started to create a csv with one line for each `UndifferentiatedPerson` that has at least one `variantName`, containing the URI (`id`), `preferredNameand `variantName`:

`curl --header "Accept: application/x-jsonlines" "http://lobid.org/gnd/search?q=type%3AUndifferentiatedPerson+AND+_exists_%3AvariantName&size=10" | jq -r '. | [ .id, .preferredName, (.variantName | join("; ")) ] | @csv' > 202001-undifferentiated-with-variantName.txt
'` 

Next step:

1. Query lobid-resources with the URI
2. If query yields results add hbz ID to the line, else delete line.

**Comment by acka47** [comment]
This seems to work with a test set of 20 GND IDs (though it is probably not great code):

```py
import requests
import json

filepath = '202001-undifferentiated-with-variantName.txt'

input = open(filepath).readlines()

def build_url(id):
    return 'https://lobid.org/resources/search?q=contribution.agent.id%3A' + id.rstrip() + '&format=json'

for row in input:
    id = row.split(',')[0]
    r = requests.get(build_url(id))
    # if r.json()['hits']['total'] > 0:
    if r.json()['totalItems'] > 0:
        with open("output.csv", "a") as output:
            output.write(row.rstrip() + ", ")
        for entry in r.json()['member']:
            hbzId = entry['hbzId']
            with open("output.csv", "a") as output:
                output.write(" " + hbzId )
        with open("output.csv", "a") as output:
            output.write("\n")
```

I will run this directly against the index when in hbz on Tuesday.

**Comment by acka47** [comment]
With the current script, the holding institutions are missing. I will have to adjust everything and will probably move from csv to reading and writing JSON.

**Comment by acka47** [comment]
Here is the result of the new approach:

1. `$ curl --header "Accept: application/x-jsonlines" "http://lobid.org/gnd/search?q=type%3AUndifferentiatedPerson+AND+_exists_%3AvariantName&size=10" | jq -c ' . | { id: .id, preferredName: .preferredName, variantName: [.variantName[] ] }' > 202002-undifferentiated-with-variantName.ndjson`
2. Python script that creates an ndjson file with a row per `undifferentiatedPerson` that is linked in hbz01:
```py
import requests
import json

filepath = '/home/acka47/git/scripts/202002-undifferentiated-with-variantName.ndjson'
input = open(filepath).readlines()

def build_url(id):
    # return 'https://lobid.org/resources/search?q=contribution.agent.id%3A' + id.rstrip() + '&format=json'
    return 'http://weywot4.hbz-nrw.de:9200/resources/_search?q=_exists_%3AhasItem+AND+contribution.agent.id%3A"' + id.rstrip() + '"&format=json'


for row in input:
     data = json.loads(row.rstrip())
     id = data['id']
     r = requests.get(build_url(id))
     if r.json()['hits']['total'] > 0:
         titles = []
         for entry in r.json()['hits']['hits']:
             title = {}
             hbzId = entry['_source']['hbzId']
             title.update({"hbzId": hbzId})
             owners = []
             for item in entry['_source']['hasItem']:
                 if 'heldBy' in item:
                     owner = item['heldBy']['id']
                     owners.append(owner)
             title.update({"owners": owners})
             titles.append(title)
         data.update({"hasTitle": titles} )
         with open('/home/acka47/git/scripts/result.ndjson', 'a') as fh:
             json.dump(data, fh)
             fh.write("\n")
```

The file contains 489.954 lines/entries, her is an example  (for readability not in one line):

```json
{
    "hasTitle":[
        {
            "owners":[
                "http://lobid.org/organisations/DE-82-611#!"
            ],
            "hbzId":"TT003434389"
        },
        {
            "owners":[
                "http://lobid.org/organisations/DE-82-609#!"
            ],
            "hbzId":"TT003891672"
        },
        {
            "owners":[
                "http://lobid.org/organisations/DE-6-293#!",
                "http://lobid.org/organisations/DE-82-613#!",
                "http://lobid.org/organisations/DE-82-609#!"
            ],
            "hbzId":"TT003479100"
        },
        {
            "owners":[
                "http://lobid.org/organisations/DE-82-609#!"
            ],
            "hbzId":"TT003891671"
        },
        {
            "owners":[
                "http://lobid.org/organisations/DE-6-293#!",
                "http://lobid.org/organisations/DE-82-613#!"
            ],
            "hbzId":"TT003522610"
        },
        {
            "owners":[
                "http://lobid.org/organisations/DE-1010#!",
                "http://lobid.org/organisations/DE-82-613#!"
            ],
            "hbzId":"TT003522609"
        }
    ],
    "variantName":[
        "Leisen, J."
    ],
    "id":"https://d-nb.info/gnd/113684185",
    "preferredName":"Leisen, Josef"
}
```

**Comment by acka47** [comment]
To create a file for bulk indexing in elasticsearch: `$ cat result.ndjson | jq -r '. | "\({ "index":{"_index":"undiff", "_id":(.id / "/") | last} })\n\(.)"' > bulk.ndjson`

To be able to index this big file I had to 

1. add `http.max_content_length: 300mb` to the `/etc/elasticsearch/elasticsearch.yml`
2. and change the following in `jvm.options`: `-Xms4g \ -Xmx4g`

**Comment by acka47** [comment]
As discussed offline. the data is now indexed on the labs-server: http://es.labs.lobid.org/undiff/

Example queries to come.

**Comment by acka47** [comment]
To Do: re-create data with only ISIL in `owner` field and reindex.

**Comment by acka47** [comment]
The ReactiveSearch webapp I was playing around with is at: https://codesandbox.io/s/fervent-banach-0w5ws Unfortunately I don't get any further without putting a lot of more effort into it...

**Comment by acka47** [comment]
Today, I realized that we can build a queryable version of the subset much easier by setting up an index with the subset from lobid-resources and just using the lobid UI. I will provide @dr0i with a list of hbz IDs to set upo the index plus UI.

**Comment by acka47** [comment]
@dr0i, the list with hbz IDs of titles containing links to undifferentiated persons is at https://github.com/acka47/scripts/blob/master/hbzId-undiff.txt.

**Comment by dr0i** [comment]
Metafactures `whitelist` works only if there is a key _and_ a value. This bash script makes the list working:
```bash
rm hbzId-undiff.tsv;
for i in $(cat hbzId-undiff.txt); do 
   echo -e "$i\t$i" >> hbzId-undiff.tsv ;
done
```

@acka47 you may want to perfect your script or we just have to keep in mind to postprocess the list to get a proper tsv for whitelisting with metafacture.
We _could_ enhance metafacture to be more convenient by allowing a simple list, but enhancing `AbstractLookup` and `WhiteList`.

**Comment by dr0i** [comment]
```bash 
$ sort -u /data/DE-605/hbzId-undiff.txt  |wc -l 
1.347.053
```

**Comment by dr0i** [comment]
As doing it with metafacture's `whitelist` produces a `StackOverflowError` (and me not being able to analyze and fix it) I wrote a simple script that look ups the `MabXmlClobs`, writes these as files, tars them and ETL it with the `lobid-resources` metafacture programs. Whole procedure is slow but fast enough, takes ~20h.
Index produced is named `undifferentiatedpersons-staging`
Started the web app of `lobid-resources` at port `7501` configured to use the above mentioned index. Use it like:
http://quaoar1.hbz-nrw.de:7501/resources/search?q=*
which brings up `1.346.866` (which is ~200 lesser than the amount of IDs feeded).
@acka47 please have a look if the result is ok.

**Comment by acka47** [comment]
> @acka47 please have a look if the result is ok.

Can't do because I can not connect to vpn. Please set up proxy, e.g. `http://test-undiff.lobid.org/resources`.

**Comment by dr0i** [comment]
Done, see http://test-undiff.lobid.org/resources/.
However http://test-undiff.lobid.org/resources/api isn't working but I think it's not important, yes?

**Comment by acka47** [comment]
> However http://test-undiff.lobid.org/resources/api isn't working but I think it's not important, yes?

You are right, it is not important.

**Comment by acka47** [comment]
I made the same error here as mentioned in https://github.com/hbz/lobid/issues/417#issuecomment-613378271, however, it won't make such a big difference in this case. Anyway, I will create a new list of hbz IDs for re-creating the index.

**Comment by acka47** [comment]
I talked to Brigitte and we have to scrap  the whole lobid-resources approach. There are only five libraries anyway who want to use this:

> - ULB Bonn inkl. Institute (ISIL DE-5 + DE-5-*)
> - ULB Düsseldorf (ISIL DE-61)
> - UB Trier (ISIL DE-385)
> - Kunst- und Museumsbibliothek der Stadt Köln (ISIL DE-Kn3)
> - LBZ (ISIL DE-107 + DE-929)

Thus, I will adjust the script from https://github.com/hbz/lobid/issues/411#issuecomment-582481505 to filter by holding institution and to create a csv with person name, variant name plus hbz ids.

**Comment by dr0i** [comment]
Does this mean we can delete the index and the play instance?

**Comment by acka47** [comment]
> Does this mean we can delete the index and the play instance?

Yes

**Comment by dr0i** [comment]
Removed from apache config, from monit, and removed repo deployment at quaoar1.

**Comment by acka47** [comment]
I sent csv files to B.B. covering DE-61, DE-385 and DE-Kn3:

- [ ] ULB Bonn inkl. Institute (ISIL DE-5 + DE-5-*)
- [x] ULB Düsseldorf (ISIL DE-61)
- [x] UB Trier (ISIL DE-385)
- [x] Kunst- und Museumsbibliothek der Stadt Köln (ISIL DE-Kn3)
- [ ] LBZ (ISIL DE-107 + DE-929)

**Comment by acka47** [comment]
Finished for all libraries that asked for it and sent to B.B. Closing.
