### ISSUE TITLE
Redirect issue

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid#416]
http://lobid.org/team gives JSON

http://lobid.org/team/ seems to redirect to http://lobid.org/team but gives HTML

**Comment by dr0i** [comment]
This seems to be intended, see https://github.com/hbz/lobid/issues/359#issuecomment-566490142: 

> RewriteRule ^/team$ /team.json [L,P]

But for me it also looks also strange (now). Changed the behavior by removing the rule.

**Comment by acka47** [comment]
+1 Closing
