### ISSUE TITLE
Provide possibility to search for resources with links to persons whose deathDate is 1949 or earlier

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#417]
For libraries to check for out-of-copyright material to be scanned & published on the web. Very similar to #411.

**Comment by acka47** [comment]
The process

- [x] 1.) Create [list of GND IDs for all persons with death date 1949 or earlier](https://github.com/acka47/scripts/blob/master/gndPersonsDeadBefore1949.txt): `$ curl --header "Accept: application/x-jsonlines" "http://lobid.org/gnd/search?q=dateOfDeath%3A%5B*+TO+1949-12-31%5D" | jq -r .gndIdentifier > gndPersonsDeadBefore1949.txt`
- [ ] 2.) Create list of hbzIds for titles linking to GND persons from list created in step 1: [script(ttps://github.com/acka47/scripts/blob/master/gnd-ids-in-hbz01.py), [result](tba)
- 3.) [ ] Build index based on hbzId list created in 2.)
- 4.) [ ] Set up lobid-resources UI to query index from 3.)

**Comment by acka47** [comment]
@dr0i übernehmen Sie. The list of hbz IDs comprises 556,223 titles and is at https://github.com/acka47/scripts/blob/master/gemeinfrei.txt.

**Comment by acka47** [comment]
I just noticed made an error in the script as I only pulled 15 titles (default) per person. However, I noticed that we actually don't need a separate index for this as the death date of a contributing person is included in lobid-resources. Thus, I can easily get the list of titles with contributors who have died >70 years ago and can also filter out online resources (i.e. this that already have been scanned):

[`contribution.agent.dateOfDeath:[* TO 1949] AND NOT medium.id:"http://rdaregistry.info/termList/RDACarrierType/1018"`](http://lobid.org/resources/search?q=contribution.agent.dateOfDeath%3A%5B*+TO+1949%5D+AND+NOT+medium.id%3A%22http%3A%2F%2Frdaregistry.info%2FtermList%2FRDACarrierType%2F1018%22)

**Comment by acka47** [comment]
And this is the query that also filters out those resources that have another contributor that has not been yet for >= 70 years: [`contribution.agent.dateOfDeath:[* TO 1949] AND NOT contribution.agent.dateOfDeath:[1950 TO *] AND NOT medium.id:"http://rdaregistry.info/termList/RDACarrierType/1018"`](http://lobid.org/resources/search?q=contribution.agent.dateOfDeath%3A%5B*+TO+1949%5D+AND+NOT+contribution.agent.dateOfDeath%3A%5B1950+TO+*%5D+AND+NOT+medium.id%3A%22http%3A%2F%2Frdaregistry.info%2FtermList%2FRDACarrierType%2F1018%22)

@dr0i, please check out whether we can make a rewrite rule that adds this filter.

**Comment by dr0i** [comment]
The rewriteRule could be added and it works, but up to date only partially:
http://publicdomain.lobid.org/resources/search?q=hut
Most annoying: facets not working. This is mandatory to work, I assume?

**Comment by acka47** [comment]
> facets not working. This is mandatory to work, I assume?

Yes, I suggested to just use lobid and write a blog post on how to search for public domain resources held by a specific institution. I think that should be sufficient.

**Comment by acka47** [comment]
The blog post was published today, see http://blog.lobid.org/2020/04/27/gemeinfreie-titel-finden.html. I am also in contact with UB Wuppertal that apparently is most interested in this and will help out when they have questions. Closing this issue.
