### ISSUE TITLE
Add bio of team members

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#420]
Add `description` blob of short bio of team members (http://lobid.org/team).
Good to be linked from slides etc.

**Comment by dr0i** [comment]
See e.g. https://lobid.org/team/ap#!.

- Member's page are currently not buildt with gatsbys's graphql. And, to be clear, to implement this would take some time. But it may make some sense, especially because:
- there is only one language page for each `member'.  We would have to think about the structure, resp. we should copy the structure we use for the multi-language team-site:
-- the default URl would be "https://lobid.org/team/ap#!", it would serve English
-- the English URL would be https://lobid.org/team/ap-en#!
-- the German URL would be https://lobid.org/team/ap-de#!
-- when using content negotiation to get jsonld, all these URIs should serve the same file
(see https://github.com/hbz/lobid/issues/395 regarding language of the team site)

**Comment by acka47** [comment]
+1 Closing
