### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid#433]
We decided to migrate our projects from Travis CI to GitHub Actions ([some background](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-work)).

- [x] Prioritize the projects below by creating and assigning individual issues
- [ ] Evaluate if something like https://github.com/rosineygp/mkdkr is useful for us

Projects to be migrated include ([see all](https://github.com/search?q=org%3Ahbz+org%3Ametafacture+org%3Askohub-io+filename%3A.travis.yml&type=code)):

(mostly) Java-based builds | Travis build | Issue/PR | GitHub build
---------------- | ---------------- | -------- | -------------
https://github.com/hbz/lobid-resources | [![Build status](https://travis-ci.org/hbz/lobid-resources.svg?branch=master)](https://travis-ci.org/hbz/lobid-resources) | https://github.com/hbz/lobid-resources/pull/1104|[![](https://github.com/hbz/lobid-resources/workflows/Build/badge.svg?branch=master)](https://github.com/hbz/lobid-resources/actions?query=workflow%3ABuild)|
https://github.com/metafacture/metafacture-core | [![Build status](https://travis-ci.org/metafacture/metafacture-core.svg?branch=master)](https://travis-ci.org/metafacture/metafacture-core) |https://github.com/metafacture/metafacture-core/issues/351 |![](https://github.com/metafacture/metafacture-core/workflows/Build/badge.svg?branch=master) |
https://github.com/metafacture/metafacture-fix | [![Build status](https://travis-ci.org/metafacture/metafacture-fix.svg?branch=master)](https://travis-ci.org/metafacture/metafacture-fix) | - | [![](https://github.com/metafacture/metafacture-fix/workflows/Build/badge.svg?branch=master)](https://github.com/metafacture/metafacture-fix/actions?query=workflow%3ABuild) |
https://github.com/metafacture/metafacture-flux | [![Build status](https://travis-ci.org/metafacture/metafacture-flux.svg?branch=master)](https://travis-ci.org/metafacture/metafacture-flux) | https://github.com/metafacture/metafacture-flux/issues/5 | [![](https://github.com/metafacture/metafacture-flux/workflows/Build/badge.svg?branch=main)](https://github.com/metafacture/metafacture-flux/actions?query=workflow%3ABuild)|

(mostly) Play-based builds | Travis build | Issue/PR | GitHub build
------------ | ------------- | ------------- | -------------
https://github.com/hbz/nwbib | [![Build status](https://travis-ci.org/hbz/nwbib.svg?branch=master)](https://travis-ci.org/hbz/nwbib) | https://github.com/hbz/nwbib/issues/566 | [![Build status](https://github.com/hbz/nwbib/workflows/Build/badge.svg?branch=master)](https://github.com/hbz/nwbib/actions?query=workflow%3ABuild) |
https://github.com/hbz/lobid-gnd | [![Build status](https://travis-ci.org/hbz/lobid-gnd.svg?branch=master)](https://travis-ci.org/hbz/lobid-gnd) |https://github.com/hbz/lobid-gnd/issues/279 | [![Build status](https://github.com/hbz/lobid-gnd/workflows/Build/badge.svg?branch=master)](https://github.com/hbz/lobid-gnd/actions?query=workflow%3ABuild)|
https://github.com/hbz/mabxml-elasticsearch | [![Build status](https://travis-ci.org/hbz/mabxml-elasticsearch.svg?branch=master)](https://travis-ci.org/hbz/mabxml-elasticsearch) |https://github.com/hbz/mabxml-elasticsearch/issues/55 | [![Build status](https://github.com/hbz/mabxml-elasticsearch/workflows/Build/badge.svg?branch=master)](https://github.com/hbz/mabxml-elasticsearch/actions?query=workflow%3ABuild)|
https://github.com/hbz/lobid-organisations | [![Build status](https://travis-ci.org/hbz/lobid-organisations.svg?branch=master)](https://travis-ci.org/hbz/lobid-resources) | https://github.com/hbz/lobid-organisations/issues/441|[![Build status](https://github.com/hbz/lobid-organisations/workflows/Build/badge.svg?branch=master)](https://github.com/hbz/lobid-organisations/actions?query=workflow%3ABuild)|

(mostly) Node-based builds | Travis build | Issue/PR | GitHub build
------------ | ------------- | ------------- | -------------
https://github.com/hbz/lobid ([gatsby](https://github.com/hbz/lobid/tree/master/gatsby/lobid)) | [![Build status](https://travis-ci.org/hbz/lobid.svg?branch=master)](https://travis-ci.org/hbz/lobid) |  https://github.com/hbz/lobid/issues/435|[![Build status](https://github.com/hbz/lobid/workflows/Build/badge.svg?branch=master)](https://github.com/hbz/lobid/actions?query=workflow%3ABuild)|
https://github.com/skohub-io/skohub-pubsub | [![Build status](https://travis-ci.org/skohub-io/skohub-pubsub.svg?branch=master)](https://travis-ci.org/skohub-io/skohub-pubsub) | https://github.com/skohub-io/skohub-pubsub/pull/42 |[![](https://github.com/skohub-io/skohub-pubsub/workflows/Build/badge.svg?branch=master)](https://github.com/skohub-io/skohub-pubsub/actions?query=workflow%3ABuild)|
https://github.com/skohub-io/skohub-vocabs | [![Build status](https://travis-ci.org/skohub-io/skohub-vocabs.svg?branch=master)](https://travis-ci.org/skohub-io/skohub-vocabs) |https://github.com/skohub-io/skohub-vocabs/pull/131 |[![](https://github.com/skohub-io/skohub-vocabs/workflows/Build/badge.svg?branch=master)](https://github.com/skohub-io/skohub-vocabs/actions?query=workflow%3ABuild)|
https://github.com/dini-ag-kim/lrmi-profile | [![Build status](https://api.travis-ci.org/dini-ag-kim/lrmi-profile.svg?branch=master)](https://travis-ci.org/dini-ag-kim/lrmi-profile) | https://github.com/dini-ag-kim/lrmi-profile/issues/51 |[![Build status](https://github.com/dini-ag-kim/lrmi-profile/workflows/Build/badge.svg?branch=master)](https://github.com/dini-ag-kim/lrmi-profile/actions?query=workflow%3ABuild) |

**Comment by acka47** [comment]
There also is https://github.com/dini-ag-kim/lrmi-profile where we use Travis with a bash script.

**Comment by katauber** [comment]
The migration of a project to GitHub Actions is done, when the field 'GitHub Build' is filled with the working build.

**Comment by dr0i** [comment]
I think we are good here, but I don't think any of us had

> Evaluate if something like https://github.com/rosineygp/mkdkr is useful for us

so I reassign @fsteeg to either remove it or else make an issue of itself to be able to close this issue.

**Comment by acka47** [comment]
Re.

> Evaluate if something like https://github.com/rosineygp/mkdkr is useful for us

This ship has sailed as we set up GitHub Actions directly. So this should be no reason to leave the issue open.

**Comment by dr0i** [comment]
Great! Closing.
