### ISSUE TITLE
Provide a list with lobid's used geodata 

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#436]
A.D. wrote:
> ich bastele zwischendurch noch am Tileserver mit Umfang komplette Erde rum.
Dazu eine Frage:
Kannst Du mir eine Liste generieren, in der alle für Euch relevanten Objekte enthalten sind?
Gut wäre eine Textdatei in der Form:
Breite, Länge (N/O positiv, S/W negativ) also etwa in der Art:
51.012345,7.98765
49.25,-123.456

I think we can omit lobid-resources, because these are only about Germany?
Interesting data would be `lobid-gnd` and `lobid-organisations`.
(although I wonder: if any new geodata will come to the data, what would become of it - no tiles in this case?)

Originates from https://github.com/hbz/lobid/issues/309.

**Comment by acka47** [comment]
I think the most geo coordinates from around the world are in GND so I start with this. Geodata is offered in lobid-gnd like this:

```json
{
  "hasGeometry": [
    {
      "type": "Point",
      "asWKT": [
        "Point ( +012.341666 +051.403333 )"
      ]
    }
  ]
}

``` 

Currently, there are [nearly 60k entries with geo coordinates](https://lobid.org/gnd/search?q=_exists_%3AhasGeometry.asWKT). You can get them in bul with `$ curl --header "Accept: application/x-jsonlines" "https://lobid.org/gnd/search?q=_exists_%3AhasGeometry.asWKT" > geo-gnd.json` and then filter the geo coordinates out with jq:

`$ cat geo-gnd.json | jq .hasGeometry[].asWKT[] > gnd-coordinates.txt` 

I uploaded the results into a gist: https://gist.github.com/acka47/97a1b60f1bfacd536cc361d92bc3695d

This isn't the format A.D. asked for but I think he should be able to work with it. Not that, there are 44 Polygons in there that look a bit different than the point information, e.g. https://gist.github.com/acka47/97a1b60f1bfacd536cc361d92bc3695d#file-gnd-coordinates-txt-L70.

**Comment by dr0i** [comment]
Great , thx! Format sufficient. IT neede it to precalculate the tiles to be able to serve them performantly.
See https://lobid.org/gnd/4064682-8.
Closing.
