### ISSUE TITLE
Update team page for new data format

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid#437]
Update http://lobid.org/team

Using the files in https://github.com/hbz/lobid/tree/432-jsonSchemas/examples

- [x] Team page itself
- [x] Individual member pages
- [x] Names and images from person files in main team page
- [x] Avoid duplicate queries for localized team pages (de, en)

Current state is deployed at http://stage.lobid.org/team

**Comment by fsteeg** [comment]
Deployed to http://stage.lobid.org/team

**Comment by acka47** [comment]
Already looks quite good. I noticed that the images on individual profile pages do not look good on mobile/in protrait format:

![image](https://user-images.githubusercontent.com/160292/109794020-b2bfbe00-7c15-11eb-9717-5c2f811d30bc.png)

**Comment by fsteeg** [comment]
Redeployed to http://stage.lobid.org/team

**Comment by acka47** [comment]
Now there is another image-related problem, see http://stage.lobid.org/team/ap#! (I think I have a déjà vu):

![image](https://user-images.githubusercontent.com/160292/109808143-0c7cb400-7c27-11eb-9b32-4c05396ec224.png)

**Comment by fsteeg** [comment]
Ah, and yours has the other problem on production: http://lobid.org/team/ap#!

**Comment by fsteeg** [comment]
Redeployed to http://stage.lobid.org/team
