### ISSUE TITLE
Support querying with different ISBN & ISSN variants 

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#44]
On the data level, we should omit the `bibo:isbn13` property and only use `bibo:isbn` with the different variants.

Example queries that should yield the same results:
- http://test.lobid.org/resource?id=978-3518461983, http://test.lobid.org/resource?id=9783518461983, http://test.lobid.org/resource?id=978-3-518-46198-3, http://test.lobid.org/resource?id=978%203%20518%2046198%203
-  http://test.lobid.org/resource?id=3-517-01410-9, http://test.lobid.org/resource?id=3517014109, http://test.lobid.org/resource?id=3%20517%2001410%209
- http://test.lobid.org/resource?id=0-7391-7460-6, http://test.lobid.org/resource?id=978-0-7391-7460-9 (currently not indexed, must index newer full dump first, see #43.)

**Comment by dr0i** [comment]
Deployed to staging, see e.g. http://test.lobid.org/resource?id=00-283-07x,  http://test.lobid.org/resource?id=00-28307x, http://test.lobid.org/resource?id=0028307x. Sugar no more unhealthy :)

**Comment by acka47** [comment]
works with and without hyphens but spaces aren't supported, e.g. http://test.lobid.org/resource?id=00%20283%2007x

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
