### ISSUE TITLE
`stage.`-URIs on production

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#475]
See http://lobid.org/team.json:

```json
{

    "@context": "https://schema.org",
    "id": "http://stage.lobid.org/team#!"
}
```

**Comment by fsteeg** [comment]
I don't think we have any mechanism in our Gatsby setup for replacing these on prod/stage es we do for the Play-based lobid instances. Maybe we can simply switch the data to production ids? (see https://github.com/hbz/lobid/blob/master/gatsby/lobid/static/team.json).
