### ISSUE TITLE
Use Mastodon instead of Twitter in footer

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#483]
Currently: 

![image](https://user-images.githubusercontent.com/160292/203762268-476c958a-1949-4bce-b904-bc441b8e8436.png)

We should either replace the Twitter link with Mastodon or show both.

**Comment by dr0i** [comment]
Can we close ? All (?!) repos free from Twitter but metafacture.org (has both).

**Comment by acka47** [comment]
Yes, closing.
