### ISSUE TITLE
lobid.org not valid html

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#497]
https://validator.w3.org/nu/?doc=http%3A%2F%2Flobid.org%2F

Because of this firefox complains with "Content Encoding Error" when opening the view-source (view-source:http://lobid.org/)

**Comment by Phu2** [comment]
The `index-en` and `index-de` files do not have any extensions. Our webserver doesn't provide the `Content-Type` http header for these files and makes Firefox complaining. Directive added to the Apache vhost config:

```
+                # matches eg. index-en, index-de files without extension
+                <FilesMatch "^index[^.]+$">
+                        ForceType text/html
+                </FilesMatch>
```
Now the "Content Encoding Error" is gone.
And the HTML validator now outputs three real errors:

> A meta element with an http-equiv attribute whose value is X-UA-Compatible must have a content attribute with the value IE=edge.
> Self-closing syntax (/>) used on a non-void HTML element. Ignoring the slash and treating as a start tag.
> Stray end tag span.
