### ISSUE TITLE
Team members page RDF link is broken

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#501]
E.g. at https://lobid.org/team/pc/#!  clicking on the RDF  icon -> https://lobid.org/team/6e724707-1763-5317-96c5-de977faa1b.json (which doesn't exist). 

Cause is the same like https://github.com/hbz/lobid/issues/498.

**Comment by kaena83** [comment]
May this ticket be wronlgy placed in metadaten.nrw?

**Comment by acka47** [comment]
> May this ticket be wronlgy placed in metadaten.nrw?

It was somehow added to the project board but is in the correct repo (hbz/lobid).I removed it from the Kanban board.
