### ISSUE TITLE
Add usage policy and warranty to lobid webpage

### ISSUE THREAD

**Issue by kaena83** [hbz/lobid#505]
The new usage policy and warranty for lobid should be included in the lobid web page. For this, several changes have to be made. Have a look into [Figma ](https://www.figma.com/file/0nQKfHAgc2q8Jw8MZiA3EM/lobid---Nutzungspolicy?type=design&node-id=0%3A1&mode=design&t=fnFgNPaHnRQ99Y9X-1) in doubt. The modifications encompass 4 main points (see below).

**1. New page for usage policy**

- [x] Create a new page for the usage policy using the URL http://lobid.org/usage-policy
- [x] Take the text of the usage policy from [here](https://pad.gwdg.de/qcP24el5QpelYvQApsqsug?view)

**2. New page for warranty**

- [x] Create a new page for the warranty using the URL http://lobid.org/warranty
- [x] Take the text of the warranty from [here](https://pad.lobid.org/RUCamfjZQw6FijTpqoQlXA?view)

**3. Modify the lobid start page**

- [x] Include a link to usage policy under icon "i" using the title "Richtlinien API-Nutzung". This should link to http://lobid.org/usage-policy.
- [x] Include "Gewährleistung" in the menu below. This should link to http://lobid.org/warranty
- [x] To create more space for the menu below, shorten the existing text "lobid | LOD-Dienste des [hbz — Hochschulbibliothekszentrum des Landes NRW](https://www.hbz-nrw.de/produkte/linked-open-data)" to "lobid — ein Dienst des [hbz](https://www.hbz-nrw.de/produkte/linked-open-data)"

![grafik](https://github.com/hbz/lobid/assets/119848543/b56ba581-9680-4372-80a9-de66042d140b)

**4. Modify the API documentation for each lobid service [(lobid-organisations](http://lobid.org/organisations/api/de), [lobid-resources](http://lobid.org/resources/api), [lobid-gnd).](http://lobid.org/gnd/api).**

- [ ] Include a colored note box at the top of each page, stating in bold "Technische und sonstige Hinweise zur lobid-Nutzung finden sich in den [Richtlinien zur API-Nutzung](http://lobid.org/usage-policy).". "Richtlinien zur API-Nutzung" should link to http://lobid.org/usage-policy.
- [ ] Include an information icon left to the text within the note box.

![grafik](https://github.com/hbz/lobid/assets/119848543/d54b2e16-e15c-4116-aeaa-56e4e20da6ec)

**Comment by Phu2** [comment]
Do we have english versions of the usage policy and warranty already?
For example, linking from http://lobid.org/organisations/api/en to the german usage policy does not meet the users expectation.

**Comment by kaena83** [comment]
No not yet as far as I know. I suggested that too. I put it on the agenda.

**Comment by acka47** [comment]
Not deployed yet. Reopening

**Comment by kaena83** [comment]
@Phu2 This looks all fine too me. Two things concerning the texts, perhaps @acka47 can give a feedback too:

1. There are currently three headers in the beginning of the usage policy http://stage.lobid.org/usage-policy/. Maybe we could delete one of them, e.g. "Richtlinien einer rücksichtsvollen lobid-Nutzung"? (also see Screenshot below)
2. Maybe we could additionally include the warranty in the usage policy? That is, users of the API would not have to look for it separately. Likely they will not think of it.



![Image](https://github.com/hbz/lobid/assets/119848543/b54570d6-5e71-458d-9ed4-6fa74ca142fa)

**Comment by acka47** [comment]
> There are currently two headers for the usage policy http://stage.lobid.org/usage-policy/. Maybe we could delete one of them, e.g. "Richtlinien einer rücksichtsvollen lobid-Nutzung"? (also see Screenshot below)

+1 IMO, we should replace "Richtlinien API-Nutzung" on top by "Richtlinien einer rücksichtsvollen lobid-Nutzung"

Looking into this, I currently see four `<h1>` headers. At least from Markdown I know that this is not good practice to habve more than one level 1 headiong (see e.g. https://google.github.io/styleguide/docguide/style.html#document-layout).

So, my suggestion would be to have only one `h1``on top, remove the h1 below the toc and make the other h1 h2s (and the sub headings h3 then).

> Maybe we could include the warranty additionally in the usage policy? That is, users of the API would not have to look for it separately. It´s not very likely that they will actively look for it in the menu at the end of the page.

A link to the warranty would do it for me. Reading the warranty again I am not satisfied with the structure. E.g. I think the sentence "lobid ist nicht selbst Urheber der angebotenen Daten, sondern aggregiert und transformiert lediglich Informationen aus offenen und freien Quellsystemen Dritter." should come much earlier, maybe even as first sentence. But we can also rewrite this at a later stage.

**Comment by Phu2** [comment]
What about the last paragraph "Empfehlungen zur Verbesserung des lobid-Angebots"? It sounds like a note to ourselves and not addressed to users.

**Comment by Phu2** [comment]
The anchor links don't work. We need to install and configure the sub-plugin https://www.gatsbyjs.com/plugins/gatsby-remark-autolink-headers/

**Comment by Phu2** [comment]
@kaena83 @acka47 Redeployed to http://stage.lobid.org/usage-policy/ with headings restructured and working anchor links. 
Do you want to add the link to the warranty? Please do as you like: https://github.com/hbz/lobid/blob/505-fix-usage-policy/gatsby/lobid/static/pages/usage-policy.md and review the last paragraph as i mentioned [earlier](https://github.com/hbz/lobid/issues/505#issuecomment-1727006084)
Then i will deploy to stage and production. After that i will add the links from the other lobid pages (task 4. in the description).

**Comment by kaena83** [comment]
> What about the last paragraph "Empfehlungen zur Verbesserung des lobid-Angebots"? It sounds like a note to ourselves and not addressed to users.

This is true.

**Comment by kaena83** [comment]
Alright, I delete it.

**Comment by Phu2** [comment]
Again redeployed to http://stage.lobid.org/usage-policy/ 
@kaena83 @acka47 ready to go live? The link to http://lobid.org/warranty will be functioning afterwards.

**Comment by acka47** [comment]
> ready to go live?

Yes, thanks.

**Comment by kaena83** [comment]
Ready.

**Comment by kaena83** [comment]
Ready.

**Comment by Phu2** [comment]
Deployed to production https://lobid.org/. Links from other lobid services will follow soon.
