### ISSUE TITLE
Change of language in footer and header (GER to EN)

### ISSUE THREAD

**Issue by kaena83** [hbz/lobid#510]
Both the footer and header jump from German to English when

1. clicking "Gewährleistung" in the **footer** on the following pages:

- https://lobid.org/
- http://test.lobid.org/organisations
- http://test.lobid.org/organisations/api/de
- http://test.lobid.org/resources
- http://test.lobid.org/resources/api

2. clicking "Richtlinien zur API-Nutzung" in the "i"-menu of the [lobid start page](https://lobid.org/)

![grafik](https://github.com/hbz/lobid-organisations/assets/119848543/7c7c762f-7f50-42dc-977f-6de0ce7dd48b)

3. clicking "Richtlininen zur API-Nutzung" in the info box at top of the pages

- http://test.lobid.org/organisations/api/de
- http://test.lobid.org/resources/api

**Comment by Phu2** [comment]
I think the newly created pages

- http://lobid.org/usage-policy/
- http://lobid.org/warranty/

are somehow / per default in the english context of the site. As only german versions are available atm, i will put them in the german context.

**Comment by Phu2** [comment]
Deployed to
- http://stage.lobid.org/usage-policy/
- http://stage.lobid.org/warranty/

@kaena83 Please have a look
