### ISSUE TITLE
Provide api health overview

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#523]
Add an api health overview. Provide a bit of status history.

**Comment by dr0i** [comment]
Discussed with @Phu2 : using `monit` to a) push-wise be informed when something changes and b) reuse monit's html view.
Revisioned in internal git daemon at gaia.

**Comment by dr0i** [comment]
- [x]  q3 as server: must be able to receive mails
- [x]  configure  /etc/mail/aliases to write monit mails into an file on its own
- [ ] configure monit rc's(`/etc/monit/conf.d/*.rc`) to also write to q3 (by just repeating "alert $mailadress")
- [ ] write script that watches changes on the inbox
- [ ] if changes on the inbox appear, get the server's monit html views and ETL them into one view and copy them to https://lobid.org/apihealth/index.html

**Comment by acka47** [comment]
There exists some FOSS software for this. Have you checked or isn't that useful for us. Examples:

- Cachet: https://github.com/cachethq
- gatus: https://github.com/TwiN/gatus
- Vigil: https://github.com/valeriansaliou/vigil

**Comment by dr0i** [comment]
Simple api health site is ready: https://lobid.org/apihealth/

Re other software: dont' fit in our environment (re `monit`), complex.
One thing that would bring more flexibility in building the HTML:
There is an API that provides XML , called like `curl -u name:passwd localhost:2812/_status?format=xml` .
Using this XML would make it easier to build a more elegant view.

**Comment by dr0i** [comment]
Announced in https://metadaten.community/t/api-health-seite/253.
Closing.
