### ISSUE TITLE
Set up monitoring of data workflow on status.lobid.org

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#57]
The current workflow being:

changes/addition of record via Aleph client ->  
daily generating of AlephXML clobs -> 
files to webserver ->
copy into file system ->
transformation flux ->
Mysql_DB ->
Dump into HDFS ->
Conversion to JSON & indexing into elasticserch ->
API adjustments (if needed, e.g. JSON LD context, HTML, NWbib ...)

We have to set up monitoring for (all? some?) of these steps.

**Comment by acka47** [comment]
Won't fix this for API 1.0, I hope we have this covered for 2.0, though... Closing.

**Comment by acka47** [comment]
@dr0i As @fsteeg just said in the standup, this might be a thing we should consider for lobid 2.0, especially as more and more users and applications depend on it and we should guarantee a stable production service. What do you think?

**Comment by acka47** [comment]
We decided to create a status page. We need  one for lobid.org (at status.lobid.org) with an overview over all services and I adjusted the issue title accordingly.

I don't  think we need separate status pages for each service (status.lobid.org/resources etc.) but will have a section for each service (status.lobid.org#resources).

**Comment by dr0i** [comment]
I think it would make sense to hold a daily  updated status of about one week? I think these status infos make sense: 
- [ ] getting and publishing of `alephXmlClobs`
- [ ] etl of the updates of the resources of `alephXmlClobs`

Wouldn't that be enough? @acka47 don't know how 

> API adjustments (if needed, e.g. JSON LD context, HTML, NWbib ...)

could look like?

**Comment by dr0i** [comment]
> collection went don't

"connection went down" I guess , you fuzzy

I thinks when our connection brakes we don't need a status info page anyway? I mean, you see the status page is gone, you know something's wrong, right?
As we have already mails informing us what about what we want to see at the status the todo is to just gather the mails, make a simple table and publish that as a website.

**Comment by ChristophEwertowski** [comment]
The status page is meant for external users, isn't it? Otherwise we could simply read our mails ;)
