### ISSUE TITLE
Remove rdamediatype:1005 from morph

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#68]
Obviously, we reuse the two different medium types `rdacarriertype:1050` ([video carriers](http://rdvocab.info/termList/RDACarrierType/1050)) and `rdamediatype:1005` ([projected](http://rdvocab.info/termList/RDAMediaType/1005)) redundantly. 

See:
```
$ curl "http://lobid.org/resource?q=*&medium=http%3A%2F%2Frdvocab.info%2FtermList%2FRDACarrierType%2F1050" | json_pp | grep totalResults
      "http://sindice.com/vocab/search#totalResults" : 12253,
$ curl "http://lobid.org/resource?q=*&medium=http%3A%2F%2Frdvocab.info%2FtermList%2FRDAMediaType%2F1005" | json_pp | grep totalResults
      "http://sindice.com/vocab/search#totalResults" : 12253
```
Thus, we can dicard one of these. As a lot of resources typed with these are VHS tapes we shouldn't use "projected" and drop it. The respective line in the morp is [295](https://github.com/lobid/lodmill/blob/b1732a6650d9a91abda76e54bc7292ee4f914c02/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L295).

**Comment by dr0i** [comment]
Merged into master. Will be completely deployed when completely reindexed , doen at the weekend. Closing now.
