### ISSUE TITLE
IDs indexed as lowercase cannot be found

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#72]
As mentioned in #69 e.g.  the URN field is used with the id_analyzer when indexed and thus be lowercased. While the URN in http://lobid.org/resource/HT016344563 is in part uppercase and querying this URN with the caputal N will fail.

What to do ? Remove the `id_analyzer` or pre-process all ID-querioes to lowercase?

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
