### ISSUE TITLE
Missing subject chains

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid#82]
Based on NWBib feedback mail, 2014-11-07, VA.

Missing subject chains resulting in missing hits, e.g.:

http://lobid.org/resource?id=BT000120805&format=full
http://lobid.org/resource?id=BT000120805&format=source

http://lobid.org/resource?id=BT000111451&format=full
http://lobid.org/resource?id=BT000111451&format=source

**Comment by dr0i** [comment]
Seems to be solved with #122. @acka47 please ACK and close if +1.

**Comment by acka47** [comment]
ACK. Closing.
