### ISSUE TITLE
Missing fulltextOnline link

### ISSUE THREAD

**Issue by acka47** [hbz/lobid#85]
Example: http://lobid.org/resource/HT014063180

**Comment by dr0i** [comment]
@acka47 : the problem seems to be gone (don't know what made it gone, though). Following the resource you provided there is only an "Online" mentioned in subject chains.

**Comment by acka47** [comment]
Made the issue title clearer.

Regarding the [first example](http://lobid.org/resource/HT014063180/about), the link provided in the [source](http://lobid.org/resource?id=HT014063180&format=source) in field 655 can't be found in the RDF.

The [second example]() is a special case where'actually no link to the fulltext exists in the source as it was deleted in 2013. (See the note in field 573 of the [source](http://lobid.org/resource?id=HT015644020&format=source): "355!URL mit z LF+EZB-Frontdoor gelöscht(25-04-13)".)

**Comment by acka47** [comment]
This is a duplicate of #489, thus closing and moving the examples there.
