### ISSUE TITLE
Please create mapping for Mab 655e

### ISSUE THREAD

**Issue by jschnasse** [hbz/lobid#99]
e.g.: http://lobid.org/resource/TT002234459/about

TT002234459 describes an archived web page. The url of the archived page is stored in MAB 655e which currently does not exist in the lobid data. 

priority in edoweb: high

**Comment by dr0i** [comment]
ping @jschnasse

**Comment by dr0i** [comment]
Deployed even to production. @jschnasse have a look and rise some thumbs if it does what it should.

**Comment by acka47** [comment]
What's missing: Add `lv:webPageArchived` to the JSON-LD context. Will do.

**Comment by jschnasse** [comment]
test import is running. looks good so far! Many thx.

**Comment by jschnasse** [comment]
+1

**Comment by acka47** [comment]
We obiously overshot the mark here by typing all Edoweb resources `lv:ArchivedWebPage`. Only resources with a URL in 655e should be typed as such as reported by @jschnasse . That's why I re-opened this issue.

**Comment by dr0i** [comment]
Here I need an example resource. HT014997977, HT018433961 and TT002234459 are in the samllest test set and they _are_ proper ArchivedWebPages.

**Comment by acka47** [comment]
Examples: [HT018585406](http://lobid.org/resource/HT018585406), [HT018585452](http://lobid.org/resource/HT018585406), [HT018585477](http://lobid.org/resource/HT018585477).

See also this JIRA issue: https://jira.hbz-nrw.de/browse/EDOZWO-480.

**Comment by dr0i** [comment]
So even if 652 states that it's about an "archivierte online resource" it's not (necessarily).
(A librarian's rose can be anything.)

**Comment by dr0i** [comment]
@acka47 you may be satisfied with having a look at the [ntriples in the outcome of the new transformation in the smallest test set](https://github.com/lobid/lodmill/blob/issue-lobid-99-missingArchivePageUrl/lodmill-rd/src/test/resources/hbz01.nt) (spares me the deploying to staging)  . Look at `HT018585406`. Now this resource is no more of type `lv:ArchivedWebPage`.

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
@jschnasse just let me know that we will have to inform @literarymachine as soon as this is deployed on production.

**Comment by literarymachine** [comment]
Thanks! Team lunch communication. Better than any ticketing system.

**Comment by acka47** [comment]
In this case, @jschnasse used the other ticketing system (JIRA) to communicate this. Lunch was good and very sunny, though.

**Comment by acka47** [comment]
@dr0i The latest fix (i.e. only type resources as `lv:ArchivedWebPage` that have  with a URL in 655e) hasn't been deployed to production yet. See http://lobid.org/resource/HT018585406 which should NOT be of type `lv:ArchivedWebPage`.

**Comment by dr0i** [comment]
In the meantime (at 20150415) the metadata of the resource has changed , i.e. e.g. http://lobid.org/resource/HT018585406 has an URL in 655e in thus is (correctly) of type `lv:ArchivedWebPage`.
The principle mechanism coded with https://github.com/lobid/lodmill/commit/ed809ffe4ef9f6d7f500525a5f93d0953b313b93 to exclude the type `lv:ArchivedWebPage` if there is *no* 655e *is also* working , as the unit tests don't bring up this type when working on old HT018585406's  metadata (where 655e *wasn't* configured).  
Other resources have changed their metadata also, at least that's true for HT018585477.

**Comment by dr0i** [comment]
Deployed to staging and production (since yesterday with lobid/lodmill#669).

**Comment by acka47** [comment]
@jschnasse Can you point me to a current example of an edoweb resource _without_ a URL in 655e?

**Comment by acka47** [comment]
Just talked to @jschnasse . This issue has gotten a bit out of hand. We decided to completely revert the addition of type `v:ArchivedWebPage` (i.e. no resource at all shall be typed as such) and stick to the issue title which we already have reached (i.e. adding the URL of the web page that has been archived to the RDF.

We may get the information whether something is an archived web page from MAB field 051, element 1, see e.g. http://lobid.org/resource?id=TT002234459&format=source where there's a `w` in element 1:
`<controlfield tag="051">mw||||||</controlfield>`.

**Comment by jschnasse** [comment]
Hi, just to clarify, there are archived webpages in the catalogue and it makes sense to type them as such. IMO it seems to be a bad idea to override explicit types if no actual use case is in sight. I will have an eye on this in future issues. If the 'w' indicates a type "archivedWebpage" it would add a valuable information to the dataset. Unfortunately this type seems to be completely undocumented. In any case it would be better to open a new ticket for the type thing.

**Comment by acka47** [comment]
> In any case it would be better to open a new ticket for the type thing.

I did so with #152.

**Comment by jschnasse** [comment]
Just for the record. The current index is not sufficient for edoweb, because everything with an entry "archivierte Langzeitresource" in Mab 655e is now typed as "archivedWebpage" which is wrong and also not in accordance with our routine of title imports. Our frontend uses the types to filter search results against lobid, e.g if a user wants to import a title for a monograph, only certain types in lobid are displayed back to the user.  For more information please ask @literarymachine.

**Comment by dr0i** [comment]
Deployed to staging. `lv:ArchivedWebPage` is no more. Please test.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
@jschnasse Please acknowledge if/when this should be made productive.

**Comment by dr0i** [comment]
With last commit the presumption "archived => cannot be of type book" is removed.

**Comment by dr0i** [comment]
deployed to staging

**Comment by jschnasse** [comment]
looks fine!

**Comment by dr0i** [comment]
Deployed to production, closing.
